### ISSUE TITLE
--tensor_split doesn't support array

### ISSUE THREAD

**Issue by thiner** [abetlen/llama-cpp-python#1016]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x ] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x ] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

`--tensor_split` argument should support array of float values. e.g. `[0.5,0.5]`.

# Current Behavior

```
error: argument --tensor_split: invalid float value: '[0.5,0.5]'
```

# Environment and Context
version: 0.2.3
cuda: 12.1

# Failure Information (for bugs)

error: argument --tensor_split: invalid float value: '[0.5,0.5]'

**Comment by brandonrobertz** [comment]
Like Tensor split takes comma separated values, not JSON/Python arrays. Try with `--tensor_split=0.5,0.5`

**Comment by thiner** [comment]
@brandonrobertz same error
```log
 __main__.py: error: argument --tensor_split: invalid float value: '0.5,0.5'
```

**Comment by thiner** [comment]
I filed this bug report at late night(3 am ), I was too tired, so I didn't provide too much details. In fact, I have tried many combinations last night. `[0.5,0.5]`, `0.5,0.5`, even `3,2`(I found this example from llama.cpp project issues list), all failed with the same error message. The only workable value for `--tensor_split` is single float value, I set it to 0.5 currently. 
However, the setting seems not working as expected. I have two GPUs on the server, but the VRAM allocation is equal. One of GPU almost hit the limit, while the other one just a few mega bytes. 
I am running llama-cpp-python v0.2.3, with cublas enabled. The server contains two A10 GPUs. `nvidia-smi` output：
```
# nvidia-smi
Sat Dec 16 14:25:24 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10                     On  | 00000000:F0:00.0 Off |                    0 |
|  0%   46C    P0              58W / 150W |  15572MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A10                     On  | 00000000:F1:00.0 Off |                    0 |
|  0%   49C    P0              64W / 150W |    256MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
#
```

The start command in pod:
```
command:
            - python3
            - '-m'
            - llama_cpp.server
            - '--host'
            - 0.0.0.0
            - '--port'
            - '8000'
            - '--model'
            - /models/mixtral-8x7B-Instruct-v0.1.Q5_K_M.gguf
            - '--model_alias'
            - mixtral-7bx8
            - '--chat_format'
            - chatml
            - '--n_ctx'
            - '16192'
            - '--tensor_split'
            - '0.5'
            - '--n_threads'
            - '8'
            - '--n_gpu_layers'
            - '13'
            - '--use_mlock'
            - 'false'
            - '--use_mmap'
            - 'true'
            - '--interrupt_requests'
            - 'false'
 ```

**Comment by brandonrobertz** [comment]
> I filed this bug report at late night(3 am ), I was too tired, so I didn't provide too much details. In fact, I have tried many combinations last night. `[0.5,0.5]`, `0.5,0.5`, even `3,2`(I found this example from llama.cpp project issues list), all failed with the same error message.

Yeah I've been investigating this and realized the pydantic setting aren't parsing the list of floats type. I'm working on a PR will let you know when I have a branch or something to test.

**Comment by brandonrobertz** [comment]
Okay, so it looks like you actually need to pass them like this: `--tensor_split 0.5 0.5` with a space separator not a comma.

**Comment by thiner** [comment]
Still not working.
`__main__.py: error: argument --tensor_split: invalid float value: '0.5 0.5'`

I did some investigation. I think the problem might be caused by K8s. Pod template accept only string `'[0.5,0.5]'`, instead of `[0.5,0.5]`. When pass this value to llama-cpp-python, it recognize it a float value in string format. Thus the error occurred. 

Can we modify the accept type to comma separated float numbers in string format, and then convert it to list of float?

**Comment by brandonrobertz** [comment]
> Still not working. `__main__.py: error: argument --tensor_split: invalid float value: '0.5 0.5'`
> 
> I did some investigation. I think the problem might be caused by K8s. Pod template accept only string `'[0.5,0.5]'`, instead of `[0.5,0.5]`. When pass this value to llama-cpp-python, it recognize it a float value in string format. Thus the error occurred.
> 
> Can we modify the accept type to comma separated float numbers in string format, and then convert it to list of float?

Yeah you're right about that thing with the string, it's probably coming across like this `--tensor_split '0.5 0.1'` which causes the same issue.

e.g. this fails: `python3 -m llama_cpp.server --model ../..//models/mixtral-8x7b-v0.1.Q5_K_M.gguf --tensor_split "1.0 1.0"`
but this works: `python3 -m llama_cpp.server --model ../..//models/mixtral-8x7b-v0.1.Q5_K_M.gguf --tensor_split 1.0 1.0`

Changing this to support the above and also the comma separated would require changing the type defs for the pydantic settings/model and also do some custom parsing in the init along the way. I started messing with this but it turned out to be kind of complicated because of how validation works (it hits before any of the init code).

**Comment by thiner** [comment]
@brandonrobertz I understood the risk of modifying type interface. Instead of modify existing one, how about add a new argument `str_tensor_split`? If this value is set, convert it python list of float, if not set or both `tensor_split` and `str_tensor_split are set, take the `tensor_split` value.

**Comment by abetlen** [comment]
@thiner does the following work for you

```
command:
            - python3
            - '-m'
            - llama_cpp.server
            - '--host'
            - 0.0.0.0
            - '--port'
            - '8000'
            - '--model'
            - /models/mixtral-8x7B-Instruct-v0.1.Q5_K_M.gguf
            - '--model_alias'
            - mixtral-7bx8
            - '--chat_format'
            - chatml
            - '--n_ctx'
            - '16192'
            - '--tensor_split'
            - '0.5'
            - '0.5'
            - '--n_threads'
            - '8'
            - '--n_gpu_layers'
            - '13'
            - '--use_mlock'
            - 'false'
            - '--use_mmap'
            - 'true'
            - '--interrupt_requests'
            - 'false'
```

**Comment by thiner** [comment]
> @thiner does the following work for you?
> 
> ```
> command:
>             - python3
>             - '-m'
>             - llama_cpp.server
>             - '--host'
>             - 0.0.0.0
>             - '--port'
>             - '8000'
>             - '--model'
>             - /models/mixtral-8x7B-Instruct-v0.1.Q5_K_M.gguf
>             - '--model_alias'
>             - mixtral-7bx8
>             - '--chat_format'
>             - chatml
>             - '--n_ctx'
>             - '16192'
>             - '--tensor_split'
>             - '0.5'
>             - '0.5'
>             - '--n_threads'
>             - '8'
>             - '--n_gpu_layers'
>             - '13'
>             - '--use_mlock'
>             - 'false'
>             - '--use_mmap'
>             - 'true'
>             - '--interrupt_requests'
>             - 'false'
> ```

Yes, it works! Thanks a lot!
