### ISSUE TITLE
(windows) model doesn't generate nothing and stays running

### ISSUE THREAD

**Issue by fcalabrow** [abetlen/llama-cpp-python#102]
Hello. I'm using LlamaCpp in Windows and I'm having the following problem.

Whenever I try to prompt a model (no mather if I do it throughout langchain or directly, with the `generate` method), although the model seems to load correctly, it stays running without returning nothing, not even an error (and I'm forced to restart the kernel). This happens when running the code on a Jupyter Notebook and also on a py file.
```
from langchain.llms import LlamaCpp
llm = LlamaCpp(model_path="models/ggml-model-q4_1.bin")
# output:
# AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 

from langchain import PromptTemplate, LLMChain
template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["question"])
llm_chain = LLMChain(prompt=prompt, llm=llm)
question = "What NFL team won the Super Bowl in the year Justin Bieber was born?"

llm_chain.run(question)
# nothing happens
```
I tried with several models and it is the same. And I also tried with this [suggestion](https://github.com/hwchase17/langchain/issues/3301#issuecomment-1518270418) and although the model loads perfectly well USING API_BASE: http://localhost:8000/v1, I don't get a response either.

Any ideas?

**Comment by jmtatsch** [comment]
How many cpu cores do you have? There is a threading bug in llama.cpp that causes just that behaviour if llama.cpp runs with more threads than cores/hyperthreads.

**Comment by jmtatsch** [comment]
I was able to run your example code line by line and it yielded an acceptable result with vicuna.
I did have some issue with with langchain importing llama_cpp and not finding the libllama.so though but that seems to be another issue.
