### ISSUE TITLE
Why does AI ask and answer itself

### ISSUE THREAD

**Issue by hell99dkx** [abetlen/llama-cpp-python#1031]
![微信截图_20231219130636](https://github.com/abetlen/llama-cpp-python/assets/132538402/87753af0-5253-4fb5-a777-bde2626a9265)
You can see from the picture that my AI will automatically ask the next question after answering one question, and then continue to answer. May I ask which settings should be adjusted?

This is a part of the code：

template = """Question: {question}
Answer: Let's work this out in a step by step way to be sure we have the right answer."""
prompt = PromptTemplate(template=template, input_variables=["question"])
callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])

llm = LlamaCpp(
    model_path="E:\\GAME\\AIGTP\\text-generation-webui-snapshot-2023-12-10\\text-generation-webui-snapshot-2023-12-10\\models\\openchat-3.5-1210.Q5_K_M.gguf",
    temperature=0.85,
    top_p=0.95,
    n_ctx=4096, 
    n_gpu_layers=28,  
    n_batch=512, 
    callback_manager=callback_manager,
)

**Comment by RatDotRaw** [comment]
In my experience, this is the ai model itself and not the libraries fault. 
You can get around this problem by using other models that are finetuned for the specific task you have in mind.
Try using models that are finetuned for chat usage for instace.

**Comment by hell99dkx** [comment]
I don't think it's a problem with the model, it was normal when I first used it. But since I upgraded LLAMA-CPP to support CPU+GPU, he has been asking himself and answering questions since then

**Comment by tk-master** [comment]
I suggest that you do your research about prompt formats and understand what an eos (end of sequence) token is.. 
Basically the model will just keep generating and never send an eos if you are using an unsuitable prompt format.

**Comment by brandonrobertz** [comment]
As others have noted, typically you want to use a prompt format such as:

```
Question: who are you?
Answer:
```

And then let the model complete from `Answer:`. Then you can add `Question:` to your list of stop tokens, preventing it from doing what you're seeing. This is a prompt issue not a llama-cpp-python issue.

**Comment by hell99dkx** [comment]
ok ,thank you
