### ISSUE TITLE
openai server doesnt work with openai package

### ISSUE THREAD

**Issue by nacho00112** [abetlen/llama-cpp-python#1032]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

openai server doesnt work with openai package

**Comment by brandonrobertz** [comment]
What are you trying to do? Paste traceback and the code you're using so people can help you.

**Comment by pintman** [comment]
When I try connecting I get the following error: `INFO:     ::1:60798 - "POST /chat/completions HTTP/1.1" 404 Not Found`

**Comment by milsun** [comment]
> /chat/completions

API endpoint is /v1/chat/completions, rather.

**Comment by pintman** [comment]
Used an older client API version. Thx.

**Comment by riverzhou** [comment]
> When I try connecting I get the following error: `INFO: ::1:60798 - "POST /chat/completions HTTP/1.1" 404 Not Found`

Add v1 at the end of your base url setting.
