### ISSUE TITLE
Build a standalone executable under windows

### ISSUE THREAD

**Issue by ndy200** [abetlen/llama-cpp-python#1042]
I'm trying to build a standalone executable under windows, but the application bundled with PyInstaller won't start. It creates a lot of temp files and that's probably fine. However, the exe file does not start, but returns to the parent directory. I get warnings about tensorflow and some dlls. I just want to build the sample example posted on the page as a test (but I get the same with more complex code).
The py file runs without error.
Is it even possible to build a runnable file from it under windows? Has anyone tried?

The warnings:

20400 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\profiler\internal\_pywrap_traceme.pyd
20406 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_proto_comparators.pyd
20415 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\profiler\internal\_pywrap_profiler.pyd
20423 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\_pywrap_tfprof.pyd
20438 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\lib\io\_pywrap_file_io.pyd
20445 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\lib\io\_pywrap_record_io.pyd
20454 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\_pywrap_utils.pyd
20458 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_op_def_library_pybind.pyd
20470 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_op_def_registry.pyd
20479 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\_pywrap_nest.pyd
20489 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\saved_model\pywrap_saved_model.pyd
20498 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\_pywrap_checkpoint_reader.pyd
20506 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\_pywrap_tensor_float_32_execution.pyd
20510 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\_pywrap_determinism.pyd
21241 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\_pywrap_events_writer.pyd
21259 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\data\experimental\service\_pywrap_server_lib.pyd
21342 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\platform\_pywrap_stacktrace_handler.pyd
21348 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_test_metrics_util.pyd
21356 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\_pywrap_device_lib.pyd
21367 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\grappler\_pywrap_tf_cluster.pyd
21375 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\grappler\_pywrap_tf_optimizer.pyd
21388 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\lib\core\_pywrap_py_func.pyd
21393 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\lib\core\_pywrap_float8.pyd
21399 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\lib\core\_pywrap_custom_casts.pyd
21405 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\lib\core\_pywrap_bfloat16.pyd
21410 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_dtypes.pyd
21416 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\_pywrap_tf_session.pyd
21425 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\_pywrap_debug_events_writer.pyd
21442 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\platform\_pywrap_cpu_feature_guard.pyd
21470 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_pywrap_python_api_dispatcher.pyd
21475 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_pywrap_python_op_gen.pyd
21481 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\_pywrap_kernel_registry.pyd
21488 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\_pywrap_transform_graph.pyd
21496 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\_pywrap_stat_summarizer.pyd
21506 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\grappler\_pywrap_tf_item.pyd
21514 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_pywrap_python_api_parameter_converter.pyd
21523 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_pywrap_python_api_info.pyd
21533 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_op_def_util.pyd
21539 WARNING: lib not found: _pywrap_tensorflow_internal.pyd dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\_errors_test_helper.pyd
22315 WARNING: lib not found: api-ms-win-security-systemfunctions-l1-1-0.dll dependency of C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudart64_110.dll
23236 WARNING: lib not found: api-ms-win-security-systemfunctions-l1-1-0.dll dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\cudart64_12.dll
23341 WARNING: lib not found: api-ms-win-security-systemfunctions-l1-1-0.dll dependency of C:\Users\Ndy\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\cudart64_12.dll

**Comment by Vanfreddy** [comment]
look at this repo is does exactly what you want its a compiled lamma.cpp and some own files wrapped with pyinstaller https://github.com/LostRuins/koboldcpp

**Comment by ndy200** [comment]
Yes, thank you. I used to use a spec file, but really the problem was that pyinstaller didn't include the lama_cpp directory (and I guess it's better to include the dlls.) I'll put it here so it's there:

# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['your.py'],
    pathex=[],
    binaries=[
    ('C:/your/absoluth/path/llama_cpp/llama.dll', '.'),
    ('C:/your/absoluth/path/llama_cpp/llava.dll', '.')
    ],
    datas=[
    ('C:/your/absoluth/path/llama_cpp', 'llama_cpp'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='pteszt',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='pteszt',
)

**Comment by lucazin** [comment]
hello, did work fine to you?     you just put the dll not put pyd ?
