### ISSUE TITLE
performance degradation between 0.2.18 and 0.2.26 with CUDA acceleration?

### ISSUE THREAD

**Issue by eduus710** [abetlen/llama-cpp-python#1054]
# Expected Behavior

- built a new linux box with a 4090, installed CUDA, built new virtual env, installed latest llama-cpp-python (0.2.26), etc
- ran a llama_index application I have been working on; expected performance improvement over my other linux machine with a 4060

# Current Behavior
- performance was significantly worse on new machine/environment

# Environment and Context

ubuntu: 22.04
nvidia-drivers: 535
cuda-toolkit: 12.2
gpu: 4090
llama-cpp-python: 0.2.18 vs 0.2.26
g++: 12
model: mistral-7b-instruct-v0.1.Q5_K_M.gguf

# Steps to Reproduce

- create a new virtual env with python 3.11.7
- install most recent llama-cpp-python
`CMAKE_ARGS="-DLLAMA_CUBLAS=on"  pip install llama-cpp-python --upgrade --force-reinstall --no-cache-dir`
```
Package           Version
----------------- -------
diskcache         5.6.3
llama_cpp_python  0.2.26
numpy             1.26.2
pip               23.2.1
setuptools        65.5.0
typing_extensions 4.9.0
```
- execute the following python code:

```
from llama_cpp import Llama

llm = Llama(model_path="../models/mistral-7b-instruct-v0.1.Q5_K_M.gguf", n_gpu_layers=50)
output = llm(
  "Building a website can be done in 10 simple steps:\\nStep 1:",
  max_tokens=400,
  #stop=[\"Q:\", \"\\n\"], # Stop generating just before the model would generate a new question\n",
  echo=True
)
print(output['choices'][0]['text'])
```
- produces the following timings (note the eval time tokens/sec):

```
llama_print_timings:        load time =     895.08 ms
llama_print_timings:      sample time =      42.78 ms /   400 runs   (    0.11 ms per token,  9349.51 tokens per second)
llama_print_timings: prompt eval time =     895.05 ms /    19 tokens (   47.11 ms per token,    21.23 tokens per second)
llama_print_timings:        eval time =    4954.59 ms /   399 runs   (   12.42 ms per token,    80.53 tokens per second)
llama_print_timings:       total time =    6393.52 ms 
```

- now create a second virtual env
- install llama-cpp-python 0.2.18
`CMAKE_ARGS="-DLLAMA_CUBLAS=on"  pip install llama-cpp-python==0.2.18 --upgrade --force-reinstall --no-cache-dir`
```
Package           Version
----------------- -------
diskcache         5.6.3
llama_cpp_python  0.2.18
numpy             1.26.2
pip               23.2.1
setuptools        65.5.0
typing_extensions 4.9.0
```
- rerun the same code
- produces the following timings:

```
llama_print_timings:        load time =      46.84 ms
llama_print_timings:      sample time =      26.97 ms /   264 runs   (    0.10 ms per token,  9789.38 tokens per second)
llama_print_timings: prompt eval time =      46.80 ms /    20 tokens (    2.34 ms per token,   427.30 tokens per second)
llama_print_timings:        eval time =    2059.39 ms /   263 runs   (    7.83 ms per token,   127.71 tokens per second)
llama_print_timings:       total time =    2468.10 ms
```

in this case the eval tokens/sec is in-line with what i see with native llama_cpp. the performance discrepancy is persistent/consistent across runs.

[highly likely i'm doing something wrong, but am out of ideas how to troubleshoot further]

**Comment by vvsotnikov** [comment]
Add `offload_kqv` flag: `llm = Llama(model_path="../models/mistral-7b-instruct-v0.1.Q5_K_M.gguf", n_gpu_layers=50, offload_kqv=True)`. See #999 for more details.

**Comment by eduus710** [comment]
thank you!

**Comment by eduus710** [comment]
`offload_kqv=True` worked
