### ISSUE TITLE
All requests end with 'finish_reason': 'length'. completion_tokens = 16

### ISSUE THREAD

**Issue by lukasz-kastelik** [abetlen/llama-cpp-python#1056]
I'm running a series of prompts that are 1K-2K tokens long on average. The models I used are:

- seraph-openchat-3.5-1210-slerp.Q4_K_M.gguf
- dolphin-2.6-mixtral-8x7b.Q4_K_M.gguf

I tried tweaking the n_ctx, n_batch, n_threads, n_parts and n_gpu_layers parameters but nothing seems to work.
Every time I run the code, I get responses like this:

`'index': 0, 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 2074, 'completion_tokens': 16, 'total_tokens': 2090}}`
`'index': 0, 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 1202, 'completion_tokens': 16, 'total_tokens': 1218}}`
`'index': 0, 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 2259, 'completion_tokens': 16, 'total_tokens': 2275}}`

Regardless of the prompt length, the completion tokens is always 16. I am running these models on RTX 3090Ti, so the former fits entirely in GPU and the latter needs some offloading to CPU.

What am I doing wrong?

**Comment by zhangchn** [comment]
The `__call__` of `Llama` has a default value 128 for the parameter `max_tokens`.
You should override this value like:
```
    llm = Llama(model_path='your_model_path')
    ...
    result = llm(prompt, max_tokens=-1)
```

**Comment by abetlen** [comment]
Yes @lukasz-kastelik @zhangchn is correct, very sorry for this change, the default was changed to 16 to match the OpenAI API but I only realized quite a bit after that many people are calling the completions function without setting max_tokens.

I'll avoid breaking changes like this in the future, sorry again for the inconveniance.
