### ISSUE TITLE
Loading LoRAs should disable mmap (LoRA + mmap causes segmentation fault)

### ISSUE THREAD

**Issue by horenbergerb** [abetlen/llama-cpp-python#107]
In [the issue that implemented LoRAs in llama.cpp](https://github.com/ggerganov/llama.cpp/pull/820) they say "Using --lora disables mmap since the models have to be modified anyway."

It seems like trying to load a LoRA in llama-cpp-python with mmap enabled causes a segmentation fault. Probably this package should copy the default behavior of llama.cpp and disable mmap when loading LoRAs.

**Comment by abetlen** [comment]
Good catch, will update.
