### ISSUE TITLE
Use llama-cpp-python with an already built version of llama.cpp

### ISSUE THREAD

**Issue by TamirHCL** [abetlen/llama-cpp-python#1070]
**Describe the solution you'd like**
I would like to be able to install llama-cpp-python without building llama.cpp and simply set a variable to the folder of an already build llama.cpp build. 

**Describe alternatives you've considered**
I tried building llama.cpp the way I want (on Windows and with cuBLAS) but it fails when being doing though llama-cpp-python, although it works fine when building llama.cpp as a standalone. 

**Additional context**
Even installing a llama-cpp-python in the basic CPU only way would be OK if it would be easy to swap the llama.cpp build afterwards.

**Comment by Speedway1** [comment]
Yes, same problem on ubunbtu, building with GPU enabled core dumps when inference starts. Doesn't seem very stable. unfortunately localai is even worse, doesn't compile properly. These tools are probably just too new.

**Comment by abetlen** [comment]
Yup this is possible!

```bash
# Build llama.cpp standalone
git clone https://github.com/ggerganov/llama.cpp
mkdir llama.cpp
mkdir build
cd build
cmake .. -DBUILD_SHARED_LIBS=ON
cmake --build . --config Release

# Export path
export LLAMA_CPP_LIB=/path/to/shared/library

# Install llama-cpp-python with LLAMA_BUILD_OFF
CMAKE_ARGS="LLAMA_BUILD=OFF" pip install llama-cpp-python
```

This gives you the most control over the build process however note that the llama.cpp API version must match the version for the version of llama-cpp-python that you're installing.

**Comment by aniljava** [comment]
Having `pip install llama-cpp-python[minimal]`  would be nice to allow use of existing llama.cpp's libllama.so.

@Speedway1 , can you try running with `LLAMA_CPP_LIB` pointing to the  llama.cpp dir and also invoking following in llama.cpp base folder.

    make BUILD_SHARED_LIBS=1 LLAMA_CUBLAS=1 libllama.so -j

**Comment by TamirHCL** [comment]
Amazing - thanks for the answer/clarification!

**Comment by thangld201** [comment]
Hi @abetlen @aniljava @TamirHCL, when installing with 
`cmake ..  -DBUILD_SHARED_LIBS=ON && cmake --build . --config Release`

I got the error
```
/usr/bin/ld: CMakeFiles/test-llama-grammar.dir/test-llama-grammar.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test-llama-grammar.dir/build.make:99: bin/test-llama-grammar] Error 1
make[1]: *** [CMakeFiles/Makefile2:1831: tests/CMakeFiles/test-llama-grammar.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

Does anyone have a solution ?

**Comment by LUXUS1** [comment]
> Yup this is possible!
> 
> ```shell
> # Build llama.cpp standalone
> git clone https://github.com/ggerganov/llama.cpp
> mkdir llama.cpp
> mkdir build
> cd build
> cmake .. -DBUILD_SHARED_LIBS=ON
> cmake --build . --config Release
> 
> # Export path
> export LLAMA_CPP_LIB=/path/to/shared/library
> 
> # Install llama-cpp-python with LLAMA_BUILD_OFF
> CMAKE_ARGS="LLAMA_BUILD=OFF" pip install llama-cpp-python
> ```
> 
> This gives you the most control over the build process however note that the llama.cpp API version must match the version for the version of llama-cpp-python that you're installing.

When I use `cmake .. -DBUILD_SHARED_LIBS=ON`to compile, the following error occurs. What is the reason?In addition, what path should the Export path point to? Thank you~~
```/usr/bin/ld: CMakeFiles/test-tokenizer-1-llama.dir/test-tokenizer-1-llama.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.17'
/usr/bin/ld: /lib/aarch64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test-tokenizer-1-llama.dir/build.make:117: bin/test-tokenizer-1-llama] Error 1
make[1]: *** [CMakeFiles/Makefile2:1912: tests/CMakeFiles/test-tokenizer-1-llama.dir/all] Error 2```

**Comment by sigjhl** [comment]
In case someone doesn't know what the shared library file is (=me), it's the libllama.so file.
LLAMA_CPP_LIB=.../libllama.so

**Comment by NeuralFlux** [comment]
I run into `libggml.so: undefined symbol: llama_max_devices`. I've built llama.cpp with CUDA and built the shared libs. Importing in Python causes that error.

**Comment by LixiangHan** [comment]
In my case, the above solutions do not work for me. I installed llama-cpp-python with the already-built llama.cpp by
```
CMAKE_ARGS="-DLLAMA_CUBLAS=OFF -DCMAKE_PREFIX_PATH=/path/to/llama.cpp/build" pip install llama-cpp-python --no-cache-dir
```

**Comment by tommydvt** [comment]
> CMAKE_ARGS="-DLLAMA_BUILD=OFF" pip install llama-cpp-python

For me I had to export LLAMA_CPP_LIB_PATH=/path/to/shared/lib/directory

**Comment by JackZeng0208** [comment]
@Mauriciocr207 The segmentation fault is caused by llama.cpp (https://github.com/ggml-org/llama.cpp/issues/9289#issuecomment-2788276223), you should build llama.cpp based on code before version b5028
