### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by thiner** [abetlen/llama-cpp-python#1083]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Streaming output should work correctly.

# Current Behavior

Streaming output is interrupted with below error message:
```
{
  "error": true,
  "message": "Unexpected end of JSON input"
}
```

The same API is working properly with same request body if call with Postman, the only difference is header set to `Accept: application/json` in Postman.

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

Running in Docker image, the image information:

- Base image: `nvidia/12.1.0-devel-ubuntu22.04`
- Python: 3.10.2
- Installed llama-cpp-python in Dockerfile by `CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip3 install llama-cpp-python[server]`

# Failure Information (for bugs)

The Web UI shows error message:

```
{
  "error": true,
  "message": "Unexpected end of JSON input"
}
```

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

Just call the `v1/chat/completions` API, and set the header value `Accept: text/event-stream`.

**Note: Many issues seem to be regarding functional or performance issues / differences with `llama.cpp`. In these cases we need to confirm that you're comparing against the version of `llama.cpp` that was built with your python package, and which parameters you're passing to the context.**

Try the following:

1. `git clone https://github.com/abetlen/llama-cpp-python`
2. `cd llama-cpp-python`
3. `rm -rf _skbuild/` # delete any old builds
4. `python -m pip install .`
5. `cd ./vendor/llama.cpp`
6. Follow [llama.cpp's instructions](https://github.com/ggerganov/llama.cpp#build) to `cmake` llama.cpp
7. Run llama.cpp's `./main` with the same arguments you previously passed to llama-cpp-python and see if you can reproduce the issue. If you can, [log an issue with llama.cpp](https://github.com/ggerganov/llama.cpp/issues)

# Failure Logs

There is not any error message output by llama-cpp-python. 
```
llama_print_timings:        load time =    4354.71 ms

 llama_print_timings:      sample time =      14.60 ms /    62 runs   (    0.24 ms per token,  4245.70 tokens per second)

 llama_print_timings: prompt eval time =     189.30 ms /     7 tokens (   27.04 ms per token,    36.98 tokens per second)

 llama_print_timings:        eval time =    2788.22 ms /    61 runs   (   45.71 ms per token,    21.88 tokens per second)

 llama_print_timings:       total time =    3134.24 ms

 Llama.generate: prefix-match hit

 

 llama_print_timings:        load time =    4354.71 ms

 llama_print_timings:      sample time =       1.86 ms /     8 runs   (    0.23 ms per token,  4294.15 tokens per second)

 llama_print_timings: prompt eval time =    1138.13 ms /   128 tokens (    8.89 ms per token,   112.47 tokens per second)

 llama_print_timings:        eval time =     375.45 ms /     7 runs   (   53.64 ms per token,    18.64 tokens per second)

 llama_print_timings:       total time =    1774.18 ms

 INFO:     10.70.0.104:47466 - "POST /v1/chat/completions?path=v1&path=chat&path=completions HTTP/1.1" 200 OK

 Llama.generate: prefix-match hit

 INFO:     10.70.0.200:16312 - "POST /v1/chat/completions?path=v1&path=chat&path=completions HTTP/1.1" 200 OK
```

Please include any relevant log snippets or files. If it works under one configuration but not under another, please provide logs for both configurations and their corresponding outputs so it is easy to see where behavior changes.

Also, please try to **avoid using screenshots** if at all possible. Instead, copy/paste the console output and use [Github's markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to cleanly format your logs for easy readability.

**Comment by aniljava** [comment]
This is the limitation of the FastAPI. By default it expects, `Accept: application/json`.

https://github.com/abetlen/llama-cpp-python/pull/1088 addresses.

OpenAI support the `text/streaming`  as Accept header as well as response is marked same. But its openapi.yaml specs or documentation does not explicitly call out text/streaming.

**Comment by thiner** [comment]
Thanks so much for your quick patching. I will check-out your code changes and verify locally.

**Comment by thiner** [comment]
I tried latest code, seems the issue still existing. Even worse, the output becomes all "#######".
![image](https://github.com/abetlen/llama-cpp-python/assets/1897227/49e4d44a-6188-4924-9579-50af2a2a39a3)

**Comment by aniljava** [comment]
@thiner ,
The `###...` is related to `offload_kqv` related bug in llama.cpp.
https://github.com/abetlen/llama-cpp-python/issues/1089#issuecomment-1894463975

pass, `--offload_kqv true` with the server command, `offload_kqv = True` with the Llama init.

**Comment by thiner** [comment]
I tested with the latest version `v0.2.30`, most of the streaming output can complete normally. But it still appearing the `Unexpected end of JSON...` error occasionally. I encountered the error once this morning in roughly 30 calls.

**Comment by abetlen** [comment]
@thiner do you know what the finish reason is? I believe grammar sampling should suppress the eos token but this may not be the case and it terminates before enclosing the end of the input.

**Comment by thiner** [comment]
I don't know, I couldn't find any clue from the logs. It just didn't output the timing information, as I pasted at the beginning of this thread.

**Comment by thiner** [comment]
Unfortunately, v0.2.38 encountered this problem again. I tried several mixtral models, all responses are interrupted after maybe 100~200 words.
