### ISSUE TITLE
API will lock up if  n_threads > actual threads

### ISSUE THREAD

**Issue by jmtatsch** [abetlen/llama-cpp-python#110]
I have 6 physical cores, 12 with hyperthreading. 
if n_threads <= 12 it runs as expected.
if n_threads > 12 it will load the model and then lock up with high cpu utilization.

Not sure if this should be prevented in llama-cpp-python or upstream?

**Comment by abetlen** [comment]
@jmtatsch I've actually run into this too, do you mind checking if this occurs in llama.cpp as well? If so can you add an issue there and mention it here in a follow up so we can track it here.

I'll add a temporary fix to clamp max `n_threads` to `cpu_count`.

**Comment by jmtatsch** [comment]
Happens in llama.cpp as well 
https://github.com/ggerganov/llama.cpp/issues/1159
