### ISSUE TITLE
How Do I Use CPU Deployment Mode to Run in an Environment with GPUs?

### ISSUE THREAD

**Issue by hzrlsd** [abetlen/llama-cpp-python#1104]
I plan to use the CPU on my server to run the quantization file ggml-model-q4_0.gguf of Mixtral-8x7B-Instruct-v0.1, but the model always runs automatically on the gpu, how to set it up in Llama's constructor ？
<img width="629" alt="1705634860191" src="https://github.com/abetlen/llama-cpp-python/assets/140566703/6839da30-a130-4d3b-9633-836b97f4d059">

Thanks!

**Comment by abetlen** [comment]
Setting `n_gpu_layers=0` and `offload_qkv=False` should work, are you having issues?
