### ISSUE TITLE
Server doesn't work with Python 3.8

### ISSUE THREAD

**Issue by rgerganov** [abetlen/llama-cpp-python#1108]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Working server with python3.8

# Current Behavior

```
$ python3 -m llama_cpp.server
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sgx/Projects/cpu-ml-cc/llama-cpp-python/venv/lib/python3.8/site-packages/llama_cpp/server/__main__.py", line 39, in <module>
    from llama_cpp.server.cli import add_args_from_model, parse_model_from_args
  File "/home/sgx/Projects/cpu-ml-cc/llama-cpp-python/venv/lib/python3.8/site-packages/llama_cpp/server/cli.py", line 86, in <module>
    T = TypeVar("T", bound=type[BaseModel])
TypeError: 'type' object is not subscriptable
```

# Environment and Context

The server started using python3.10+ features from version 0.2.25 and it is no longer working with python3.8. The last version which works with python3.8 is 0.2.24

**Comment by abetlen** [comment]
@rgerganov should be fixed now in v0.2.31
