### ISSUE TITLE
Does the tokenize function work as expected? 

### ISSUE THREAD

**Issue by serena-mafinancial** [abetlen/llama-cpp-python#115]
https://github.com/abetlen/llama-cpp-python/blob/cbd26fdcc116dc692308f2d262083dfd1ddaa142/llama_cpp/llama_cpp.py#L274

I am trying to implement LlamaCpp with Vicuna model in LangChain Pandas Dataframe Agent. 

This is my code: 
![image](https://user-images.githubusercontent.com/129805157/234478919-e5ce1ab6-dc5d-42d8-89c5-cba39b89887a.png)

This is the error: 
![image](https://user-images.githubusercontent.com/129805157/234478963-5e9e1684-2a7f-4a7d-87db-60a509a70e74.png)
![image](https://user-images.githubusercontent.com/129805157/234478982-53951431-289a-4554-a5d8-c41d8f432ab4.png)
![image](https://user-images.githubusercontent.com/129805157/234479022-0a97cc97-804d-4b7d-bb04-4f013ed08868.png)
![image](https://user-images.githubusercontent.com/129805157/234479052-ec909bf5-9417-4db6-8ded-098cfa9f2879.png)
![image](https://user-images.githubusercontent.com/129805157/234479084-782bdb58-7d74-4db1-8e7c-faee377a33e6.png)
![image](https://user-images.githubusercontent.com/129805157/234479111-c44089f0-79f6-4d62-964d-ed4d8480f2a9.png)
![image](https://user-images.githubusercontent.com/129805157/234479130-0ad8793c-0a89-48d4-a202-ca3cc01848cc.png)

Which led me to believe that the tokenize function has not been implemented properly. I posted about this issue as well in LangChain Github: https://github.com/hwchase17/langchain/issues/3569 

The n_tokens returned is -680, which should not be negative. Not sure what's causing this issue...

**Comment by abetlen** [comment]
It should work, can you set `n_ctx=1024` when you initialize the `LlamaCpp` class?

**Comment by serena-mafinancial** [comment]
Thanks! It worked with n_ctx=2048.
