### ISSUE TITLE
How to use speculative decoding?

### ISSUE THREAD

**Issue by irthomasthomas** [abetlen/llama-cpp-python#1164]
Hello, 

I've read the docs and tried a few different ways to start speculative decoding, but they all fail. 
E.g.
 error: unrecognized arguments: --draft_model=prompt-lookup-decoding --draft_model_num_pred_tokens=2

or
Extra inputs are not permitted [type=extra_forbidden, input_value='prompt-lookup-decoding', input_type=str]

So what is the correct way to start an openai server with speculative decoding?

Cheers.

**Comment by abetlen** [comment]
Hey @irthomasthomas that should work, are you sure you have the latest version installed?

```
python3 -c "import llama_cpp; print(llama_cpp.__version__)"
```

If you run that the version should be at least `0.2.38` for speculative decoding support.

**Comment by irthomasthomas** [comment]
Thanks @abetlen, I forgot I was running multiple python environments... Anyway, after updating, I'm now getting a new problem: `ValueError: Attempt to split tensors that exceed maximum supported devices. Current LLAMA_MAX_DEVICES=1`

Is that related to this? https://github.com/ggerganov/llama.cpp/pull/5240

**Comment by irthomasthomas** [comment]
I opened a new issue as its unrelated to this one. #1166
