### ISSUE TITLE
llama cpp submodule `kompute` is not included in the sdist.

### ISSUE THREAD

**Issue by Bing-su** [abetlen/llama-cpp-python#1165]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

recursive checkout when running workflows.

# Current Behavior

![스크린샷 2024-02-07 131004](https://github.com/abetlen/llama-cpp-python/assets/37621276/bf8d3291-1da7-4f45-9e48-2a4f8abbc0fc)

https://github.com/ggerganov/llama.cpp

![스크린샷 2024-02-07 131024](https://github.com/abetlen/llama-cpp-python/assets/37621276/a7028e19-1586-48c4-b912-8eaa18e99be6)

**Comment by abetlen** [comment]
@Bing-su thanks for reporting this, should be fixed on `main` and included in the next release!
