### ISSUE TITLE
Add multimodal support to server

### ISSUE THREAD

**Issue by tctrautman** [abetlen/llama-cpp-python#1168]
**Is your feature request related to a problem? Please describe.**
If I understand correctly, multimodal requests have the below format:
```
{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "image_url",
          "image_url": {
            "url": <image_url>
          }
        },
        {
          "type": "text",
          "text": <text>
        }
      ]
    }
  ]
}
```
Notice that `content` is an array, but the server seems to require that `content` is a string:
https://github.com/abetlen/llama-cpp-python/blob/901827013b732d74f1f67033062d13a6204a62bd/llama_cpp/server/types.py#L183-L185

And this is - I believe - why the server returns the bellow error when I send a request with the above structure:
```
{
	"error": {
		"message": "can only concatenate str (not \"list\") to str",
		"type": "internal_server_error",
		"param": null,
		"code": null
	}
}
```

**Describe the solution you'd like**
I believe that adding multimodal support to the server might just be a few-line change to the server's validation, but I could very easily be wrong about that.

**Describe alternatives you've considered**
N/A

**Additional context**
Two things: (1) thanks so much for creating this -- it's super impressive -- and (2) I typically don't use Python, so please forgive any silly mistakes on my part.

**Comment by abetlen** [comment]
@tctrautman let me look into this because it was previously working through the server as well but it may have been broken in a bad merge.

**Comment by abetlen** [comment]
@tctrautman I can't seem to reproduce the error

```python
from openai import OpenAI

client = OpenAI(base_url="http://localhost:8000/v1", api_key="sk-1234")
response = client.chat.completions.create(
    model="gpt-4-vision-preview",
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://user-images.githubusercontent.com/1991296/230134379-7181e485-c521-4d23-a0d6-f7b3b61ba524.png",
                    },
                },
                {"type": "text", "text": "What does the image say."},
            ],
        }
    ],
    response_format={ 
        "type": "json_object", 
        "schema": {
            "type": "object",
            "properties": {
                "text": {"type": "string"}
            },
            "required": ["text"]
        }
    }
)
import json
print(json.loads(response.choices[0].message.content))
```

**Comment by tctrautman** [comment]
Thanks for looking into this, @abetlen. I just confirmed this was a dumb mistake on my part.  I accidentally loaded up a llava 1.6 model while starting the server -- requests using llava 1.5 work as expected.

**Comment by hockeybro12** [comment]
Hi @abetlen  I'm having issues running multimodal data with the server. I'm on version 0.2.33 (can't get future versions to work with GPU). It seems like the Multimodal model either doesn't read my text, or image, or both. I tried passing the images several ways (below and as described in the OpenAI API where they explain how to [upload base 64 images](https://platform.openai.com/docs/guides/vision) (i.e. `requests.post("http://128.10.12.202:47525/v1/chat/completions", headers=headers, json=payload`) ). However, both methods aren't working.

I run the multimodal server with the recommended download model, like so: `CUDA_VISIBLE_DEVICES=0,1 python3 -m llama_cpp.server --model Llama/models--mys--ggml_llava-v1.5-7b/snapshots/9b713a64048c7f982ec3969e60e9f61f7a2730c2/ggml-model-q4_k.gguf  --n_gpu_layers 83 --host 128.10.12.202 --port 47525 --n_ctx 4096` 

And test it client side like so:
```
from openai import OpenAI
client = OpenAI(base_url="http://128.10.12.202:47525/v1", api_key="sk-xxx")

response = client.chat.completions.create(
    model="gpt-4-vision-preview",
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://user-images.githubusercontent.com/1991296/230134379-7181e485-c521-4d23-a0d6-f7b3b61ba524.png",
                    },
                },
                {"type": "text", "text": "What does the image say."},
            ],
        }
    ],
    response_format={ 
        "type": "json_object", 
        "schema": {
            "type": "object",
            "properties": {
                "text": {"type": "string"}
            },
            "required": ["text"]
        }
    }
)
import json
print(response.choices[0])
print(json.loads(response.choices[0].message.content))
```

I get bad responses, like so:
```
Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='{"inst_id": "2015-06-30T14:28:30", "user_id": "456789"}\n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n\n \n \n \n \n \n\n \n \n \n \n\n \n \n \n \n \n \n \n \n \n \n \n\n \n \n \n \n \n \n \n\n \n \n \n \n', role='assistant', function_call=None, tool_calls=None))
{'inst_id': '2015-06-30T14:28:30', 'user_id': '456789'}
```

or:
```{'instructions': 'Instructions for this example go here'}```

They are different every time, and it seems like the Multimodal model either isn't reading my image correctly, or my text prompt correctly, or both. 

Any idea what I could be doing wrong? Thanks!
