### ISSUE TITLE
Support for embedding models

### ISSUE THREAD

**Issue by rlancemartin** [abetlen/llama-cpp-python#1189]
Recently https://github.com/ggerganov/llama.cpp/pull/5468 merged in llama.cpp that enables [Nomic Embed](https://blog.nomic.ai/posts/nomic-embed-text-v1).

Also we have [GGUF weights](https://huggingface.co/nomic-ai/nomic-embed-text-v1-GGUF).

Confirmed it works for me locally (Mac M2, 32GB):
```
./embedding -ngl 99 -m models/nomic-embd/nomic-embed-text-v1.Q4_K_S.gguf -c 8192 -b 8192 --rope-scaling yarn --rope-freq-scale .75 -p 'search_query: What is TSNE?'
```

It looks like we may need an integration in llama-cpp-python for embedding models?

Edit: talking with @cebtenzzre -

```
here is llama-cpp-python support but only in the low-level API atm - you can call llama_cpp.llama_get_embeddings_ith in the same way llama.cpp's embedding.cpp does
```
I need to see if this is sufficient for popular llama-cpp-python integrations such as LangChain.

**Comment by abetlen** [comment]
This is actually in the high-level API through the `embed` and `create_embeddings` functions. @iamlemec just contributed an awesome PR to support batched embeddings as well in #1186 

I'll update the README though to make this more clear!

**Comment by AndriyMulyar** [comment]
Nomic has made some GGUF's for ya:
https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF
https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF

https://blog.nomic.ai/posts/nomic-embed-matryoshka

**Comment by rlancemartin** [comment]
Yup! Confirmed all works :) 

```
from llama_cpp import Llama
embd_model_path = "/Users/rlm/Desktop/Code/llama.cpp/models/nomic-embd/nomic-embed-text-v1.Q4_K_S.gguf"
embd = Llama(
    model_path=embd_model_path,
    embedding=True
)
embedding = embd.embed("search_query: What is TSNE?")
```

I'll create a new text embedding integration within LangChain for this.

**Comment by abetlen** [comment]
@AndriyMulyar thank you so much for the model, can't wait to try it out!

**Comment by abetlen** [comment]
@rlancemartin just published some fixes for the embeddings, recommend upgrading (some pooling issues and output was broken when passing a single `str`)

**Comment by rlancemartin** [comment]
Thanks! Will do.

**Comment by rlancemartin** [comment]
Ah excellent. I just upgraded to 2.4.4.

Can confirm now that the most recent GGUF files from Nomic work. 

```
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import WebBaseLoader
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import LlamaCppEmbeddings
from langchain_nomic.embeddings import NomicEmbeddings

# Load
url = "https://lilianweng.github.io/posts/2023-06-23-agent/"
loader = WebBaseLoader(url)
docs = loader.load()

# Split
text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    chunk_size=500, chunk_overlap=100
)
all_splits = text_splitter.split_documents(docs)

# Embed and index
embd_model_path = "/Users/rlm/Desktop/Code/llama.cpp/models/nomic-embd/nomic-embed-text-v1.5.f16.gguf"
embedding = LlamaCppEmbeddings(model_path=embd_model_path, n_batch=512)

# Index
vectorstore = Chroma.from_documents(
    documents=all_splits,
    collection_name="rag-chroma",
    embedding=embedding,
)
retriever = vectorstore.as_retriever()
```

Before I saw an error:
```
llama_model_load: error loading model: error loading model hyperparameters: key not found in model: nomic-bert.pooling_layer
llama_load_model_from_file: failed to load model
```
