### ISSUE TITLE
initialization llavachathandler in colab causes error UnsupportedOperation: fileno

### ISSUE THREAD

**Issue by barinov274** [abetlen/llama-cpp-python#1190]
I just ran this code
```python
from llama_cpp import Llama
from llama_cpp.llama_chat_format import Llava15ChatHandler

# Create a chat handler
chat_handler = Llava15ChatHandler(clip_model_path="/root/.cache/huggingface/hub/models--cmp-nct--llava-1.6-gguf/snapshots/03a9a9f46fdf376a27f1f38eb733f2821e874fbf/mmproj-mistral7b-f16-q6_k.gguf")
...
```
and got an error:
```
---------------------------------------------------------------------------

UnsupportedOperation                      Traceback (most recent call last)

<ipython-input-8-ca17ac38a2cc> in <cell line: 5>()
      3 
      4 # Create a chat handler
----> 5 chat_handler = Llava15ChatHandler(clip_model_path="/root/.cache/huggingface/hub/models--cmp-nct--llava-1.6-gguf/snapshots/03a9a9f46fdf376a27f1f38eb733f2821e874fbf/mmproj-mistral7b-f16-q6_k.gguf", verbose=False)
      6 
      7 # Initialize the Llama model

1 frames

/usr/local/lib/python3.10/dist-packages/llama_cpp/_utils.py in __enter__(self)
     27             return self  # Return the instance without making changes
     28 
---> 29         self.old_stdout_fileno_undup = self.sys.stdout.fileno()
     30         self.old_stderr_fileno_undup = self.sys.stderr.fileno()
     31 

UnsupportedOperation: fileno

```

**Comment by johnwick123f** [comment]
@barinov274 just add verbose=True and it works.
so it should be like

chat_handler = Llava15ChatHandler(clip_model_path="/root/.cache/huggingface/hub/models--cmp-nct--llava-1.6-gguf/snapshots/03a9a9f46fdf376a27f1f38eb733f2821e874fbf/mmproj-mistral7b-f16-q6_k.gguf", verbose=True)

**Comment by congson1293** [comment]
I have the same issue when run with version 0.2.44 in Google Colab. I don't want to show log so I just set verbose=False. Waiting for the next version to fix the issue.

**Comment by michael-wettach** [comment]
> @barinov274 just add verbose=True and it works. so it should be like
> 
> chat_handler = Llava15ChatHandler(clip_model_path="/root/.cache/huggingface/hub/models--cmp-nct--llava-1.6-gguf/snapshots/03a9a9f46fdf376a27f1f38eb733f2821e874fbf/mmproj-mistral7b-f16-q6_k.gguf", verbose=True)

Added that parameter, but now the Colab runtime crashes on executing this command. Any other workarounds?

**Comment by abetlen** [comment]
@barinov274 this should be fixed now in the latest releases, please let me know if you still experience this bug!
