### ISSUE TITLE
LLAVA v1.6

### ISSUE THREAD

**Issue by enrico07** [abetlen/llama-cpp-python#1204]
Hello,

I was wondering if it is compatible with LLAVA v1.6 34B. If it is so, how can I implement it? Should I use the same code of LLAVA v1.5?

**Comment by Robzz** [comment]
Seems like it's compatible, I just tried running the `llava-v1.6-mistral-7b.Q5_K_M.gguf` model using the LLaVa 1.5 example code and it's been working fine so far.
