### ISSUE TITLE
OrangePi5 FP16_VA = 0, while been activated for llama.cpp

### ISSUE THREAD

**Issue by NeonBohdan** [abetlen/llama-cpp-python#1215]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [+] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [+] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [+] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [+] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Current Behavior

I have runned `pip install llama-cpp-python` and llama.cpp `make` on `OrangePi5`
And saw that with `python` it's 20% slower
I found that it's may be relevant to the difference in compilation parameters 

`llama-cpp-python`
```
AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 |
```
`llama.cpp`
```
AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 |
```

# Expected Behavior

You can see that in `llama-cpp-python` `FP16_VA = 0` while it's different for the default installation of `llama.cpp` 
If it not uses `vector arithmetic` on ARM sure it will be slower, I don't see the way to activate it, it's auto thing

**Comment by FireballDWF** [comment]
Observed same FP16_VA=0 issue on AWS c6gd instance type (Graviton2 CPU)

**Comment by Yuchen-Cao** [comment]
> # Prerequisites
> Please answer the following questions for yourself before submitting an issue.
> 
> * [+] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
> * [+] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
> * [+] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
> * [+] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.
> 
> # Current Behavior
> I have runned `pip install llama-cpp-python` and llama.cpp `make` on `OrangePi5` And saw that with `python` it's 20% slower I found that it's may be relevant to the difference in compilation parameters
> 
> `llama-cpp-python`
> 
> ```
> AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 |
> ```
> 
> `llama.cpp`
> 
> ```
> AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 |
> ```
> 
> # Expected Behavior
> You can see that in `llama-cpp-python` `FP16_VA = 0` while it's different for the default installation of `llama.cpp` If it not uses `vector arithmetic` on ARM sure it will be slower, I don't see the way to activate it, it's auto thing

At first glance I thought we met the same problem, but I doublechecked and found out that in my situation even llama.cpp had been built with FP16_VA=0.

I am quite sure my device supports FP16_VA since it supports armv8.2-a.

So could you please kindly teach me how to eable FA16_VA option during `make` in llama.cpp itself? Did you barely use `make` and by default it turned on FP16_VA?

**Comment by NeonBohdan** [comment]
@Yuchen-Cao just run `make`
So can't help you with your problem

**Comment by WCSY-YG** [comment]
same question

**Comment by GiviMAD** [comment]
Hello,

For me when building with cmake I've got the FA16_VA enabled when passing march armv8.2-a+fp16 or native as CFLAGS.

```sh
mkdir build
cd build/
cmake -DCMAKE_C_FLAGS="-march=armv8.2-a+fp16" ..
cmake --build . --config Release
```

So I think you can get it enabled by installing like:

```sh
CFLAGS=-march=armv8.2-a+fp16 pip install llama-cpp-python
```

I didn't try it, hope it helps.

**Comment by NeonBohdan** [comment]
@GiviMAD it works for me, great thanks
After `CFLAGS=-march=armv8.2-a+fp16 pip install llama-cpp-python`
Got `FP16_VA = 1`
