### ISSUE TITLE
Builds are slow on MacOS with Apple silicon

### ISSUE THREAD

**Issue by zeitderforschung** [abetlen/llama-cpp-python#122]
Here are the different system infos after loading a model:

**llama.cpp**
```
system_info: n_threads = 4 / 12 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 |
```

* BLAS, NEON, ARM_FMA and FP16_VA is enabled

**llama-cpp-python**
```
AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
```

* BLAS and SSE3 is enabled, but NEON, ARM_FMA is missing 🤔

**Comment by matthoffner** [comment]
I had a similar issue and upgrading fixed where I see `NEON = 1` and `ARM_FMA = ` now.

`FORCE_CMAKE=1 pip install --upgrade llama-cpp-python`

**Comment by zeitderforschung** [comment]
@matthoffner I unfortunately had no success with your tip with the current version.

**Comment by zeitderforschung** [comment]
I reinstalled with `pip install -U git+https://github.com/abetlen/llama-cpp-python.git`, but without the `FORCE_CMAKE=1` flag and now it works as expected on Apple silicon. Be sure that the command `uname -m` outputs "arm64".
