### ISSUE TITLE
Llava1.5 multi-modal not working since version 0.2.26

### ISSUE THREAD

**Issue by psychodinae** [abetlen/llama-cpp-python#1225]
tried out the code from the docs over here: 
https://llama-cpp-python.readthedocs.io/en/latest/#multi-modal-models

And I used a ggml-model-q4_k.gguf from:
[huggingface.co/mys/ggml_bakllava-1](https://huggingface.co/mys/ggml_bakllava-1/tree/main)

I used the most recent version (v0.2.51) and all since v0.2.46 have the same error.

version version 0.2.25 works fine.

Tested it on both Windows and my VM running Ubuntu 22.04.4.

**code**:
```python
from llama_cpp import Llama
from llama_cpp.llama_chat_format import Llava15ChatHandler

chat_handler = Llava15ChatHandler(clip_model_path="./models/mmproj-model-f16.gguf")
llm = Llama(
    model_path="./models/ggml-model-q4_k.gguf",
    chat_handler=chat_handler,
    n_ctx=1024,  # n_ctx should be increased to accomodate the image embedding
    logits_all=True,  # needed to make llava work
)
r = llm.create_chat_completion(
    messages=[
        {"role": "system", "content": "You are an assistant who perfectly describes images."},
        {
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {
                    "url": "https://i.imgur.com/LYw1UnI.jpeg"}},
                {"type": "text", "text": "Describe this image in detail please."}
            ]
        }
    ]
)

print(r)
```

**Error**:

```
Traceback (most recent call last):
  File "/home/vboxuser/PycharmProjects/vtai/test_llama_cpp_bak_llama.py", line 11, in <module>
    r = llm.create_chat_completion(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/PycharmProjects/vtai/.venv/lib/python3.11/site-packages/llama_cpp/llama.py", line 1638, in create_chat_completion
    return handler(
           ^^^^^^^^
  File "/home/vboxuser/PycharmProjects/vtai/.venv/lib/python3.11/site-packages/llama_cpp/llama_chat_format.py", line 1959, in __call__
    self._llava_cpp.llava_image_embed_make_with_bytes(
TypeError: this function takes at least 4 arguments (0 given)
```

**Comment by abetlen** [comment]
@psychodinae thank you for reporting this, it should be fixed in v0.2.52

In v0.2.46 the way that the low level api functions work changed so that they bind directly to the shared library functions instead of first passing through another python. This reduces the overhead of making ffi calls however it also means these functions became positional argument only. Unfortunately in some places in the code base this change was missed but it should be fixed everywhere now.

**Comment by psychodinae** [comment]
> @psychodinae thank you for reporting this, it should be fixed in v0.2.52
> 
> In v0.2.46 the way that the low level api functions work changed so that they bind directly to the shared library functions instead of first passing through another python function. This reduces the overhead of making ffi calls but it also means the functions became positional argument only. Unfortunately in some places in the code base we were using keyword arguments for low level functions, I had migrated most of those over but missed these.

thanks! An additional improvement would be to add a basic user-agent to the Llava15ChatHandler load_image() function because some images on the internet return error 403 without a user agent.

**Comment by ParisNeo** [comment]
Hi, is there a simple fix for that?
TypeError: this function takes at least 4 arguments (0 given)
I can't seem to make any llava based model to work :(

**Comment by abetlen** [comment]
> Hi, is there a simple fix for that? TypeError: this function takes at least 4 arguments (0 given) I can't seem to make any llava based model to work :(

Hey @ParisNeo yes you should be able to upgrade and get this to work now, are you still expeeriencing the issue on the latest version?

**Comment by ParisNeo** [comment]
Hi, I have reverted to v 0.2.44. I need to wait for someone to rebuild it for all platforms then i'll migrate.

**Comment by alexandrebcaruso** [comment]
I have version llama_cpp_python==0.2.56 and this is happening to me using keyword arguments. btw not only for `llava_image_embed_make_with_bytes` but also `llava_eval_image_embed`. 

fix: changing to using positional arguments works for me. thanks!
