### ISSUE TITLE
Automatically setting eos/bos_token from metadata does not work when falling back to Jinja2ChatFormatter

### ISSUE THREAD

**Issue by CISC** [abetlen/llama-cpp-python#1228]
When falling back to Jinja2ChatFormatter in Llama.__init__() the following code erroneously sets eos_token and bos_token to blank strings, causing the Jinja2 template to malfunction and the model to not respond:

```python
                eos_token = self.detokenize([eos_token_id]).decode("utf-8")
                bos_token = self.detokenize([bos_token_id]).decode("utf-8")
```

If I change this piece of code to the following the Jinja2 template works as it should and the model responds correctly:

```python
                eos_token = self._model.token_get_text(eos_token_id)
                bos_token = self._model.token_get_text(bos_token_id)
```

However this might not be the appropriate solution, hence no PR.

**Comment by abetlen** [comment]
@CISC I believe that's correct thank you! If you want to open a PR I'll merge it!

**Comment by CISC** [comment]
Done #1230
