### ISSUE TITLE
Failed to build, problem with the CMake installation

### ISSUE THREAD

**Issue by kabo** [abetlen/llama-cpp-python#123]
```
$ pipenv install -v llama-cpp-python
Installing llama-cpp-python...
Resolving llama-cpp-python...
Installing...
Installing package: llama-cpp-python
⠋ Installing llama-cpp-python...Writing supplied requirement line to temporary file: 'llama-cpp-python'
Installing 'llama-cpp-python'
$ /home/kabo/.local/share/virtualenvs/gpt4all-py-vRusQcUg/bin/python /home/kabo/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/pip/__pip-runner__.py install --no-input --verbose --upgrade --exists-action=i -r /tmp/pipenv-n34989xl-requirements/pipenv-983_spqy-requirement.txt -i https://pypi.org/simple
Using source directory: '/home/kabo/.local/share/virtualenvs/gpt4all-py-vRusQcUg/src'
⠸ Installing llama-cpp-python...[31m[1mError: [0m An error occurred while installing [32mllama-cpp-python[0m!
Error text: Using pip 23.1 from /home/kabo/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/pip (python 3.10)
Collecting llama-cpp-python (from -r /tmp/pipenv-n34989xl-requirements/pipenv-983_spqy-requirement.txt (line 1))
  Using cached llama_cpp_python-0.1.38.tar.gz (1.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.5.0 in /home/kabo/.local/share/virtualenvs/gpt4all-py-vRusQcUg/lib/python3.10/site-packages
(from llama-cpp-python->-r /tmp/pipenv-n34989xl-requirements/pipenv-983_spqy-requirement.txt (line 1)) (4.5.0)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml): started
  Building wheel for llama-cpp-python (pyproject.toml): finished with status 'error'
Failed to build llama-cpp-python

[36m  Running command pip subprocess to install build dependencies
  Collecting setuptools>=42
    Using cached setuptools-67.7.2-py3-none-any.whl (1.1 MB)
  Collecting scikit-build>=0.13
    Using cached scikit_build-0.17.2-py3-none-any.whl (82 kB)
  Collecting cmake>=3.18
    Using cached cmake-3.26.3-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (24.0 MB)
  Collecting ninja
    Using cached ninja-1.11.1-py2.py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (145 kB)
  Collecting distro (from scikit-build>=0.13)
    Using cached distro-1.8.0-py3-none-any.whl (20 kB)
  Collecting packaging (from scikit-build>=0.13)
    Using cached packaging-23.1-py3-none-any.whl (48 kB)
  Collecting tomli (from scikit-build>=0.13)
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting wheel>=0.32.0 (from scikit-build>=0.13)
    Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
  Installing collected packages: ninja, cmake, wheel, tomli, setuptools, packaging, distro, scikit-build
  Successfully installed cmake-3.26.3 distro-1.8.0 ninja-1.11.1 packaging-23.1 scikit-build-0.17.2 setuptools-67.7.2 tomli-2.0.1 wheel-0.40.0
  Running command Getting requirements to build wheel
  running egg_info
  writing llama_cpp_python.egg-info/PKG-INFO
  writing dependency_links to llama_cpp_python.egg-info/dependency_links.txt
  writing requirements to llama_cpp_python.egg-info/requires.txt
  writing top-level names to llama_cpp_python.egg-info/top_level.txt
  reading manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
  adding license file 'LICENSE.md'
  writing manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-oybpwuer/llama_cpp_python.egg-info
  writing /tmp/pip-modern-metadata-oybpwuer/llama_cpp_python.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-oybpwuer/llama_cpp_python.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-oybpwuer/llama_cpp_python.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-oybpwuer/llama_cpp_python.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-oybpwuer/llama_cpp_python.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-oybpwuer/llama_cpp_python.egg-info/SOURCES.txt'
  adding license file 'LICENSE.md'
  writing manifest file '/tmp/pip-modern-metadata-oybpwuer/llama_cpp_python.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-oybpwuer/llama_cpp_python-0.1.38.dist-info'
  Running command Building wheel for llama-cpp-python (pyproject.toml)
  Traceback (most recent call last):
    File "/tmp/pip-build-env-kb8h2mwj/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/tmp/pip-build-env-kb8h2mwj/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 148, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "/tmp/pip-build-env-kb8h2mwj/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
      raise SKBuildError(msg) from err

  Problem with the CMake installation, aborting build. CMake executable is
/tmp/pip-build-env-kb8h2mwj/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/kabo/.local/share/virtualenvs/gpt4all-py-vRusQcUg/bin/python
/home/kabo/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel
/tmp/tmp3vzjc4i8
  cwd: /tmp/pip-install-_gikbftc/llama-cpp-python_b81308b1618341d29fdbefb222daaa90
  ERROR: Failed building wheel for llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
[0m
[36mUsing pip 23.1 from /home/kabo/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/pip (python 3.10)
Collecting llama-cpp-python
  Using cached llama_cpp_python-0.1.38.tar.gz (1.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.5.0 in /home/kabo/.local/share/virtualenvs/gpt4all-py-vRusQcUg/lib/python3.10/site-packages
(from llama-cpp-python->-r /tmp/pipenv-n34989xl-requirements/pipenv-983_spqy-requirement.txt (line 1)) (4.5.0)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml): started
  Building wheel for llama-cpp-python (pyproject.toml): finished with status 'error'
Failed to build llama-cpp-python
[0m
✘ Installation Failed
```

I tried with `pip install --user llama-cpp-python`, same result.

Anyone else seen this?
pip 23.0.1, pipenv 2023.04.20, python 3.10, artix linux

**Comment by minarchist** [comment]
Try:
`pip install --upgrade cmake`

**Comment by Galaxy-Ding** [comment]
same problems, i have upgrade gcc to 11.1.0, can't work either.

**Comment by gjmulder** [comment]
It isn't clear what the error is from the log.

Can you try building `llama.cpp` using both `make` and `cmake` and see if that works? There was an issue a while back with old versions of `cmake`, but I think `llama.cpp` has a `cmake` version check, now.

**Comment by Galaxy-Ding** [comment]
> **it failed at make:**
> 
> ` I llama.cpp build info: I UNAME_S: Linux I UNAME_P: x86_64 I UNAME_M: x86_64 I CFLAGS: -I. -O3 -std=c11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native I LDFLAGS: I CC: cc (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0 I CXX: g++ (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0
> 
> cc -I. -O3 -std=c11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -c ggml.c -o ggml.o /tmp/ccXgF03w.s: Assembler messages: /tmp/ccXgF03w.s:1987: error： no such instruction: `{vex} vpdpbusd %ymm2,%ymm5,%ymm0' /tmp/ccXgF03w.s:2050: error： no such instruction: `{vex} vpdpbusd %ymm2,%ymm6,%ymm0' /tmp/ccXgF03w.s:2105: error： no such instruction: `{vex} vpdpbusd %ymm2,%ymm5,%ymm0' /tmp/ccXgF03w.s:2180: error： no such instruction: `{vex} vpdpbusd %ymm0,%ymm11,%ymm1' /tmp/ccXgF03w.s:2248: error： no such instruction: `{vex} vpdpbusd %ymm1,%ymm10,%ymm0' Makefile:186: recipe for target 'ggml.o' failed make: *** [ggml.o] Error 1 `
> 
> **but successed at cmake:** ` [ 3%] Built target BUILD_INFO [ 6%] Building C object CMakeFiles/ggml.dir/ggml.c.o [ 6%] Built target ggml [ 9%] Building CXX object CMakeFiles/llama.dir/llama.cpp.o /home/xx/workspace/pycharm_projects/llama.cpp/llama.cpp: In function ‘size_t llama_set_state_data(llama_context*, const uint8_t*)’: /home/xx/workspace/pycharm_projects/llama.cpp/llama.cpp:2686:27: warning: cast from type ‘const uint8_t*’ {aka ‘const unsigned char*’} to type ‘void*’ casts away qualifiers [-Wcast-qual] 2686 | kin3d->data = (void _) inp; | ^~~~~~~~~~~~ /home/xx/workspace/pycharm_projects/llama.cpp/llama.cpp:2690:27: warning: cast from type ‘const uint8_t_’ {aka ‘const unsigned char*’} to type ‘void*’ casts away qualifiers [-Wcast-qual] 2690 | vin3d->data = (void _) inp; | ^~~~~~~~~~~~ [ 12%] Linking CXX static library libllama.a [ 12%] Built target llama [ 15%] Building CXX object tests/CMakeFiles/test-quantize-fns.dir/test-quantize-fns.cpp.o [ 18%] Linking CXX executable ../bin/test-quantize-fns [ 18%] Built target test-quantize-fns [ 21%] Building CXX object tests/CMakeFiles/test-quantize-perf.dir/test-quantize-perf.cpp.o [ 24%] Linking CXX executable ../bin/test-quantize-perf [ 24%] Built target test-quantize-perf [ 27%] Building CXX object tests/CMakeFiles/test-sampling.dir/test-sampling.cpp.o /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp: In function ‘void test_top_k(const std::vector&, const std::vector&, int)’: /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp:22:44: warning: unused parameter ‘expected_probs’ [-Wunused-parameter] 22 | const std::vector & expected_probs, | ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~ /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp: In function ‘void test_top_p(const std::vector&, const std::vector&, float)’: /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp:46:44: warning: unused parameter ‘expected_probs’ [-Wunused-parameter] 46 | const std::vector & expected_probs, | ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~ /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp: In function ‘void test_tfs(const std::vector&, const std::vector&, float)’: /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp:71:44: warning: unused parameter ‘expected_probs’ [-Wunused-parameter] 71 | const std::vector & expected_probs, | ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~ /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp: In function ‘void test_typical(const std::vector&, const std::vector&, float)’: /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp:94:44: warning: unused parameter ‘expected_probs’ [-Wunused-parameter] 94 | const std::vector & expected_probs, | ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~ /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp: In function ‘void test_repetition_penalty(const std::vector&, const std::vector&, const std::vector&, float)’: /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp:119:44: warning: unused parameter ‘expected_probs’ [-Wunused-parameter] 119 | const std::vector & expected_probs, | ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~ /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp: In function ‘void test_frequency_presence_penalty(const std::vector&, const std::vector&, const std::vector&, float, float)’: /home/xx/workspace/pycharm_projects/llama.cpp/tests/test-sampling.cpp:148:44: warning: unused parameter ‘expected_probs’ [-Wunused-parameter] 148 | const std::vector & expected_probs, | ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~ [ 30%] Linking CXX executable ../bin/test-sampling [ 30%] Built target test-sampling [ 33%] Building CXX object tests/CMakeFiles/test-tokenizer-0.dir/test-tokenizer-0.cpp.o [ 36%] Linking CXX executable ../bin/test-tokenizer-0 [ 36%] Built target test-tokenizer-0 [ 39%] Building CXX object examples/CMakeFiles/common.dir/common.cpp.o [ 39%] Built target common [ 42%] Building CXX object examples/main/CMakeFiles/main.dir/main.cpp.o [ 45%] Linking CXX executable ../../bin/main [ 45%] Built target main [ 48%] Building CXX object examples/quantize/CMakeFiles/quantize.dir/quantize.cpp.o [ 51%] Linking CXX executable ../../bin/quantize [ 51%] Built target quantize [ 54%] Building CXX object examples/quantize-stats/CMakeFiles/quantize-stats.dir/quantize-stats.cpp.o [ 57%] Linking CXX executable ../../bin/quantize-stats [ 57%] Built target quantize-stats [ 60%] Building CXX object examples/perplexity/CMakeFiles/perplexity.dir/perplexity.cpp.o [ 63%] Linking CXX executable ../../bin/perplexity [ 63%] Built target perplexity [ 66%] Building CXX object examples/embedding/CMakeFiles/embedding.dir/embedding.cpp.o [ 69%] Linking CXX executable ../../bin/embedding [ 69%] Built target embedding [ 72%] Building CXX object examples/save-load-state/CMakeFiles/save-load-state.dir/save-load-state.cpp.o [ 75%] Linking CXX executable ../../bin/save-load-state [ 75%] Built target save-load-state [ 78%] Building CXX object examples/benchmark/CMakeFiles/benchmark.dir/benchmark-matmult.cpp.o [ 81%] Linking CXX executable ../../bin/benchmark [ 81%] Built target benchmark [ 84%] Building CXX object examples/baby-llama/CMakeFiles/baby-llama.dir/baby-llama.cpp.o /home/xx/workspace/pycharm_projects/llama.cpp/examples/baby-llama/baby-llama.cpp: In function ‘int main(int, char_*)’: /home/xx/workspace/pycharm_projects/llama.cpp/examples/baby-llama/baby-llama.cpp:1593:32: warning: variable ‘opt_params_adam’ set but not used [-Wunused-but-set-variable] 1593 | struct ggml_opt_params opt_params_adam = ggml_opt_default_params(GGML_OPT_ADAM); | ^~~~~~~~~~~~~~~ [ 87%] Linking CXX executable ../../bin/baby-llama [ 87%] Built target baby-llama [ 90%] Building CXX object pocs/vdot/CMakeFiles/vdot.dir/vdot.cpp.o [ 93%] Linking CXX executable ../../bin/vdot [ 93%] Built target vdot [ 96%] Building CXX object pocs/vdot/CMakeFiles/q8dot.dir/q8dot.cpp.o [100%] Linking CXX executable ../../bin/q8dot [100%] Built target q8dot
> 
> `

After cmake succeeds, what's the next step?
