### ISSUE TITLE
[Feature Request] Get chat template from GGUF's tokenizer.chat_template key

### ISSUE THREAD

**Issue by akarshanbiswas** [abetlen/llama-cpp-python#1236]
I think it will be better than manually adding chat templates of newly released models. Also it will be awesome it it auto set's the correct chat template when an object of the llama class is created.

It just need to parse the value which is generally in the format (for example: this is gemma's chat_template saved in tokenizer.chat_template)
```
{{ bos_token }}{% if messages[0]['role'] == 'system' %}{{ raise_exception('System role not supported') }}{% endif %}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if (message['role'] == 'assistant') %}{% set role = 'model' %}{% else %}{% set role = message['role'] %}{% endif %}{{ '<start_of_turn>' + role + '
' + message['content'] | trim + '<end_of_turn>
' }}{% endfor %}{% if add_generation_prompt %}{{'<start_of_turn>model
'}}{% endif %}
```

llama.cpp server already supports this.

**Comment by abetlen** [comment]
@akarshanbiswas this is actually a feature here as well (may need better documentation) but if you don't specify a chat_format it will attempt to autodetect (frist from presets then from the gguf).

**Comment by akarshanbiswas** [comment]
@abetlen Interesting. I was not aware. The API docs says this :

- chat_format (Optional, default: None )  String specifying the chat format to use when calling create_chat_completion.

- chat_handler (Optional [LlamaChatCompletionHandler], default: None ) 

Optional chat handler to use when calling create_chat_completion.

I think it should be better to add this information to the docs.
