### ISSUE TITLE
Support for q5?

### ISSUE THREAD

**Issue by appvoid** [abetlen/llama-cpp-python#124]
WizardLM is the best 7B parameters model right now and is not possible to use it with this solution. Are you planning to update the shared libraries? Or is it a way to set my own Linux binary so I can use it for my project?

**Comment by abetlen** [comment]
Hi, I actually added the q5 support in main but haven't published to pypi, can you check if this works using the development instructions in the README

**Comment by Malrama** [comment]
> Hi, I actually added the q5 support in main but haven't published to pypi, can you check if this works using the development instructions in the README

Could you please push a version, and we would test it or at least give feedback? ^^' I am using oobabooga and I have no idea how I build that in there from scratch. However, I know how to use the pip updater :D Sorry, I don't want to sound silly. I would just love to try out q5 :3

**Comment by Malrama** [comment]
> @appvoid @Malrama pushed to PyPI with version 0.1.39, lmk if it works with the WizardLM model.

I updated and tested it with the Q5_1 WizardLM model by TheBloke and it works perfectly! Quite impressive tbh! Same size as Q4, but Q5 as just as fast. Thank you so much for keeping this updated. This is a huge serve to us. I will use Q5_1 a lot now :D

**Comment by abetlen** [comment]
Glad to hear it! I'll close this issue now.
