### ISSUE TITLE
BERT Support

### ISSUE THREAD

**Issue by fakerybakery** [abetlen/llama-cpp-python#1240]
Hi,
Thanks for releasing this library! Please add [BERT](https://github.com/ggerganov/llama.cpp/pull/5423) support, preferably for classification.
Thanks!

**Comment by abetlen** [comment]
Hi @fakerybakery this was added here as well at the time!

**Comment by fakerybakery** [comment]
Ah, thanks! Do you have an example on how I can use it for text classification? (Also, is RoBERTa supported?)
