### ISSUE TITLE
setting kvcache requirements using 4bit as the precision i.e. 1/8 precision

### ISSUE THREAD

**Issue by prashantkanuru** [abetlen/llama-cpp-python#1254]
hi @abetlen 
Can I set the KV Cache requirements with precision of 4 bits, now it is throwing it up default with 16bits.

Would really appreciate any help.

**Comment by abetlen** [comment]
Added in [0.2.58](https://github.com/abetlen/llama-cpp-python/blob/main/CHANGELOG.md#0258)
