### ISSUE TITLE
Tokens per Second Feature

### ISSUE THREAD

**Issue by lauraminkova** [abetlen/llama-cpp-python#1255]
Hi! I'm new to llama-cpp-python and have been reading the API docs recently. At the moment, I'm interested in the tokens per second speed of the LLM I'm testing on CPU. I know this exists in the original llama.cpp project and was wondering if it's possible to display this information with the current llama-cpp-python library? If not, this could be an interesting new feature?

Please let me know if what I'm saying is at all unclear! Any help would be appreciated :)

**Comment by abetlen** [comment]
This should be printed automatically when running with `verbose=True` as for accessing this information there's a low-level api function for it, not currently exposed but would be happy to take a look at any PRs to include this.

![image](https://github.com/abetlen/llama-cpp-python/assets/6826477/d5154f13-14da-467a-a7c4-8982f601c6ba)

**Comment by lauraminkova** [comment]
Thank you for the speedy reply! When using verbose=True and using either create_chat_completion or create_completion I get the following output:

```json
{
        "id": "",
        "object": "text_completion",
        "created":  X,
        "model": "",
        "choices": [
          {
            "text": "",
            "index": 0,
            "logprobs": null,
            "finish_reason": "length"
          }
        ],
        "usage": {
          "prompt_tokens": Y,
          "completion_tokens": Z,
          "total_tokens": ZZ
        }
      }
 }
```
Am I missing something ?

**Comment by lauraminkova** [comment]
Nvm! I got it :) Thank you for your help

**Comment by Muhammad4hmed** [comment]
> Nvm! I got it :) Thank you for your help

can you please share how you got it?

**Comment by lauraminkova** [comment]
> > Nvm! I got it :) Thank you for your help
> 
> can you please share how you got it?

Hi @Muhammad4hmed, sorry for the late reply! I was eventually able to see the tokens per second, but only when running llama-cpp-python on a Jupyter notebook, and of course using verbose=True. Hope this helps
