### ISSUE TITLE
Problem when using images

### ISSUE THREAD

**Issue by ParisNeo** [abetlen/llama-cpp-python#1265]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ ] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
When I send an image I expect it to work with no errors.
# Current Behavior
I get this error:
  File "xxx\Lib\site-packages\llama_cpp_cuda_tensorcores\llama_chat_format.py", line 1935, in __call__
    self._llava_cpp.llava_image_embed_make_with_bytes(
TypeError: this function takes at least 4 arguments (0 given)

# Environment and Context

I am using it with lollms as front end tool. lollms uses conda, python 3.11, cuda, pytorch etc. text generation works fine, but only when I use llava for images I get this error.

**Comment by abetlen** [comment]
Fixed in [0.2.52](https://github.com/abetlen/llama-cpp-python/blob/main/CHANGELOG.md#0252)
