### ISSUE TITLE
llama_sample_top_p_top_k is gone from llama.cpp, import fails

### ISSUE THREAD

**Issue by peter-ch** [abetlen/llama-cpp-python#127]
In [1]: import llama_cpp
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 import llama_cpp

File ~\Dropbox\Desktop\llama-cpp-python\_skbuild\win-amd64-3.9\cmake-install\lla
ma_cpp\__init__.py:1
----> 1 from .llama_cpp import *
      2 from .llama import *

File ~\Dropbox\Desktop\llama-cpp-python\_skbuild\win-amd64-3.9\cmake-install\lla
ma_cpp\llama_cpp.py:419
    405 def llama_sample_top_p_top_k(
    406     ctx: llama_context_p,
    407     last_n_tokens_data,  # type: Array[llama_token]
   (...)
    412     repeat_penalty: c_float,
    413 ) -> llama_token:
    414     return _lib.llama_sample_top_p_top_k(
    415         ctx, last_n_tokens_data, last_n_tokens_size, top_k, top_p, temp,
 repeat_penalty
    416     )
--> 419 _lib.llama_sample_top_p_top_k.argtypes = [
    420     llama_context_p,
    421     llama_token_p,
    422     c_int,
    423     c_int,
    424     c_float,
    425     c_float,
    426     c_float,
    427 ]
    428 _lib.llama_sample_top_p_top_k.restype = llama_token
    431 # Performance information

File C:\Python39\lib\ctypes\__init__.py:387, in CDLL.__getattr__(self, name)
    385 if name.startswith('__') and name.endswith('__'):
    386     raise AttributeError(name)
--> 387 func = self.__getitem__(name)
    388 setattr(self, name, func)
    389 return func

File C:\Python39\lib\ctypes\__init__.py:392, in CDLL.__getitem__(self, name_or_o
rdinal)
    391 def __getitem__(self, name_or_ordinal):
--> 392     func = self._FuncPtr((name_or_ordinal, self))
    393     if not isinstance(name_or_ordinal, int):
    394         func.__name__ = name_or_ordinal

AttributeError: function 'llama_sample_top_p_top_k' not found

**Comment by abetlen** [comment]
@peter-ch how did you install llama-cpp-python?

**Comment by peter-ch** [comment]
With "python setup.py build". It's probably not the correct way, but I don't see how I can build it with BLAS support otherwise.

**Comment by abetlen** [comment]
`LLAMA_OPENBLAS=1 pip install llama-cpp-python` should work.

The issue is that you likely cloned a newer version of the llama.cpp submodule which just recently removed that function.

**Comment by peter-ch** [comment]
Thanks, that worked.
