### ISSUE TITLE
Question: More than one EOS token in the Jinja chat formatter

### ISSUE THREAD

**Issue by JamesKunstle** [abetlen/llama-cpp-python#1278]
I'm using https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama_chat_format.py#L167 but we consider more than one EOS token. I'm mostly convinced that Jinja templates can only accept the one string literal as an EOS option, but I'm curious if there'd be another recommended option. Thanks!

**Comment by bruceunx** [comment]
I am curious about this, could you show some examples about `more than one EOS token`?

**Comment by JamesKunstle** [comment]
This is a non-issue, I think it can be closed, I was misinterpreting the use of the `eos_token` in the template vs. in the chat handler.
