### ISSUE TITLE
Clarify which version of llamacpp is being used

### ISSUE THREAD

**Issue by fiery-transition** [abetlen/llama-cpp-python#1283]
Hey, would be nice to know if the version of llamacpp being used is locked to the python package, and if it is, which version it is. Or at least clarify it. I saw that it said it builds llamacpp from source when installing, but which version? I'm a bit confused about that part 😅

It is not possible to config this package to use the latest build from llamacpp itself? So that the bindings and the library version could be decoupled? Only on a specific override of course, otherwise it would cause way too much headache. Things like supporting a new type of LLM would not really mean any outward API changes, and since llamacpp moves so fast, it could be nice to at least have the option to do so.

**Comment by abetlen** [comment]
Hey @fiery-transition late reply but I publish this in the [CHANGELOG](https://llama-cpp-python.readthedocs.io/en/latest/changelog/) whitch each release. It's not included in the package itself (open to a PR if anyone wants to do this) but you should be able to use `llama_cpp.__version__` to get that info.
