### ISSUE TITLE
Add pipeline selection in the customLLM script 

### ISSUE THREAD

**Issue by thomas101rcx** [abetlen/llama-cpp-python#129]
I am still relatively new to the LLM world. I am trying to build a Q/A chatbot based on Vicuna's 13B 4-bit quantized model.
Link below from huggingface
**eachadea/ggml-vicuna-13b-1.1**
`https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/tree/main`
 Using llama_index, llama-cpp-python and also langchain module. 

After following the example in the examples/high_level_api/langchain_custom_llm.py script, how do I add the ability to pipeline the LLM ?
In the llama_index documentation, there is a section where it mentions the ability to use a custom LLM Model with llama_index. 
`https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html
`
How do I incorporated this functionally  from llama_index to the following codeblock ?

`    pipeline = pipeline("text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype":torch.bfloat16})
`

```
class LlamaLLM(LLM):
    model_path: str
    llm: Llama

    @property
    def _llm_type(self) -> str:
        return "llama-cpp-python"

    def __init__(self, model_path: str, **kwargs: Any):
        model_path = model_path
        llm = Llama(model_path=model_path)
        super().__init__(model_path=model_path, llm=llm, **kwargs)

    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        response = self.llm(prompt, stop=stop or [])
        return response["choices"][0]["text"]

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"model_path": self.model_path}
```

**Comment by shengkaixuan** [comment]
any progress???
@abetlen   really hope you could help out,thanks!!

**Comment by abetlen** [comment]
@thomas101rcx @shengkaixuan I believe pipeline is specific to hugginface transformers which the Llama class is not. However if you just want to use this inside of llama index or through langchain it's officially supported [here](https://python.langchain.com/en/latest/ecosystem/llamacpp.html) you don't need a CustomLLM implementation.

Hope this helps

**Comment by ShinokuS** [comment]
@abetlen hi. I use llama-cpp-python in llama-index as follows:
```python
from langchain.llms import LlamaCpp
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from llama_index import SimpleDirectoryReader, GPTListIndex, PromptHelper, load_index_from_storage, StorageContext
from llama_index import LLMPredictor, ServiceContext

# define prompt helper
max_input_size = 2048
# set number of output tokens
num_output = 256
# set maximum chunk overlap
max_chunk_overlap = 20
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)

# Callbacks support token-wise streaming
callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
# Verbose is required to pass to the callback manager

# Make sure the model path is correct for your system!
llama = LlamaCpp(
    model_path="./ggml-model-q4_0.bin", 
    callback_manager=callback_manager, 
    verbose=False,
    max_tokens=256,
    n_ctx=1024,
    n_batch=256,
)

llm_predictor = LLMPredictor(llm=llama)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)

# Load the your data
documents = SimpleDirectoryReader('./docs').load_data()
index = GPTListIndex.from_documents(documents, service_context=service_context)
index.storage_context.persist(persist_dir="./index/")
# storage_context = StorageContext.from_defaults(persist_dir="./index/")
# index = load_index_from_storage(storage_context, service_context=service_context)

# Query and print response
query_engine = index.as_query_engine()
response = query_engine.query("<my_query>")
print(response)
```

But I have a problem with settings of llamacpp and llamaindex. I'm new to NLP, could you tell me which parameters are best configured for fast indexing of any files of any size and a quick response? Now the response is generated too slowly and ends with this: ```Llama.generate: prefix-match hit```
