### ISSUE TITLE
Adding a transformers library version to the pyproject.toml

### ISSUE THREAD

**Issue by ysiaj33802** [abetlen/llama-cpp-python#1294]
I was installing the project using pip to use Functionary V2.2 for function calling; however, I noticed that the hugging face transformers library is not included as a dependency to be downloaded even though transformers is being used for the tokenizer. I'm not sure sure if this can be remedied. A minor thing, but it can sometimes still be a little annoying at times.

**Comment by abetlen** [comment]
@ysiaj33802 I appreciate the suggesting but adding transformers as a dependency is going to really slow down installs for folks not using the library. If there's somewhere in the docs that you think we should include it I'm happy to accept a PR. Cheers.
