### ISSUE TITLE
cache-type-k and cache-type-p parameters support

### ISSUE THREAD

**Issue by riverzhou** [abetlen/llama-cpp-python#1305]
Origin llama.cpp is support cache-type-k and cache-type-p setting, but llama-cpp-python server is not.

**Comment by Limour-dev** [comment]
[Setting quantization below f16](https://github.com/Limour-dev/llama-python-streamingllm/blob/main/llama_cpp_python_streamingllm.py#L383) will result in an error: GGML_ASSERT: llama.cpp\ggml.c:7553: false

**Comment by abetlen** [comment]
@riverzhou thanks to @Limour-dev this should be in the latest v0.2.58 release by setting `llama_cpp.Llama(..., type_k=llama_cpp.GGML_TYPE_I8)`
