### ISSUE TITLE
Directions to compile to use GPU? 

### ISSUE THREAD

**Issue by Free-Radical** [abetlen/llama-cpp-python#131]
Can someone please point me to where the directions are?

I'm on Ubuntu 23.04

**Comment by gjmulder** [comment]
@Free-Radical check out my my issue #113 . If you can follow what I did and get it working, please tell me. If not, let's try and debug together?

**Comment by Free-Radical** [comment]
> @Free-Radical check out my my issue #113 . If you can follow what I did and get it working, please tell me. If not, let's try and debug together?

Ok thx, checking it out, will report later today when I have feedback. 

PS I wonder if it is better to compile the original llama.cpp for GPU/BLAS and then transfer the compiled files to this project?
I mention that because I believe due to the more love spread use of the llama.cpp repo there are supposed to be more "solid" directions available in that repo

**Comment by gjmulder** [comment]
@Free-Radical I can't actually get `llama.cpp` to compile against CUDA 12.1 using [ggerganov/llama.cpp](https://github.com/ggerganov/llama.cpp) as I get a cmake error `Failed to detect a default CUDA architecture.`

However, the following works just fine:

`llama-cpp-python/vendor/llama.cpp$ LLAMA_CUBLAS=1 make`

:man_shrugging:

**Comment by LiliumSancta** [comment]
> @Free-Radical I can't actually get `llama.cpp` to compile against CUDA 12.1 using [ggerganov/llama.cpp](https://github.com/ggerganov/llama.cpp) as I get a cmake error `Failed to detect a default CUDA architecture.`
> 
> However, the following works just fine:
> 
> `llama-cpp-python/vendor/llama.cpp$ LLAMA_CUBLAS=1 make`
> 
> 🤷‍♂️

The version of llama.cpp used in llama-cpp-python is not the latest version in the llama.cpp repository. You can see this by comparing the files inside vendor. Yesterday I had a bit of work to create a version of the library with the changes to run q5_0 and q5_1 with CLBlast support inside llama-cpp-python.

**Comment by gjmulder** [comment]
Attached is a [Dockerfile](https://github.com/abetlen/llama-cpp-python/files/11367635/Dockerfile.txt) that builds with the latest `git clone` of `llama-cpp-python` and confirms that `n_batch == 512`.

```
$ nvidia-smi
Mon May  1 19:43:48 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080 Ti      On | 00000000:09:00.0 Off |                  N/A |
| 25%   35C    P8               11W / 250W|    244MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    211467      C   python3                                     224MiB |
+---------------------------------------------------------------------------------------+

```

```
# Haiku:
Old computer, why do you taunt me?
Broken parts, dead as dirt.
```

**Comment by shengkaixuan** [comment]
> 
i used a 13b model with cublast, used a https://github.com/oobabooga/text-generation-webui as ui
the result is 2.44 tokens/s,  Is this result good in a gpu ????

`llama.cpp: loading model from models/ggml-vicuna-13b-1.1-q5_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 8 (mostly Q5_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 10583.25 MB (+ 1608.00 MB per state)
llama_init_from_file: kv self size  = 1600.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
Output generated in 81.98 seconds (2.44 tokens/s, 200 tokens, context 22, seed 1279011280)`

**Comment by gjmulder** [comment]
@shengkaixuan 

> Is this result good in a gpu ????

I am getting around 16 tokens a second with `llama.cpp` `./perplexity` w/my old `1080Ti`, and 16 old AMD cores with the `65B` model:

```
llama_print_timings:        load time = 33113.94 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time = 2361695.35 ms / 36864 tokens (   64.07 ms per token)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings:       total time = 2368454.17 ms

```

**Comment by abetlen** [comment]
@gjmulder that's remarkably fast for the 65b model, do you get the same speed for the `./main` example?

@shengkaixuan I get around 85ms per token for the 7b models and around 145ms per token for 13b models, my results are consistent between llama.cpp and the python bindings.

**Comment by gjmulder** [comment]
[make LLAMA_CUBLAS=1 && ./perplexity generates GPU load, while ./main does not](https://github.com/ggerganov/llama.cpp/issues/1283)

"BLAS calls are only called when the tensors meet certain dimensions. In your case, you need to pass a prompt with length of 32 or more tokens to main to make it use BLAS. After it processes the prompt, it will continue text generation without BLAS since the overhead in this case is too big and there is no benefit"

**Comment by shengkaixuan** [comment]
@gjmulder   

> Attached is a [Dockerfile](https://github.com/abetlen/llama-cpp-python/files/11367635/Dockerfile.txt) that builds with the latest `git clone` of `llama-cpp-python` and confirms that `n_batch == 512`.
> 
> ```
> $ nvidia-smi
> Mon May  1 19:43:48 2023       
> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
> |-----------------------------------------+----------------------+----------------------+
> | GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                                         |                      |               MIG M. |
> |=========================================+======================+======================|
> |   0  NVIDIA GeForce GTX 1080 Ti      On | 00000000:09:00.0 Off |                  N/A |
> | 25%   35C    P8               11W / 250W|    244MiB / 11264MiB |      0%      Default |
> |                                         |                      |                  N/A |
>                                                                                          
> +---------------------------------------------------------------------------------------+
> | Processes:                                                                            |
> |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
> |        ID   ID                                                             Usage      |
> |=======================================================================================|
> |    0   N/A  N/A    211467      C   python3                                     224MiB |
> +---------------------------------------------------------------------------------------+
> ```
> 
> ```
> # Haiku:
> Old computer, why do you taunt me?
> Broken parts, dead as dirt.
> ```

@gjmulder  how is the performance improvement when you  run llama-cpp-python in the docker container?

**Comment by gjmulder** [comment]
> how is the performance improvement when you run llama-cpp-python in the docker container?

@shengkaixuan minimal for short prompts.

**Comment by gabrielcustodio** [comment]
How params to use in ./main with gpu?

**Comment by ZacharyDK** [comment]
Any idea where to start with Docker, AMD, mac os?

AMD Radeon Pro 5600M 8 GB

2.3 GHz 8-Core Intel Core i9

16 GB 2667 MHz DDR4

Mac OS Ventura 13.3.1

Heck, I'm not totally sure how to create a docker image starting from @gjmulder Dockerfile in the thread. Even then, not totally sure how to use it after build docker. And load the model, read write from files on regular OS. etc. Any ideas for when to get started with docker..and if its even possible to use it to run a model with gpu support on mac os?
