### ISSUE TITLE
shared library llama not found 0.1.39

### ISSUE THREAD

**Issue by matthoffner** [abetlen/llama-cpp-python#132]
I can't no longer get this project to work after upgrading from 0.1.38 to 0.1.39. I think its because I'm using the Langchain wrapper:

```
from langchain.llms import LlamaCpp
```

```
FileNotFoundError: Shared library with base name 'llama' not found
```

**Comment by jmtatsch** [comment]
Same here

**Comment by abetlen** [comment]
@matthoffner I don't think anything in the api has changed, can you try with v0.1.41? Are there any errors when you try to install with pip?

**Comment by matthoffner** [comment]
Will try the latest @abetlen - I think this is specific to how llama.cpp is installed on my computer and not Langchain.Not sure where `llama` is supposed to be installed, or if its something Mac specific.

**Comment by jmtatsch** [comment]
Actually it works well for me again with the current versions. 
Turned out i had an issue with accidentally importing a local copy of the code instead of the installed package.

**Comment by abetlen** [comment]
> Will try the latest @abetlen - I think this is specific to how llama.cpp is installed on my computer and not Langchain.Not sure where `llama` is supposed to be installed, or if its something Mac specific.

llama.cpp should be compiled and installed inside the llama-cpp-python package, the pypi package is a source distribution which includes llama.cpp and tries to build via cmake / make. Let me know if you figure out what's causing the issue.

**Comment by matthoffner** [comment]
Fixed with latest, thanks

**Comment by rok-GKC** [comment]
Installed 0.1.48 and get "FileNotFoundError: Shared library with base name 'llama' not found"

The folder ./vendor/llama.cpp/ is empty

Any ideas?

**Comment by abetlen** [comment]
@rok-GKC are you installing from PyPI or Github?

**Comment by abetlen** [comment]
And otherwise no errrors during the pip installation?

**Comment by rok-GKC** [comment]
No errors.

**Comment by rok-GKC** [comment]
I tired again today with 0.1.49 and it worked.
