### ISSUE TITLE
Update low-level examples to use new sampling API

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#141]
llama.cpp recently changed the sampling API to make sampling more configurable. Unfortunately this broke many of the low-level examples so we should update these.

**Comment by mikeggh** [comment]
I'd like to know an example for using:
llama_load_session_file(ctx, session_file, embd, out_len, (llama_cpp.c_int * out_len)(*embd_inp_out))

and save of course... if you get a chance :> i'll try to brute force it later though..

**Comment by SagsMug** [comment]
Im gonna work on updating the chat example, it might take a moment given the number of changes 😉

**Comment by abetlen** [comment]
Thanks @SagsMug yeah I was a little overwhelmed with the new sampling API but overall it seems like the right direction to have more control over sampling. Check out https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama.py#L255 might help
