### ISSUE TITLE
Could not build wheels for llama-cpp-python , python 3.9, aws linux

### ISSUE THREAD

**Issue by navinshahse** [abetlen/llama-cpp-python#142]
Configuring Project
        Working directory:
          /tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6/_skbuild/linux-x86_64-3.9/cmake-build
        Command:
          /tmp/pip-build-env-0_wbu4ds/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake /tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6 -G Ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.15 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-0_wbu4ds/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/ec2-user/anaconda3/envs/pytorch_p39/bin/python3.9 -DPYTHON_INCLUDE_DIR:PATH=/home/ec2-user/anaconda3/envs/pytorch_p39/include/python3.9 -DPYTHON_LIBRARY:PATH=/home/ec2-user/anaconda3/envs/pytorch_p39/lib/libpython3.9.so -DPython_EXECUTABLE:PATH=/home/ec2-user/anaconda3/envs/pytorch_p39/bin/python3.9 -DPython_ROOT_DIR:PATH=/home/ec2-user/anaconda3/envs/pytorch_p39 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/ec2-user/anaconda3/envs/pytorch_p39/include/python3.9 -DPython3_EXECUTABLE:PATH=/home/ec2-user/anaconda3/envs/pytorch_p39/bin/python3.9 -DPython3_ROOT_DIR:PATH=/home/ec2-user/anaconda3/envs/pytorch_p39 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/ec2-user/anaconda3/envs/pytorch_p39/include/python3.9 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-0_wbu4ds/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 7.3.1
      -- The CXX compiler identification is GNU 7.3.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Warning (dev) in CMakeLists.txt:
        A logical block opening on the line

          /tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6/CMakeLists.txt:9 (if)

        closes on the line

          /tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6/CMakeLists.txt:31 (endif)

        with mis-matching arguments.
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Configuring done (0.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6/_skbuild/linux-x86_64-3.9/cmake-build
      [1/2] Generating /tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6/vendor/llama.cpp/libllama.so
      FAILED: /tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6/vendor/llama.cpp/libllama.so
      cd /tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6/vendor/llama.cpp && make libllama.so
      I llama.cpp build info:
      I UNAME_S:  Linux
      I UNAME_P:  x86_64
      I UNAME_M:  x86_64
      I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native
      I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native
      I LDFLAGS:
      I CC:       cc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)
      I CXX:      g++ (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)

      g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -c llama.cpp -o llama.o
      cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native   -c ggml.c -o ggml.o
      ggml.c: In function ‘ggml_vec_dot_q4_2_q8_0’:
      ggml.c:3069:40: warning: implicit declaration of function ‘_mm256_set_m128’; did you mean ‘_mm256_set_epi8’? [-Wimplicit-function-declaration]
               const __m256 d = _mm256_mul_ps(_mm256_set_m128(d1, d0), _mm256_broadcast_ss(&y[i].d));
                                              ^~~~~~~~~~~~~~~
                                              _mm256_set_epi8
      ggml.c:3069:40: error: incompatible type for argument 1 of ‘_mm256_mul_ps’
      In file included from /usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h:41:0,
                       from ggml.c:183:
      /usr/lib/gcc/x86_64-redhat-linux/7/include/avxintrin.h:317:1: note: expected ‘__m256 {aka __vector(8) float}’ but argument is of type ‘int’
       _mm256_mul_ps (__m256 __A, __m256 __B)
       ^~~~~~~~~~~~~
      ggml.c:3073:22: warning: implicit declaration of function ‘_mm256_set_m128i’; did you mean ‘_mm256_set_epi8’? [-Wimplicit-function-declaration]
               __m256i bx = _mm256_set_m128i(bx1, bx0);
                            ^~~~~~~~~~~~~~~~
                            _mm256_set_epi8
      ggml.c:3073:22: error: incompatible types when initializing type ‘__m256i {aka __vector(4) long long int}’ using type ‘int’
      make: *** [ggml.o] Error 1
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-0_wbu4ds/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-0_wbu4ds/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 696, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-0_wbu4ds/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 741, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-0_wbu4ds/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6
        Working directory:
          /tmp/pip-install-o3fr_ynt/llama-cpp-python_237ceb0be00c417795f75e9b9aa4e7b6/_skbuild/linux-x86_64-3.9/cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by abetlen** [comment]
Can you try compiling llama.cpp standalone?

**Comment by navinshahse** [comment]
sh-4.2$ make
I llama.cpp build info:
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native
I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native
I LDFLAGS:
I CC:       cc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)
I CXX:      g++ (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)

cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native   -c ggml.c -o ggml.o
ggml.c: In function ‘ggml_vec_dot_q4_2_q8_0’:
ggml.c:3069:40: warning: implicit declaration of function ‘_mm256_set_m128’; did you mean ‘_mm256_set_epi8’? [-Wimplicit-function-declaration]
         const __m256 d = _mm256_mul_ps(_mm256_set_m128(d1, d0), _mm256_broadcast_ss(&y[i].d));
                                        ^~~~~~~~~~~~~~~
                                        _mm256_set_epi8
ggml.c:3069:40: error: incompatible type for argument 1 of ‘_mm256_mul_ps’
In file included from /usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h:41:0,
                 from ggml.c:183:
/usr/lib/gcc/x86_64-redhat-linux/7/include/avxintrin.h:317:1: note: expected ‘__m256 {aka __vector(8) float}’ but argument is of type ‘int’
 _mm256_mul_ps (__m256 __A, __m256 __B)
 ^~~~~~~~~~~~~
ggml.c:3073:22: warning: implicit declaration of function ‘_mm256_set_m128i’; did you mean ‘_mm256_set_epi8’? [-Wimplicit-function-declaration]
         __m256i bx = _mm256_set_m128i(bx1, bx0);
                      ^~~~~~~~~~~~~~~~
                      _mm256_set_epi8
ggml.c:3073:22: error: incompatible types when initializing type ‘__m256i {aka __vector(4) long long int}’ using type ‘int’
make: *** [ggml.o] Error 1

**Comment by abetlen** [comment]
@navinshahse you should submit an issue at https://github.com/ggerganov/llama.cpp once it's fixed there I'll be able to merge it in.

**Comment by bizism** [comment]
Try install GCC compiler version 11.0, and install newest version of cmake. It helped me.

**Comment by shadowfaxproject** [comment]
> Try install GCC compiler version 11.0, and install newest version of cmake. It helped me.

Thanks that worked for me on aws-inf2 centos.
