### ISSUE TITLE
How to build the llamacpp's .so file separately and then pass it in the llama_cpp_python.

### ISSUE THREAD

**Issue by fastdaima** [abetlen/llama-cpp-python#1435]
When I tried to install the library with gpu support. I am facing some issue due to cuda . 

But building llamacpp project with cuda support works fine. 

Is there a way to build .so objects separately ? If so, then I can directly place it in the python_env_name/lib/python3.10/site-packages/llama_cpp/  to make it work right ?

**Comment by iamlemec** [comment]
Not sure if this is exactly what you're looking for, but you can build directly with `cmake` using something like:
```
cmake -DLLAMA_CUDA=ON -DLLAVA_BUILD=OFF -B build .
cmake --build build --config Release
```
Disabling LlaVa is not mandatory, but it was giving me an error otherwise.

Then if you copy it over, there's a good chance it'll work, but I haven't actually tried. Another option is to set the `LLAMA_CPP_LIB` environent variable to the full path for the `.so` file and it'll pick it up on import.

**Comment by fastdaima** [comment]
@iamlemec , thanks for the reply 

But I tried for cpu version

`cmake -B build 
cmake --build build --config Release`

It creates .a files not .so files, 

How to use that directly in llama_cpp_python library 

PFA for reference: 

![image](https://github.com/abetlen/llama-cpp-python/assets/25530496/cfba2e57-44fd-4729-acb7-92221bf783fb)

**Comment by iamlemec** [comment]
Hmm, that's odd. Running the same thing, I'm getting the file showing up at `build/vendor/llama.cpp/libllama.so`. Are you sure your repo is fully up to date and unmodified? Could also try removing `build` an starting fresh.

**Comment by abetlen** [comment]
@fastdaima you'll also need to add the `-DBUILD_SHARED_LIBS` option to the cmake command.

**Comment by fastdaima** [comment]
Hi @abetlen , when I tried that, I am getting error on pthread library

![image](https://github.com/abetlen/llama-cpp-python/assets/25530496/52781264-14ce-4c6d-bfe3-c86e0d488fec)

**Comment by fastdaima** [comment]
Thanks @abetlen  & @iamlemec ,

I was able to resolve this issue, by adding -pthread cmake flag to CMakeLists.txt
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1c3b5c8e..9b1074de 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -154,7 +154,7 @@ set(CMAKE_CXX_STANDARD_REQUIRED true)
 set(CMAKE_C_STANDARD 11)
 set(CMAKE_C_STANDARD_REQUIRED true)
 set(THREADS_PREFER_PTHREAD_FLAG ON)
-
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pthread")
 find_package(Threads REQUIRED)
 include(CheckCXXCompilerFlag)

```
then ran these commands, to build the .so files, then copied libllama.so and libggml_shared.so to  env/lib/python_version/site-packages/llama_cpp 

```
cmake -DLLAMA_STATIC=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_FLAGS=-fPIC -DCMAKE_C_FLAGS=-fPIC -DLLAMA_CCACHE=OFF -B build .
cmake --build build --config Release

```
After this , I was able to load the model in llama_cpp_python and use it.

**Comment by ayush20501** [comment]
@iamlemec Can you please provide detailed steps of how you were able to generate .so file for llama-cpp-python. thanks
