### ISSUE TITLE
Segfault on load for embedding models lacking BOS/EOS token (such as `BAAI/bge-*`)

### ISSUE THREAD

**Issue by iamlemec** [abetlen/llama-cpp-python#1463]
For embedding models that lack BOS/EOS tokens (such as `BAAI/bge-*`), the BOS/EOS token ids default to `-1`, which causes a segfault on loading when calling `token_get_text`. I would recommend either short-circuiting these calls to the empty string in that case or skipping the chat template code entirely for embedding models.

**Comment by abetlen** [comment]
@iamlemec thanks for catching this, should be fixed now by checking for the `-1` and using the empty string in that case.
