### ISSUE TITLE
Fix README: `Llama3VisionAlpha` not `Llama3VisionAlphaChatHandler`

### ISSUE THREAD

**Issue by mdnestor** [abetlen/llama-cpp-python#1488]
Under "Multi-modal Models", [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md?plain=1#L511) says to use `Llama3VisionAlphaChatHandler`. However in [llama_cpp/llama_chat_format.py](https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama_chat_format.py#L3101) we see the correct name is `Llama3VisionAlpha`.

**Comment by abetlen** [comment]
@mdnestor thanks for catching that, though it's technically a breaking change I may rename the chat handler and add an alias to it if someone runs into an issue.
