### ISSUE TITLE
cuBLAS and mirostat support?

### ISSUE THREAD

**Issue by paryska99** [abetlen/llama-cpp-python#152]
The ci_cublas branch of the llamacpp now supports cuBLAS (tested it on a 3060 with batch size of 512 and it performed significantly faster at reading the prompt than master). 
Is it possible that we can get this functionality as well as mirostat so third party projects such as Oobabooga's textgen can use it?

If not, then how can one compile a cuBLAS version of llama-cpp-python and replace it in the textgen-webui?
OS: Windows

**Comment by abetlen** [comment]
Currently tracking mirostat here -> #147 I'll take another look at the docker option, the only issue I ran into is building the image inside of a github actions runner.

**Comment by Dampfinchen** [comment]
Yes, seconded. cuBLAS makes llama.cpp so much faster and more useable. I hope Oobabooga will support it in the future. CLBlast is nice for AMD GPUs as well.
