### ISSUE TITLE
Updating llama-cpp to  add support for BitnetForCausalLM

### ISSUE THREAD

**Issue by bhugueney** [abetlen/llama-cpp-python#1553]
Thank you for this project !
Llama-cpp just landed  [support for BitnetForCausalLM](https://github.com/ggerganov/llama.cpp/commit/e112b610a1a75cb7fa8351e1a933e2e7a755a5ce) which could be a game changer for some use cases.
I know that the llama-cpp version has been recently updated, but If that is not to much of a burden, a new update to get BitnetForCausalLM with the python binding would be greatly appreciated.

Best Regards.

**Comment by abetlen** [comment]
@bhugueney should be available in v0.2.80
