### ISSUE TITLE
New Gemma 2 GGUF works okay, but crashes w llama_cpp.server (NULL pointer access)

### ISSUE THREAD

**Issue by fat-tire** [abetlen/llama-cpp-python#1562]
Running the latest llama-cpp-python code, built from the master/main branch.  Trying out[ the gguf of the gemma 2 models...](https://old.reddit.com/r/LocalLLaMA/comments/1dpv9nq/gemma_2_9b_ggufs_are_up/) from locallama.

Per the README, regular inference works like this:
```python
messages = [{"role": "system", "content": "What's 2+2?"},  # no system prompts for gemma, but it's okay
            {"role": "user", "content": "How are you today?"}]  

llm = Llama.from_pretrained(
    repo_id="bartowski/gemma-2-9b-it-GGUF"
    filename="*Q6_K.gguf",
    verbose=False,
    chat_format="gemma",
)

x = llm.create_chat_completion(
    messages=messages,
)

print(x["choices"][0]["message"]["content"])
```

That works fine and you get a response on the second non-system prompt.

But if you run the webserver manually:

```bash
python3 -m llama_cpp.server --hf_model_repo_id bartowski/gemma-2-9b-it-GGUF --model gemma-2-9b-it-Q6_K.gguf  --host localhost --port 8000 --chat_format gemma 
```

and then connect like:

```bash
curl -s http://localhost:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
   "messages": [
      {"role": "user", "content": "How are you today?"}}
   ]
 }'
```
...you get a crash:
```
...
 File "/home/xxx/gitclone/llama-cpp-python/llama_cpp/llama_chat_format.py", line 606, in chat_completion_handler
    completion_or_chunks = llama.create_completion(
  File "/home/xxx/gitclone/llama-cpp-python/llama_cpp/llama.py", line 1607, in create_completion
    completion: Completion = next(completion_or_chunks)  # type: ignore
  File "/home/xxx/gitclone/llama-cpp-python/llama_cpp/llama.py", line 1132, in _create_completion
    for token in self.generate(
  File "/home/xxx/gitclone/llama-cpp-python/llama_cpp/llama.py", line 740, in generate
    self.eval(tokens)
  File "/home/xxx/gitclone/llama-cpp-python/llama_cpp/llama.py", line 585, in eval
    logits = np.ctypeslib.as_array(self._ctx.get_logits(), shape=(rows * cols, ))
  File "/home/xxx/.local/lib/python3.10/site-packages/numpy/ctypeslib.py", line 522, in as_array
    obj = ctypes.cast(obj, p_arr_type).contents
ValueError: NULL pointer access
```
Then this results in a 500 Internal Server error:
```
"POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
{"error":{"message":"NULL pointer access","type":"internal_server_error","param":null,"code":null}}%                                       
```
Same crash if you try to access the server in other ways. Something's wrong here I think.

Tried various versions of numpy from 1.26.xx to 2.0.0 didn't matter.

**Comment by werruww** [comment]
are it work with the code?


from llama_cpp import Llama
messages = [{"role": "system", "content": "What's 2+2?"},  # no system prompts for gemma, but it's okay
            {"role": "user", "content": "How are you today?"}]  

llm = Llama.from_pretrained(
    repo_id="bartowski/gemma-2-9b-it-GGUF"
    filename="*Q6_K.gguf",
    verbose=False,
    chat_format="gemma",
)

x = llm.create_chat_completion(
    messages=messages,
)

print(x["choices"][0]["message"]["content"])

**Comment by werruww** [comment]
>>> from llama_cpp import Llama
>>>
>>>
>>> messages = [{"role": "system", "content": "What's 2+2?"},  # no system prompts for gemma, but it's okay
...             {"role": "user", "content": "How are you today?"}]
>>>
>>> llm = Llama.from_pretrained(
...     repo_id="legraphista/gemma-2-9b-it-IMat-GGUF",
...     filename="gemma-2-9b-it.IQ1_M.gguf",
...     verbose=False,
...     chat_format="gemma",
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\m\Desktop\ollama\llama-cpp-python\llama_cpp\llama.py", line 2091, in from_pretrained
    return cls(
           ^^^^
  File "C:\Users\m\Desktop\ollama\llama-cpp-python\llama_cpp\llama.py", line 358, in __init__
    self._model = self._stack.enter_context(contextlib.closing(_LlamaModel(
                                                               ^^^^^^^^^^^^
  File "C:\Users\m\Desktop\ollama\llama-cpp-python\llama_cpp\_internals.py", line 54, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: C:\Users\m\.cache\huggingface\hub\models--legraphista--gemma-2-9b-it-IMat-GGUF\snapshots\410d64a19518c6cd0d312b2e084943175745d2c6\.\gemma-2-9b-it.IQ1_M.gguf
>>>
>>> x = llm.create_chat_completion(
...     messages=messages,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'llm' is not defined
>>>
>>> print(x["choices"][0]["message"]["content"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined

**Comment by fat-tire** [comment]
Sorry I could have been more complete (and left out a comma) if it helps.  Here's the full code from the file and its output:

```python
% cat quicktest.py 
#!/usr/bin/python3

from llama_cpp import Llama

messages = [{"role": "system", "content": "What's 2+2?"},  # no system prompts for gemma, but it's okay
            {"role": "user", "content": "How are you today?"}]  

llm = Llama.from_pretrained(
    repo_id="bartowski/gemma-2-9b-it-GGUF",
    filename="*Q6_K.gguf",
    verbose=False,
    chat_format="gemma",
)

x = llm.create_chat_completion(
    messages=messages,
)

print(x["choices"][0]["message"]["content"])

```
Output when run:

```
% python3 quicktest.py
As an AI, I don't have feelings or experiences like humans do. So I don't have "days" or emotions like "good" or "bad".

But I'm here and ready to assist you with any questions or tasks you may have! How can I help you today?
```

Changed 2nd prompt to: `"What kind of LLM are you?"`

Output when run:

```
% python3 quicktest.py
I am Gemma, an open-weights large language model. This means my weights are publicly available. I was created by the Gemma team at Google DeepMind.
```

BTW I left the system prompt in to show that so long as you use `chat_format="gemma"`, it will not give you a "System mode not supported" Exception (though it will ignore this prompt).

**Comment by mindwellsolutions** [comment]
@fat-tire Hi, thank you so much for sharing how you got Gemma working. What version / type of Llama Cpp are you using. The original C++ Llama.cpp or the llama-cpp-python build?

With your exact script I still get these errors, even though I defined :

llama_model_load: error loading model: error loading model architecture: unknown model architecture: 'gemma2'
llama_load_model_from_file: failed to load model
ValueError: Failed to load model from file: gemma-2-9b-it-Q6_K.gguf

**Comment by fat-tire** [comment]
Q: Did you build llama-cpp-python from source or are you using the pre-baked release?

**Comment by fat-tire** [comment]
So I've just built the latest changes from today and now everything works with gemma even with the server! :)  I'm going to close this but @mindwellsolutions please continue the discussion if you like...
