### ISSUE TITLE
So how do I build now?

### ISSUE THREAD

**Issue by Ph0rk0z** [abetlen/llama-cpp-python#1572]
I don't use wheels and llama.cpp has broken setting compile variables from cmakelists. I have a whole litany of compile time options including AVX512, size for peer cache, etc. Is the only option to make a long compile string like a chump? ccmake can work for the main repo but that's not how it builds here.

**Comment by abetlen** [comment]
@Ph0rk0z let me look into it, are you on Linux? We might just be able to manually set `-march=native` or similar in our cmakelist to enable those.

**Comment by Ph0rk0z** [comment]
figured out those have to be passed in the command prompt now :(
