### ISSUE TITLE
The installation described in README.md does not enable hipBLAS.

### ISSUE THREAD

**Issue by kfule** [abetlen/llama-cpp-python#1579]
After https://github.com/ggerganov/llama.cpp/commit/f3f65429c44bb195a9195bfdc19a30a79709db7b, the environment variable "LLAMA_HIPBLAS" is no longer valid. Therefore, even if you install as instructed in README.md, hipBLAS is not enabled.

"GGML_HIPBLAS" should be used instead of "LLAMA_HIPBLAS" as described below.

```bash
CMAKE_ARGS="-DGGML_HIPBLAS=on" pip install llama-cpp-python
```

**Comment by abetlen** [comment]
@kfule thank you for point this out, just updated the docs.
