### ISSUE TITLE
Implement Llama longest prefix cache

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#158]
Opening this up to track the development of the new caching behaviour I'm planning to implement. This will leverage 2 significant improvements

- Reduced llama state size which is now a function of evaluated tokens
- Improved efficiency of Llama.generate which now only eval's prompt tokens that are not already in the context window

**Comment by abetlen** [comment]
This looks like it's good to go now, the cache is in-memory currently so you'll need to set `CACHE_SIZE` or `--cache-size` in bytes to the maximum cache size for your available RAM. If anyone wants to test this out let me know if it works as expected, I'll probably push this release later tonight.

**Comment by eiery** [comment]
Tried this out in oobabooga and it's a game-changer for chats with frequent editing. Before this the model had to spend a lot of time reingesting the entire prompt even on a small edit.

**Comment by abetlen** [comment]
@eiery glad to hear! I should point out though that text-generation-webui is just using the new `generate` rewind behaviour and not the full state cache. Basically "rewind" is useful for a single long conversation or generating multiple responses for a single prompt, the full state cache let's you restore completely differrent conversations.

**Comment by ibehnam** [comment]
@abetlen I'm curious about using this feature in the Python API. I tried this approach but re-running the same `llm` always returns "... remaining 1 prompt tokens to eval" even though it should not eval anything because the prompt hasn't changed. 🤔

```
from llama_cpp import Llama, LlamaDiskCache

cache = LlamaDiskCache(cache_dir=".../.cache")


model_path_2 = "...Phi-3-mini-4k-instruct-q4.gguf"
llm = Llama(
    model_path=model_path_2,
    n_gpu_layers=-1,
    flash_attn=True,
    n_threads=10,
    use_mlock=False,
    seed=42,
    verbose=True,
)
llm.reset()
llm.set_cache(cache)

# %%

prompt = "#User:\nFrom now on, your name is Ben.\n#Assistant:\n"

r = llm(
    prompt=prompt,
    max_tokens=12,
    temperature=0.0,
    stop=[
        "\n\n",
        "#User:",
        "#Assistant:",
    ],
)

print(r["choices"][0]["text"])
```
