### ISSUE TITLE
Support for GLM in llama-cpp-python

### ISSUE THREAD

**Issue by logan0116** [abetlen/llama-cpp-python#1582]
I noticed that llama-cpp has recently added support for chatglm3 and glm4, as detailed in [this pull request](https://github.com/ggerganov/llama.cpp/pull/8031).

I hope that llama-cpp-python can also provide support for these models.

Thank you for your continued hard work.

**Comment by abetlen** [comment]
@logan0116 should be available in the latest release (v0.2.82)
