### ISSUE TITLE
Embedding response not OpenAI-compatible

### ISSUE THREAD

**Issue by jamesfalkner** [abetlen/llama-cpp-python#1588]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I expect the return value from `/v1/embeddings` to correspond to the format [documented](https://platform.openai.com/docs/guides/embeddings/what-are-embeddings) in OpenAI. 

# Current Behavior

The return value is similar, but the actual `embedding` element has an array-of-arrays. For example, when I invoke using this command:

```bash
curl -H 'Accept: application/json' -H 'Authorization: Bearer dummy' -H 'Content-Type: application/json' -d '{"model": "nomic-embed-text", "input": "hello world"}' http://localhost:8000/v1/embeddings`
```

The returned value begins with:

```json
{"object":"list","data":[{"object":"embedding","embedding":[[10.64968204498291,2.7278764247894287,
```

Notice the `[[` (array of arrays). In OpenAI, it does not have this. It's just an array for the `embedding` element:

```json
{
  "object": "list",
  "data": [
    {
      "object": "embedding",
      "index": 0,
      "embedding": [
        -0.006929283495992422,
        -0.005336422007530928,
        ... (omitted for spacing)
}
```

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

MacBook M2 Pro laptop

* Operating System, e.g. for Linux:

`Darwin jfalkner-mac 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64`

* SDK version, e.g. for Linux:

```
(base) ➜  ~ python3 --version
Python 3.11.4
(base) ➜  ~ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
(base) ➜  ~ g++ --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

# Failure Information (for bugs)

It responds with OpenAI-incompatible values, causing issues with libraries I am using (in this case, langchain4j) to process embeddings and throws exceptions.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Run a model with llama_cpp_python: `python3 -m llama_cpp.server --embedding=True --model <path to model> --port 8000`
2. Generate embedding with `curl` as above.

# Failure Logs

There is no failure output from llama_cpp_python - it just doesn't generate OpenAI-compatible embedding json responses.

**Comment by iamlemec** [comment]
Those look like token level embeddings, rather than the sequence level embeddings you're looking for. Is the length of the outer list the same as the number of tokens (should be around 4 for "hello world")? I would double check that you're passing the right model to the server. You would expect this kind of output with a generative model, but not an embedding model. I just checked here with `nomic-embed-text-v1.5` and it's giving me a single list.

**Comment by jamesfalkner** [comment]
I think you're right, and it exposes my lack of knowledge with embeddings! Running explicitly with `nomic-embed-text-v1.5` gets the result I was expecting. I'll close this now, thanks for the nudge in the right direction!
