### ISSUE TITLE
AttributeError: 'Llama' object has no attribute 'embed'

### ISSUE THREAD

**Issue by BayramAnnakov** [abetlen/llama-cpp-python#16]
I believe you forgot to change from 'embed' to 'create_embedding' in LlamaCppEmbeddings ('embed_documents' & 'embed_query')

**Comment by abetlen** [comment]
Fixed, sorry about that, that embedding function actually got dropped earlier but I've added it back in to fix langchain support.

You should just be able to `pip install --upgrade llama-cpp-python`

Let me know if that works now.

**Comment by BayramAnnakov** [comment]
It resolves the compilation error - yes, thank you!

but I get the following issue when building index (for your context: I am using GPTSimpleVectorIndex with LLamaEmbeddings to build index)

File /llamacpp.py", line 106, in <listcomp>
    return [list(map(float, e)) for e in embeddings]
ValueError: could not convert string to float: 'object'

**Comment by BayramAnnakov** [comment]
This fixed the attribute error - yes, thank you!

however, when building the index I get this:
File "/opt/miniconda3/envs/mychatbot/lib/python3.10/site-packages/langchain/embeddings/llamacpp.py", line 106, in **embed_documents**
    return [list(map(float, e)) for e in embeddings]
  File "/opt/miniconda3/envs/mychatbot/lib/python3.10/site-packages/langchain/embeddings/llamacpp.py", line 106, in <listcomp>
    return [list(map(float, e)) for e in embeddings]
**ValueError: could not convert string to float: 'object'**

**Comment by BayramAnnakov** [comment]
all good now - thank you @abetlen !
