### ISSUE TITLE
JSON grammar not completely respected

### ISSUE THREAD

**Issue by haldunanil** [abetlen/llama-cpp-python#1600]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Model respects entire JSON schema for grammar. 

# Current Behavior

```python
from llama_cpp import Llama, LlamaGrammar


dirname = path.dirname(__file__)
model_path = path.join(dirname, "../model/model.gguf")

llm = Llama(
      model_path=model_path,
      n_gpu_layers=-1, # Use GPU acceleration
      seed=9, # Set a specific seed
      n_ctx=512, # Set the context window
)

grammar = LlamaGrammar.from_json_schema(dumps({
    "type": "object",
    "properties": {
        "result": {
            "type": "boolean"
        },
        "feedback": {
            "type": "string"
        }
    }
}))

chat_completion = llm.create_chat_completion(
    messages = [
        {
            "role": "system",
            "content": data["system_prompt"]
        },
        {
            "role": "user",
            "content": data["prompt"]
        }
    ],
    temperature=0,
    grammar=grammar,
)
```

When I run this, I get:

```bash
{'id': 'chatcmpl-d00d60bf-a7e4-4726-97bf-0dcc4568479f', 'object': 'chat.completion', 'created': 1721075835, 'model': '../model/model.gguf', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '{ "feedback": "The response starts with \'Hello\', which meets the criterion of saying hello. However, it\'s a very brief and simple greeting. To improve, consider adding more context or details to make it more engaging. [Says hello]: True." }'}, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 208, 'completion_tokens': 54, 'total_tokens': 262}}
```

Note that the `content` above contains `feedback`, but not `result` in the generated object. Oddly, when I remove `feedback`, `result` appears as desired.

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

My laptop is an M1 Pro with 16GB of shared VRAM.

* Operating System, e.g. for Linux:

macOS 14.3

* SDK version, e.g. for Linux:

```
$ python3 --version
Python 3.12.2

$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

$ g++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin23.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

# Failure Information (for bugs)

The grammar is not entirely respected.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Install `llama-cpp-python` with Metal.
2. Download https://huggingface.co/mradermacher/Meta-Llama-3-8B-Instruct-GGUF
3. Give it the following system prompt:

```txt
You are a fair evaluation assistant tasked with providing clear, objective, self-consistent feedback based on a specific criterion.

You will be given a response to evaluate, a binary criterion to evaluate against, and (optionally) additional context to consider. You must provide feedback based on the given criterion and the response.

Please follow these guidelines:

1. Write a detailed feedback that assess the quality of the response strictly based on the binary criterion.
2. Your feedback should end by explicitly stating whether the criterion is met, explicitly using the words True or False.
3. Keep your feedback concise and clear, do not repeat yourself and do not exceed 280 characters for the feedback.
```

4. Give it the following prompt:

```txt
### Response to evaluate:

Hello, world!

### Score Rubrics:

[Says hello]:

- False: The response being evaluated does not meet the criterion described in the square brackets.
- True: The response being evaluated does meet the criterion described in the square brackets.

### Feedback:
```

5. Call the function

# Failure Logs

It doesn't fail, it produces incorrect output.

**Comment by phaylon** [comment]
IIRC the ?properties` are optional (i.e. the LLM may skip them) unless a `required` array forces them to be there.

So you'd have to change it to:

```python
grammar = LlamaGrammar.from_json_schema(dumps({
    "type": "object",
    "properties": {
        "result": {
            "type": "boolean"
        },
        "feedback": {
            "type": "string"
        }
    },
    "required": ["result", "feedback"],
}))
```

I just got up, so I hope I didn't miss anything.

**Comment by haldunanil** [comment]
oh yes, thank you @phaylon!
