### ISSUE TITLE
The latest version kills python kernel with LlamaGrammar

### ISSUE THREAD

**Issue by yamikumo-DSD** [abetlen/llama-cpp-python#1623]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior and Current Behavior
The latest version of llama-cpp-python kills python kernel with LlamaGrammar.
I ran the following code:
```python
from llama_cpp import Llama, LlamaGrammar
model = Llama(model_path="ggufs/Meta-Llama-3-8B-Instruct.Q5_K_M.gguf", verbose=False) # Model doesn't matter.
grammar = LlamaGrammar.from_string('root ::= "a"+')
model("hello", max_tokens=10, grammar=grammar)
```
When it ran, the python kernel died immediately for unknown reason. Dying kernel doesn't happen without use of `LlamaGrammar`. 
Because this behavior has not been observed recently (actually few days ago), I suspect my recent update of llama-cpp-python module made this problem.

What I tried is:
1. Build the latest code by myself -> kernel died
2. Build [the code in the latest release](https://github.com/abetlen/llama-cpp-python/releases/tag/v0.2.83-metal) by myself -> kernel died
3. Re-install [wheel of the latest release](https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.83-metal/llama_cpp_python-0.2.83-cp311-cp311-macosx_11_0_arm64.whl) -> No problem

My experiment might suggest this problem comes from backend Llama.cpp and is not llama-cpp-python's fault.
But anyway, I wanna know whether people is experiencing this bug. 

# Environment
**OS**: macOS Sonoma
**Processor**: M2Max 64GB.
**Python version**: 11

**Comment by handshape** [comment]
I'm experiencing something similar on x86_64 with CUDA since 0.2.84 - segfault when calling LlamaGrammar through the JSON-schema binding. No trouble without the grammar constraint. Rolling back to 0.2.83 fixes it.

**Comment by yamikumo-DSD** [comment]
> I'm experiencing something similar on x86_64 with CUDA since 0.2.84 - segfault when calling LlamaGrammar through the JSON-schema binding. No trouble without the grammar constraint. Rolling back to 0.2.83 fixes it.

Which do you think should we blame for it, llama-cpp-python or native Llama.cpp?
I observe no issue arisen on this problem in Llama.cpp's issue page regardless of increasing demand on function calling, which I see weird. (so, environment dependent thing?)
The version of these module really matters as new models popping up every week, and I don't want to stick to the old versions.

**Comment by axel7083** [comment]
> I ran the following code:

I do reproduce the same error. After entering the code you provided the program stop.

The scenario where the problem occurs can be found in detailed in https://github.com/abetlen/llama-cpp-python/issues/1636 (and the hardware/software specification).

Rolling back to 0.2.82 seems to fix the problem: the code provided execute without crash/issue on previous version.

**Comment by yamikumo-DSD** [comment]
> > I ran the following code:
> 
> I do reproduce the same error. After entering the code you provided the program stop.
> 
> The scenario where the problem occurs can be found in detailed in #1636 (and the hardware/software specification).
> 
> Rolling back to 0.2.82 seems to fix the problem: the code provided execute without crash/issue on previous version.

I found recent Llama.cpp did split the main source code (llama.cpp) into several part;
```
llama-grammar.cpp
llama-sampling.cpp
llama-vocab.cpp
```
These source files found in the latest release cannot be found in releases a week ago.
though I'm not familiar with binding method between C++ and Python, i suspect some internal changes in Llama.cpp causes mismatch of communication between C++-implemented binaries and Python.

**Comment by handshape** [comment]
Looks like work is underway: https://github.com/abetlen/llama-cpp-python/pull/1637

**Comment by ProfessorAO** [comment]
Anyone find a solution for this ?

**Comment by handshape** [comment]
> Getting the same error, both in colab and in personal. On vs code it comes up as an OS Error or Win Error.
> 

Pretty sure this PR addresses it, pending the next release: https://github.com/abetlen/llama-cpp-python/pull/1649
