### ISSUE TITLE
Please bump llama.cpp version to b3472 to have llama 3.1 support

### ISSUE THREAD

**Issue by leszekhanusz** [abetlen/llama-cpp-python#1625]
llama.cpp release [b3472](https://github.com/ggerganov/llama.cpp/releases/tag/b3472) added support for llama 3.1.

Could you please bump the llama.cpp version?

**Comment by RandomInternetPreson** [comment]
The last piece of the puzzle. Textgeneration webui uses this library, and because of the rope factors are added as a tensor, an error is returned saying it received the incorrect number of tensors.  When trying to load a model converted to gguf using the latest llama.cpp code.

**Comment by RandomInternetPreson** [comment]
It's happening ❤️

**Comment by leszekhanusz** [comment]
It has been done in [release 0.2.84](https://github.com/abetlen/llama-cpp-python/blob/main/CHANGELOG.md#0284). Thanks!
