### ISSUE TITLE
Bug: GitHub Pages missing wheels for v0.2.83 - v0.2.86

### ISSUE THREAD

**Issue by gaby** [abetlen/llama-cpp-python#1627]
@abetlen The github-pages are missing the wheels for `v0.2.83` https://abetlen.github.io/llama-cpp-python/whl/cpu/llama-cpp-python/ I think you trigger these manually?

**Comment by gaby** [comment]
Wheels for v0.2.84 are also not in the GitHub Page

**Comment by jcuenod** [comment]
Perhaps related: https://github.com/abetlen/llama-cpp-python/issues/1377
(also missing 0.2.85 now)

**Comment by abetlen** [comment]
@gaby thanks should be fixed now.

**Comment by gaby** [comment]
@abetlen Thank you! 💪

**Comment by abetlen** [comment]
@gaby I've also fixed the CI workflow so that it automatically runs on all new releases now (I thought I had done this previously but it was misoncfigured).

**Comment by gaby** [comment]
Thank you!  Looks good 💪💪💪
