### ISSUE TITLE
Using Llama-cpp with FastAPI to connect a html.

### ISSUE THREAD

**Issue by raymerjacque** [abetlen/llama-cpp-python#166]
Currently I deploy my model on my serverbox using FastAPI below :
```
from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from llama_cpp import Llama
import json

app = FastAPI()

llm = Llama(model_path="./model/ggml-model-q8_0.bin")

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

from pydantic import BaseModel

class InputData(BaseModel):
    prompt: str

@app.post("/api/ask")
async def ask(data: InputData):
    print("Received request:", data)
    output = llm(f"Q: {data.prompt} A: ",
                 max_tokens=400,
                 temperature=0.7,
                 top_p=0.9,
                 stop=["Q:", "\n"],
                 echo=False,
                 repeat_penalty=1.1,
                 top_k=40)

    # Extract the relevant information from the output
    response_text = output.get("choices", [])[0].get("text", "")

    return {"response": response_text}

if __name__ == "__main__":

    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=5000)
   
```

Then i connect my html to it from another box, basically using it as a chatbot, my goal is not to use it for http ultimately, i am simply using it this way for testing, But, This actually works very effectively.

Is there anything else i can do here to optmize the deployment of the model ? its a little slow on its response times. the VPS i use is a 4 core box with 16GB ram, this is a 7B model, so i have twice the required ram, and still most responses seem to take around 30 to 60 seconds, however i can see on the server console that the model recieved the input query within the first 2 or 3 seconds... it then takes about 30 to 60 seconds to generate a response. so its not an internet issue. its the actual model taking time to generate a resonse. is there anything i can modify in my script to speed up the generation proccess ?  I have tried setting max tokens down, it doesnt make that much of a difference.  Any guidance would be appreciated. 

here is an example of generated response :

```
INFO:     xx.xx.xx.xx:37196 - "OPTIONS /api/ask HTTP/1.1" 200 OK
Received request: prompt='describe mars'

llama_print_timings:        load time =  4102.40 ms
llama_print_timings:      sample time =    97.96 ms /   103 runs   (    0.95 ms per run)
llama_print_timings: prompt eval time =  4102.33 ms /     8 tokens (  512.79 ms per token)
llama_print_timings:        eval time = 45712.52 ms /   102 runs   (  448.16 ms per run)
llama_print_timings:       total time = 59561.53 ms
INFO:    xx.xx.xx.xx:37196 - "POST /api/ask HTTP/1.1" 200 OK
```

As you can see, this response took 60 seconds... on my html it showed 60.4... so very little time is lost through http, the delay is the model itself. and ive tried many models, most are slower, this model has been the fastest yet.
    
you can actually test it yourself, i have a webiste i setup here for testing purposes : 
    
is there anything i can modify in my script to speed up the generation proccess ?  I have tried setting max tokens down, it doesnt make that much of a difference.  Any guidance would be appreciated.

**Comment by gjmulder** [comment]
More cores will help up until about 8 or 12. Then you're likely limited by memory speed. Here's some numbers using a `65B-q5_1` model on a 16 physical core AMD 1950X:

```
$ lscpu | grep "^CPU(s)"
CPU(s):                          32

$ sudo dmidecode -t processor | grep Hz 
	External Clock: 100 MHz
	Max Speed: 4200 MHz
	Current Speed: 3400 MHz

$ sudo dmidecode --type 17 | grep Speed | sort -u
	Configured Memory Speed: 2666 MT/s
	Speed: 2666 MT/s
```

```
llama_print_timings:        load time = 18498.45 ms
llama_print_timings:      sample time =    40.00 ms /    64 runs   (    0.63 ms per run)
llama_print_timings: prompt eval time = 20896.10 ms /   121 tokens (  172.70 ms per token)
llama_print_timings:        eval time = 90135.39 ms /    63 runs   ( 1430.72 ms per run)
llama_print_timings:       total time = 114295.56 ms
```

**Comment by raymerjacque** [comment]
# lscpu | grep "^CPU(s)"

CPU(s):                          6

# sudo dmidecode -t processor | grep Hz 

	Max Speed: 2000 MHz
	Current Speed: 2000 MHz
	
# sudo dmidecode --type 17 | grep Speed | sort -u

	Configured Memory Speed: Unknown
	Speed: Unknown

**Comment by gjmulder** [comment]
See #155

**Comment by raymerjacque** [comment]
its work in progress, not yet finished. when im done ill upload to github... 

but here is a little demo video you can see how quick and speedy it is... ( I now have a website and an android app that points to my server ) I call my AI model ( Electra ). 

see the video i made on my phone : 

[https://youtu.be/TY0Pdsr1-qE](https://youtu.be/TY0Pdsr1-qE)

**Comment by gjmulder** [comment]
Great job! If instead of a timer counting up you could simulate the "...." of typing it might feel even a bit more interactive?

**Comment by raymerjacque** [comment]
Well, as i said, Im not really making it for web use, I run a Linux Distro "MakuluLinux". and I am actually building this to integrate with the Linux using Voice.  The Website and android app are just extra's ... In the Linux distro I use the timer in the terminal, it looks kickass in the terminal. I am nearly done. when im dont i'll upload to github and link it to you guys, if you find anything useful you can include it, if not, you can simply just point people to the files that are looking for a similar setup.

**Comment by ibrahimpallah-code** [comment]
Just make it clear
