### ISSUE TITLE
Somehow, the llama-cpp-python doesn't perform as fast as the native llama cpp

### ISSUE THREAD

**Issue by mzbac** [abetlen/llama-cpp-python#167]
I have tried both on my Mac M1 max. The native llama cpp build from source code can run Vicuna 13b around 100ms per token, but on the llama-cpp-python it's around 1 token per second. It's significantly slower.

**Comment by jmtatsch** [comment]
Is memlock disabled in the python binding? It makes a large difference on Mac I think.

**Comment by abetlen** [comment]
@jmtatsch it was disabled by default because of some platform bugs, I've just pushed a version (v0.1.44) that enables it by default if `llama_mmap_supported` returns `True`.

**Comment by jmtatsch** [comment]
Something is still severely broken with performance on my m1 Mac.

Running the high-level example just stalls for ages like the thread deadlock.
When using the langchain example https://python.langchain.com/en/latest/modules/models/llms/integrations/llamacpp.html it works but extremely slow (like op). 
When running native llama.cpp its quite usable  97.86 ms per token.

Compilation of llama-cpp-python looks fine. All suitable acceleration flags seem set.

Can you maybe enhance the verbose mode to output all the inferred flags and threading options so we can narrow these performance issues down? 

Sometimes I noted that the final timings after high-level api call are missing
```
llama_print_timings:        load time =  5389.06 ms
llama_print_timings:      sample time =    42.71 ms /    60 runs   (    0.71 ms per run)
llama_print_timings: prompt eval time =  5389.03 ms /    27 tokens (  199.59 ms per token)
llama_print_timings:        eval time = 10700.45 ms /    59 runs   (  181.36 ms per run)
llama_print_timings:       total time = 17324.15 ms
```
presumably if the end token was not found or something.
llama.cpp always gives them back even after ctrl+c. Any way to achieve that?

Update: After running these example programs several times they run quite consistently at sub second speeds. Like an old motor that needs to warm up. 🤯

**Comment by x4080** [comment]
hello, is the speed using python is speedy like llama cpp ? I wondered what api should I use to connect it to external app

**Comment by mzbac** [comment]
I dug a bit deeper into the issue. It turns out that when using Mac M1, you have to install the Python interpreter for ARM64 architecture. Otherwise, LlamaCPP will be built for x86 architecture which is 10 times slower on Mac M1 machines. So, you just need to uninstall whatever Python runtime you have on your machine and reinstall the ARM64 version. for example:
```
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh
bash Miniforge3-MacOSX-arm64.sh
```
cc @abetlen

**Comment by abetlen** [comment]
@mzbac thank you for investigating this! I'll close for now and make a change in the docs.
