### ISSUE TITLE
Add MiniCPM-V-2.6 to supported multi-modal models

### ISSUE THREAD

**Issue by wkzcml-1** [abetlen/llama-cpp-python#1678]
I would like to request the addition of MiniCPM-V-2.6 to the supported multi-modal models in llama-cpp-python. This model, which is already supported by llama.cpp, is capable of video understanding and would be a valuable addition for those working on multi-modal projects. Thank you!

**Comment by abetlen** [comment]
@wkzcml-1 added in v0.2.90
