### ISSUE TITLE
[Feature] Dynamic Model Loading and Model Endpoint in FastAPI

### ISSUE THREAD

**Issue by MillionthOdin16** [abetlen/llama-cpp-python#17]
I'd like to propose a future feature I think would add useful flexibility for users of the `completions/embeddings` API . I'm suggesting the ability to dynamically load models based on calls to the `FastAPI` endpoint.

The concept is as follows:
- Have a predefined location for model files (e.g., a `models` folder within the project) and allow users to specify an additional model folder if needed.
- When the API starts, it checks the designated model folders and populates the available models dynamically.
- Users can query the available models through a `GET` request to the `/v1/engines` endpoint , which would return a list of models and their statuses.
- Users can then specify the desired model when making inference requests.

This dynamic model loading feature would align with the behavior of the OpenAI spec for models and model status. It would offer users the flexibility to easily choose and use different models without having make manual changes to the project or configs.

This is a suggestion for later, but I wanted to suggest it now so we can plan if we do decide to implement it.

Let me know your thoughts :)

**Comment by 0xdevalias** [comment]
Potentially related:

- https://github.com/abetlen/llama-cpp-python/issues/38

**Comment by MillionthOdin16** [comment]
@abetlen 

Here's something that seemed interesting from vicuna that I just saw. I can definitely see the challenge trying to adapt to all these different input formats. This seemed like an extendable format that might help, not sure where you currently are on it.

https://github.com/lm-sys/FastChat/blob/00d9e6675bdff60be6603ffff9313b1d797d2e3e/fastchat/conversation.py#L83-L112

**Comment by abetlen** [comment]
@jmtatsch @MillionthOdin16 thank you!

I still have a few questions on the best way to implement this, appreciate any input.

The basic features would allow you to:
- Specify a config file in whatever format is easiest for pydantic to parse
- Specify one or more models to load with their paths, default llama.cpp parameters, and an alias.

The part I'm still scratching my head on are the chat models
- The request passes in a list of messages
- Turning chat messages -> prompt is model dependent
- Only some models (Vicuna, maybe gpt4all) can handle chat corectly.

I guess the solution would be to have some way to specify these pre-defined models and custom prompt serialisation functions for each.

**Comment by docmeth02** [comment]
> I guess the solution would be to have some way to specify these pre-defined models and custom prompt serialisation functions for each.

Hi!
the way i implemented this on a local copy is that i added a method called generate_completion_prompts to llama_cpp.Llama that returns the PROMPT strin and the PROMPT_STOP list.

That way you can override the prompt generation from the outside and you could provide a list of model specific implementations to handle the message history and prompt generation on a per model basis :)

**Comment by abetlen** [comment]
Implemented in #931
