### ISSUE TITLE
PyPi index only includes the latest releases

### ISSUE THREAD

**Issue by OKUA1** [abetlen/llama-cpp-python#1701]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

The pypi index should include pre built wheels for all releases previous releases.

# Current Behavior

The GitHub API returns paginated responses. Currently, only the first page is used when building the index.

**Comment by abetlen** [comment]
@OKUA1 thanks for reporting this, it should be fixed now to pull all pages!
