### ISSUE TITLE
Adding MiniCPM-V-2.6 support

### ISSUE THREAD

**Issue by 2OsZI4ISYd** [abetlen/llama-cpp-python#1707]
MiniCPM-V-2.6 has shown incredible performance in many tasks, especially in digitizing complex documents; as such, it has a huge potential for educational and business applications. 

Support for the model now exists on the main build, but I don't think that it's been added here. I would appreciate if the devs would consider adding the functionality. Thanks!

**Comment by thistleknot** [comment]
yes please

main issue seems to be what chat handler and how to load gguf mmproj clip

**Comment by abetlen** [comment]
@2OsZI4ISYd should be available now in 0.2.90, link in README
