### ISSUE TITLE
Base settings confusion (How to disable mlock)

### ISSUE THREAD

**Issue by snxraven** [abetlen/llama-cpp-python#171]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
Before the latest updates I have been using ENV Vars to set base settings for things like cache, n_threads etc.

This does not seem to work anymore, I noticed the readme was updated to show the use of switches like this:
--model models/7B/ggml-model.bin

Is this how all base settings are given now? The model switch above does infact work.

Usually llama.cpp will default to mmap by itself but in the new versions I keep seeing the cannot mlock errors.

I have attempted ENV and switches to disable mlock and I cannot seem to do so.

I have attempted:

--use_mlock 0

--use_mmap 1

a combination including both of these togetjer and seperate.

While testing was happening the env vars were not touched.

# Current Behavior

Instead of disabling mlock, it seems that its default every time I run the server.

**Comment by abetlen** [comment]
This is a bug, the behaviour is that it should allow for both environmnet variables and cli options and validate at the end.

@gjmulder for dockerfiles the environmnet variables are still preferred because they play better with the variaous container deployment methods

**Comment by abetlen** [comment]
@snxraven a fix should be pushed that lets you use the environment variables, let me know if that works. You can also call `--help` now for a full list of cli arguments and their defualt values.

**Comment by snxraven** [comment]
@abetlen I have attempted the latest it does not seem to fall back for me and I still see the memlock errors:
![image](https://user-images.githubusercontent.com/1396275/236904240-3119adac-0f18-4e60-96bc-82c01dafd42f.png)

All of my previous settings within my docker env are ignored in 0.1.46

I confirmed this because cache and n_threads was also ignored.

**Comment by gjmulder** [comment]
`MODEL` does work, however.

Ditto on the `MLOCK` warning. I worked around it with the following change to my `Dockerfile`:

`CMD bash -c "ulimit -l unlimited && python3 -m llama_cpp.server"`

**Comment by abetlen** [comment]
@snxraven you're right, I ended up ignoring environment variables for options that had defaults (why MODEL worked but e.g. N_THREADS didn't) because they were being set by the argparse. That should be fixed with v0.1.47

**Comment by snxraven** [comment]
building and trying :)

**Comment by abetlen** [comment]
@snxraven that's not an warning I can disable if mlock is enabled that warning will come up. If you are using mlock I would recommend increasing that limit, I remember looking it up and I just had to edit `/etc/security/limits.conf` and add two lines

```
*        hard    memlock        unlimited
*        soft    memlock        unlimited
```

**Comment by snxraven** [comment]
The issue was not being able to disable mlock at all.

With all of your recent changes, it does seem setting:

USE_MLOCK=0 

Is working, it seems this issue can now be closed :)
