### ISSUE TITLE
Request for prebuilt CUDA wheels for newer version

### ISSUE THREAD

**Issue by XJF2332** [abetlen/llama-cpp-python#1824]
I noticed that 0.3.0 and 0.3.1 have no prebuilt CUDA wheels
I would be grateful if there are prebuilt wheels for newer versions.

**Comment by pabl-o-ce** [comment]
+1 here jeje

**Comment by pabl-o-ce** [comment]
it seems that there some issues creating windows wheels https://github.com/abetlen/llama-cpp-python/actions/runs/11148387475

**Comment by John6666cat** [comment]
+1 here

**Comment by pabl-o-ce** [comment]
I get this github actions to change over installing manually [cuda drivers - Jimver/cuda-toolkit](https://github.com/Jimver/cuda-toolkit) on windows/ubuntu. Im exploring to set this

**Comment by pabl-o-ce** [comment]
I fix the wheels for [linux](https://github.com/pabl-o-ce/llama-cpp-python/actions/runs/11939921813/job/33281483401) just for testing this Jimver/cuda-toolkit.

But I think I can solve the one for windows and I think what is the issue (just come in a moment to see if work that take to much time to run it)

**Comment by Muzixin** [comment]
+1 here

**Comment by pabl-o-ce** [comment]
I fixed guys

send the PR #1838

**Comment by John6666cat** [comment]
Great!
https://github.com/abetlen/llama-cpp-python/releases/tag/v0.3.4-cu124

**Comment by XJF2332** [comment]
thank you guys for your amazing work!

**Comment by AleefBilal** [comment]
Install llama-cpp wheel, v0.3.4 for cuda 12.2 using.
`CMAKE_ARGS="-DLLAMA_CUBLAS=ON" pip install https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.4-cu122/llama_cpp_python-0.3.4-cp311-cp311-linux_x86_64.whl`. Lookout for other versions by checking out 
https://github.com/abetlen/llama-cpp-python/releases
