### ISSUE TITLE
chat llama cli python the User prompts sometimes print out sometimes not

### ISSUE THREAD

**Issue by lucasjinreal** [abetlen/llama-cpp-python#186]
![image](https://github.com/abetlen/llama-cpp-python/assets/21303438/0fb916a7-151a-4feb-a043-b32e1162eec8)

this is anoying

**Comment by SagsMug** [comment]
The default 7B model is too dumb to act like a chatbot.
Use alpaca or the 13B model.

**Comment by lucasjinreal** [comment]
@SagsMug hi, am just using 13B, and cpp gives me right prompt every time.

**Comment by lucasjinreal** [comment]
@SagsMug Also, what if I don't need this role playing in terminal, I just need replay to users raw input sentence, how can I write the prompt and using the config (gptParams)? In short, I don't need the role name prefix in every sentence.

**Comment by gjmulder** [comment]
Any update?
