### ISSUE TITLE
Default temperature for llama-cpp-python server

### ISSUE THREAD

**Issue by Qsan1** [abetlen/llama-cpp-python#1868]
Hey,

I have two questions. 
1. Is the default temperature for the llama-cpp-python server the same as the llama-cpp server (0.8)?
2. Is there a way to configure the temperature for the llama-cpp-python server? It is not an option in the command line and I also cant find it [here](https://llama-cpp-python.readthedocs.io/en/latest/server/). I am asking, because the llama-cpp server does have an option for it, according to this [README](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md)

**Comment by sergey21000** [comment]
1. The default temperature is 0.8 [llama_cpp/server/types.py#L25](https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/server/types.py#L25)

2. Temperature can be set via the API request parameters for both `chat/completions` and `completions` endpoints.  
Here are examples:  
```
python3 -m llama_cpp.server --model ./gemma-2-2b-it-Q8_0.gguf

curl -X POST \
	--url http://localhost:8000/v1/chat/completions \
	-H "Content-Type: application/json" \
	-d '{
	  "model": "gemma-2-2b-it-Q8_0.gguf",
	  "messages": [{"role": "user", "content": "Why is grass green?"}],
	  "temperature": 0.2,
	  "top_p": 0.95,
	  "top_k": 40
	}'

curl -X POST \
	--url http://localhost:8000/v1/completions \
	-H "Content-Type: application/json" \
	-d '{
	  "prompt": "<bos><start_of_turn>user\nWhy is grass green?<end_of_turn>\n<start_of_turn>model\n", 
	  "temperature": 0.2, 
	  "top_p": 0.95, 
	  "top_k": 40,
	  "max_tokens": 1000
	}'
```

**Comment by Qsan1** [comment]
Thank you! I appreciate the help.
