### ISSUE TITLE
Add Verbose Logging Support to Diagnose Performance Issues

### ISSUE THREAD

**Issue by luminalle** [abetlen/llama-cpp-python#19]
Sorry, this might be totally wrong place to open the issue. Feel free to close.

Anyway, I'm working with a 3rd party project* that uses your awesome wrapper and I'm having problems there, which brings me back here. Everything seems to be working, but not with the speed I expect after using plain llama.cpp. With some prompts it seems to even completely freeze, never completing the task. Could I somehow raise this wrapper's logging level to make it more verbose, so I could see in real-time as it works?

\* https://github.com/hwchase17/langchain

**Comment by abetlen** [comment]
Hi, thanks for submitting this issue!

Yes, we can add logging support!

If possible do you mind providing some of the following:
- operating system (Linux / MacOS / Windows)
- cpu architecture (x86 / M1)
- python package manager (pip / conda / poetry)
- langchain examples of slow / hanging completions

**Comment by abetlen** [comment]
I'm adding `verbose` flag to the `Llama` instance but in the meantime can you try (and kindly post here if possible) the following.

```python
from langchain.llms import LlamaCpp
import llama_cpp

# change model path
llm = LlamaCpp(model_path="./ggml-model-q4_0.bin")
ctx = llm.client.ctx # this returns the llama.cpp context
llama_cpp.llama_print_system_info()
llama_cpp.llama_reset_timings(ctx)
llm("Some example phrase")
llama_cpp.llama_print_timings(ctx)
```

And let me know if the output of `print_system_info` matches what you get when you run e.g. `./main` in `llama.cpp`

**Comment by abetlen** [comment]
Gotcha, it looks like it compiled correctly wrt optimisations.

There are a few knobs for the `Llama` class that aren't exposed in LangChain (I'll try to create a PR for those soon) but you should be ale to replace the instance in the embedding class with a new "more tuned" version as follows:

```
new_llama = Llama(**kwargs)
LlamaCpp.client = new_llama
```

The kwargs I'd play with are
- `n_threads`: Anywhere between cpu_count / 2 to cpu_count should be ideal
- `use_mlock`: `True`
- `f16_cache`: True
- `n_batch`: Set the max value of this to your `n_ctx` this effects how many tokens get `eval`'d at once.

Let me know if any of that helps.

**Comment by luminalle** [comment]
Could not make it work without getting:
`ValueError: llm must be an instance of langchain.llms.base.LLM`

Quite possibly I did it wrong though. I tried it with LlamaCpp and LlamaCppEmbeddings with same result.
```
from llama_cpp import Llama
new_llama = Llama(**LlamaArgs)
LlamaCpp.client = new_llama

# define our LLM
llama_llm = LlamaCpp.client
predictor = LLMPredictor(llm=llama_llm)
```
With the original `llama_llm = LlamaCpp(**LlamaArgs)` line, I would just get multiple instances (and the error for unknown arg)

**Comment by abetlen** [comment]
Sorry I think you might have misunderstood, you should still initialise the `llm` from as a `LlamaCpp` class but then just replace the internal client.

```
llama_llm = LlamaCpp(**LlamaArgs)
llama_internal = llama_cpp.Llama(n_ctx=2048, n_batch=2048, use_mlock=True, f16_cache=True, embedding=True)
llama_llm.client = llama_internal
predictor = LLMPredictor(llm=llama_llm)
```
