### ISSUE TITLE
Indexing custom documents with llama-cpp-python.

### ISSUE THREAD

**Issue by veerlosar** [abetlen/llama-cpp-python#195]
Hello, thanks for your work! 

I was wondering if it's already possible to add/index your documents to llama-like models with llama-cpp-python and then chat about those documents with it. If not, it would be nice to have a feature like this if possible, of course. If yes, could you point me to an example or create it? 

Thanks in advance.

**Comment by veerlosar** [comment]
@gjmulder I might have not made myself clear. My question was, is it possible to finetune/index custom documents for llama-likes with llama-cpp-python (this library)? If yes, could you please give a link to the tutorial?

**Comment by abetlen** [comment]
@veerlosar yes you can, here are a few options:

- The Llama class offers an [`embed`](https://abetlen.github.io/llama-cpp-python/#llama_cpp.llama.Llama.embed) function
- [`langchain`](https://python.langchain.com/en/latest/ecosystem/llamacpp.html) 
- [`llamaindex`](https://gpt-index.readthedocs.io/en/latest/index.html)

**Comment by veerlosar** [comment]
@abetlen Thank you!
