### ISSUE TITLE
GPU inference

### ISSUE THREAD

**Issue by Miao-WangHao** [abetlen/llama-cpp-python#196]
Hello, is there any inference mode for GPU?

**Comment by gjmulder** [comment]
There is partial support for GPUs if you compile with CuBLAS.

**Comment by Miao-WangHao** [comment]
hi，Is there a tutorial?

**Comment by gjmulder** [comment]
https://github.com/abetlen/llama-cpp-python/blob/main/README.md

**Comment by Miao-WangHao** [comment]
> https://github.com/abetlen/llama-cpp-python/blob/main/README.md

Brother, how to configure windows?

**Comment by Miao-WangHao** [comment]
thx a lot

**Comment by Celppu** [comment]
I built it with cublas but high level api streaming example does not use gpu at all. How do I get it to offload to gpu?

**Comment by Miao-WangHao** [comment]
> #182 might help

I configured cublas on linux, but I couldn't load it to the GPU here either, I couldn't even find where to set the parameters to load to the GPU, I was so confused.I need help, brother

**Comment by gjmulder** [comment]
If CuBLAS is enabled it with use CuBLAS. Run nvidia-smi to see if it is running a process on your GPU.

You need to set `n_gpu_layers=1000` when you create the model to get full GPU offloading, assuming you have enough VRAM for the model size you are using.

Finally the GPU will likely only be active if your prompts are longer than 32. The overhead for shorter prompts makes GPU offload suboptimal.
