### ISSUE TITLE
Investigate using `make` instead of `cmake` to build shared library

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#20]
It's been pointed out that `make` may be better supported by `llama.cpp` (on some platforms). We're currently using `scikit-build` to build the shared library on installation with `cmake` but it also supports [make](https://scikit-build.readthedocs.io/en/latest/generators.html#unix-makefiles).

Additional note as pointed out in #32 we should support passing environment variables in both settings.

**Comment by pjlegato** [comment]
With current master branches from both projects, I can get it to work by going into `vendor/llama.cpp`, then doing `make libllama.so`, then manually copying that .so to the main project's `llama_cpp` directory (as suggested at https://github.com/ggerganov/llama.cpp/pull/797). The automatic build process doesn't work.

**Comment by abetlen** [comment]
https://cmake.org/pipermail/cmake/2010-November/040631.html suggests adding a custom target to the root CMakeLists of this project and calling make in llama.cpp. I'll try this approach.

**Comment by abetlen** [comment]
@pjlegato I've pushed a fix to build the project using make on linux and macos, do you mind testing it for me? If you can confirm that it works I'll push to PyPI.
