### ISSUE TITLE
How to implemant CLBLAST on windows ?

### ISSUE THREAD

**Issue by LeLaboDuGame** [abetlen/llama-cpp-python#201]
Hey ! I'm on windows and I want to use CLBLAST to use the model with my amazing RX6600XT (AMD GPU) ! 
I dont know why but when I execute this cmd to install the py lib with CLBLAST parameter, CLBLAST are not install !!

the cmd:

```powershell
$env:CMAKE_ARGS="-DLLAMA_CLBLAST=on"; $env:FORCE_CMAKE=1;
 pip install llama-cpp-python
```

I did something wrong  ? **_I'm crazy ?!_**

So if anyone can help me out it's greatly appreciated!
Labo

PS:My english is verrrrry bad so excuse me in adnvance for my level laungage.

**Comment by gjmulder** [comment]
Please provide a better description of your problem as per [ISSUE_TEMPLATE/bug_report.md](https://github.com/abetlen/llama-cpp-python/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
