### ISSUE TITLE
Bug in tokenize function

### ISSUE THREAD

**Issue by r3v1** [abetlen/llama-cpp-python#206]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

The `tokenize` method should return the list of tokens of the input text,of `List[int]` type I supose. In fact, there is a [TODO](https://github.com/abetlen/llama-cpp-python/blob/d90c9df32639397078a439c86ac6a474043ce57d/llama_cpp/llama_cpp.py#L347) pointing out this issue.

# Current Behavior

Instead, an error raises:
```python
ctypes.ArgumentError: argument 2: TypeError: wrong type
```

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Operating System, e.g. for Linux:

```sh
$ uname -a
Linux msi 6.1.26-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 26 Apr 2023 19:15:42 +0000 x86_64 GNU/Linux
```

* SDK version, e.g. for Linux:

```
$ python3 --version
Python 3.10.10

$ make --version
GNU Make 4.4.1
Este programa fue construido para x86_64-pc-linux-gnu
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ g++ --version
g++ (GCC) 12.2.1 20230201
Copyright (C) 2022 Free Software Foundation, Inc
```
# Steps to Reproduce

```python
from llama_cpp import Llama
llm = Llama(n_ctx=512, model_path="./models/7B/ggml-model-f16.bin")
llm.tokenize("Hello world!")
```

# Failure Logs

```sh
python test.py 
llama.cpp: loading model from models/7B/ggml-model-f16.bin
llama_model_load_internal: format     = ggjt v1 (pre #1405)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 1 (mostly F16)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  72.75 KB
llama_model_load_internal: mem required  = 14645.09 MB (+ 1026.00 MB per state)
llama_init_from_file: kv self size  =  256.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
Traceback (most recent call last):
  File "[...]/test.py", line 3, in <module>
    llm.tokenize("Hello world!")
  File "[...]/venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 196, in tokenize
    n_tokens = llama_cpp.llama_tokenize(
  File "[...]/venv/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 355, in llama_tokenize
    return _lib.llama_tokenize(ctx, text, tokens, n_max_tokens, add_bos)
ctypes.ArgumentError: argument 2: TypeError: wrong type
```

**Comment by abetlen** [comment]
@r3v1 as per the docs tokenize operates over bytes not strings, `llm.tokenize(b"Hello world!")` should work.

**Comment by r3v1** [comment]
Oh I see, tahanks. Should it be mentioned in some documentation? Or typing operators?

**Comment by abetlen** [comment]
@r3v1 it is afaik, did you not get a type error?

**Comment by r3v1** [comment]
I'm using VSCode and it doesnt show any relating to type errors. Yes, it should show some type of warning
