### ISSUE TITLE
Add support for llama.cpp --n_gpu_layers

### ISSUE THREAD

**Issue by moonlightelite** [abetlen/llama-cpp-python#207]
llama.cpp a day ago added support for offloading a specific number of transformer layers to the GPU (https://github.com/ggerganov/llama.cpp/commit/905d87b70aa189623d500a28602d7a3a755a4769).

llama-cpp-python already has the binding in 0.1.15 (n_gpu_layers, https://github.com/abetlen/llama-cpp-python/commit/cdf59768f52cbf3e54bfe2877d0e5cd3049c04a6#diff-9184e090a770a03ec97535fbef520d03252b635dafbed7fa99e59a5cca569fbc), but llama.py and llama_cpp.py don't use --n_gpu_layers yet.

**Describe the solution you'd like**
Add support for --n_gpu_layers.

**Additional context**
I get around 50% speedup by offloading some (25-40) of the transform layers work to the GPU in the latest llama.cpp.

https://www.reddit.com/r/LocalLLaMA/comments/13gok03/llamacpp_now_officially_supports_gpu_acceleration/

**Comment by gjmulder** [comment]
`N_GPU_LAYERS=1000`

seems to already be working for me:

```
docker run -e CUDA_VISIBLE_DEVICES=1 -e MODEL=/var/lib/models/Wizard-Vicuna-13B-Uncensored-GGML/Wizard-Vicuna-13B-Uncensored.ggml.q5_1.bin -e N_CTX=512 -e CACHE=1 -e CACHE_SIZE=17179869184 -e N_GPU_LAYERS=1000 --cap-add SYS_RESOURCE -v /data/llama:/var/lib/models -p 8000:8000 --gpus all lcp:cublas07

==========
== CUDA ==
==========

CUDA Version 12.1.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

llama.cpp: loading model from /var/lib/models/Wizard-Vicuna-13B-Uncensored-GGML/Wizard-Vicuna-13B-Uncensored.ggml.q5_1.bin
llama_model_load_internal: format     = ggjt v2 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  90.75 KB
llama_model_load_internal: mem required  = 11359.05 MB (+ 1608.00 MB per state)
....................................................................................................
llama_model_load_internal: [cublas] offloading 40 layers to GPU
llama_model_load_internal: [cublas] offloading output layer to GPU
llama_model_load_internal: [cublas] total VRAM used: 9192 MB
llama_init_from_file: kv self size  =  400.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
INFO:     Started server process [27]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

**Comment by gjmulder** [comment]
> I'm trying this right now and it's only using the cpu. did a clean pip install and build. windows 10 with all the cuda stuff installed. Any suggestions? I see you have [cublas]. what is that? There doesn't seem to be any instructions here to get gpu running?

Please try the script in #182 as I don't know anything about windows builds.

I run with NVidia containers in Docker on Ubuntu 22.04, which means everything is pre-installed and configured, except `llama-cpp-python`

**Comment by gjmulder** [comment]
> This is all very very complicated. It builds the latest version when I install it, shouldn't this just work on the GPU with this new n_gpu_layers? What is this script even doing?

GPU support is [very complicated](https://github.com/ggerganov/llama.cpp/issues?q=gpu+).

To quote `Wizard-Vicuna-13B-Uncensored.ggml.q5_1.bin`:
```
Complex systems are
Sophisticated, yet delicate
Performance matters most
```
If you don't have the time, you might want to try 128 vCPUs from AWS:

[x1.32xlarge](https://aws.amazon.com/about-aws/whats-new/2016/05/now-available-x1-instances-the-largest-amazon-ec2-memory-optimized-instance-with-2-tb-of-memory/)

**Comment by gjmulder** [comment]
Impossible to give fixed guidelines as it is dependent on your model size, GPU VRAM and context size.

Run `nvidia-smi` and do a rough search using: 4, 8, 16, 32

You'll want to leave some VRAM free for the context.

**Comment by jeppelsh** [comment]
@gjmulder Can you go into a bit more detail? What criteria do I go by after calling nvidia-smi? To be specific: Gemma-29b-it has a total of 43 layers. You suggest to increase the number of layers iteratively. But what is the criteria i am then looking at? The remaining VRAM? The gpu utilization? At what point should I stop increasing the number of layers being offloaded?
