### ISSUE TITLE
Failed to load shared library

### ISSUE THREAD

**Issue by teristam** [abetlen/llama-cpp-python#208]
I compiled and installed the latest code (0.1.5) in Windows 11 with Python 3.10.11 and CUDA 11.8. The compilation with cuBLAS flag and installation were successful. When importing the module via `from llama_cpp import Llama`, python reported

```
Failed to load shared library 'C:\Users\teristam\Anaconda3\envs\textgen\Lib\site-packages\llama_cpp\llama.dll': 
Could not find module 'C:\Users\teristam\Anaconda3\envs\textgen\Lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
But when I change 
 https://github.com/abetlen/llama-cpp-python/blob/d90c9df32639397078a439c86ac6a474043ce57d/llama_cpp/llama_cpp.py#L55

to `ctypes.CDLL(str(_lib_path),winmode=0)`, the dll is able to load succesfully. It may be related to a bug in ctype in Windows:

https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python/64472088#64472088
https://bugs.python.org/issue42114

**Comment by abetlen** [comment]
@teristam thanks for the bug report / solution, I'll update it so `winmode=0`. Are there any side-effects?

**Comment by aneeshjoy** [comment]
The winmod=0 alone did not fix this issue for me. I had add CUDA_PATH to dll dir.  #225
