### ISSUE TITLE
How to set the answer's size (max token size)?

### ISSUE THREAD

**Issue by mikeyang01** [abetlen/llama-cpp-python#211]
currently, to stop the reply we have 
  "stop": [   
   "\n",  "###"
  ]

What I want is, 
like open AI, we have
    max_tokens=50,

like Llama.cpp, we have
  -n N, --n_predict N   number of tokens to predict (default: -1, -1 = infinity)

**Comment by robin-coac** [comment]
```
from llama_cpp import Llama
model = Llama(model_path=model_path,  n_ctx=2048, n_threads=12)

prompt = "### Human: Tell me a joke. ### Assistant:"

output = model( prompt, 
                       max_tokens=50, 
                       stop=["###"], 
                       temperature=0.1,
                       top_p=0.2,
                       top_k=10,
                       repeat_penalty=1,2,
                       )
```

**Comment by robinnarsinghranabhat** [comment]
```
from llama_cpp import Llama
model = Llama(model_path=model_path,  n_ctx=2048, n_threads=12)

prompt = "### Human: Tell me a joke. ### Assistant:"

output = model( prompt, 
                       max_tokens=50, 
                       stop=["###"], 
                       temperature=0.1,
                       top_p=0.2,
                       top_k=10,
                       repeat_penalty=1,2,
                       )
```

**Comment by harryoui** [comment]
`{
  "prompt": "\n\n### Instructions:\nWhat is the capital of France?\n\n### Response:\n",
  "stop": [
    "\n",
    "###"
  ],
  "max_tokens" 200
}`

**Comment by arthurwolf** [comment]
thanks a lot.

**Comment by kirkog86** [comment]
Or edit /usr/local/lib/python3.10/dist-packages/llama_cpp/server/app.py
Line 412

**Comment by dillfrescott** [comment]
This really needs to be a flag on the server cli options. I was fighting with why the output got cut off after ~10 words for forever

**Comment by kirkog86** [comment]
@dillfrescott, yee, I'm 100% agree with you. I was frustrated as well...

**Comment by aahmed-newboxes** [comment]
You can see the value of the 'usage' key in the generated output dict, below the 'text' values.

**Comment by falling-springs** [comment]
Yeah, can we change the default? Seems like this is a pretty common hangup for folks using this package. 

See, e.g., [here](https://github.com/abetlen/llama-cpp-python/issues/542#issuecomment-1694411791).

**Comment by CarloNicolini** [comment]
Importantly, it would be nice to have a None value such that when using Langchain ChatOpenAI one can simply specify None as in the original OpenAI API.
Currently, when setting None, the pydantic validator complains because the number is not an integer.

**Comment by Ryangr0** [comment]
This really needs to be more visible in the API spec. Just wasted 20 minutes looking for this.

**Comment by weissenbacherpwc** [comment]
is it "max_tokens" or "max_new_tokens"?

**Comment by weissenbacherpwc** [comment]
> ```
> from llama_cpp import Llama
> model = Llama(model_path=model_path,  n_ctx=2048, n_threads=12)
> 
> prompt = "### Human: Tell me a joke. ### Assistant:"
> 
> output = model( prompt, 
>                        max_tokens=50, 
>                        stop=["###"], 
>                        temperature=0.1,
>                        top_p=0.2,
>                        top_k=10,
>                        repeat_penalty=1,2,
>                        )
> ```

I am a bit confused with setting the max_tokens. I created my model as follows, so is max_tokens here at the wrong place?:
```
def build_llm():
    # Local CTransformers model
    # for token-wise streaming so you'll see the answer gets generated token by token when Llama is answering your question
        callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])

        n_gpu_layers = 1  # Metal set to 1 is enough.
        n_batch = 512  # Should be between 1 and n_ctx, consider the amount of RAM of your Apple Silicon Chip.
        llm = LlamaCpp(
        model_path=cfg.MODEL_BIN_PATH,
        temperature=0.2,
        f16_kv=True,
        max_tokens = 100,# nur ausprobiert
        n_ctx=8000, # davor 2048
        n_gpu_layers=n_gpu_layers,
        n_batch=n_batch,
        callback_manager=callback_manager, 
        verbose=False, # Verbose is required to pass to the callback manager
        #echo=False,
        #max_new_tokens = 2000,
        top_p=0.75,
        top_k=40,
        repetition_penalty=1.1,
        )
        
        return llm
```

I am using the model in a rag application, so do I have to set max_token here in 'llm = build_llm("MAX_TOKEN_HERE?")
```
qa = RetrievalQA.from_chain_type(llm=build_llm(),
                                 chain_type="stuff",
                                 return_source_documents=True,
                                 chain_type_kwargs=chain_type_kwargs,
                                 retriever=big_chunks_retriever)
```
