### ISSUE TITLE
Quantized Llama 7B not working

### ISSUE THREAD

**Issue by rajdtta** [abetlen/llama-cpp-python#216]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Current + Expected Behavior

I'm trying to run the basic demo shown on the README.

```py
from llama_cpp import Llama
llm = Llama(model_path="./ggml-model-f16.bin")
output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
print(output)
```

Using `ggml-model-f16`, the model runs properly & gives the answer. However, using the quantized version `ggml-model-q4_0` causes an error when trying to run the script.

I've tried downgrading my version of `llama-cpp-python` after seeing the existing/closed issues, but that doesn't seem to have changed anything. I saw something about Llama.cpp changing the quantization format (and how that would break existing frameworks/projects), but I believe this was fixed in #200.

I should also note that the quantized version works with Llama.cpp directly (when ran via CLI), I'm only encountering issues when trying to use the Python wrapper.

# Environment and Context

* Apple M2 Max

* macOS 13/4

* Python 3.10.6

* GNU Make 3.81

* Apple clang version 14.0.3 (clang-1403.0.22.14.1)
* `llama-cpp-python` v0.1.50

* Latest version of Llama.cpp (#63d2046)

# Failure Information (for bugs)

```
llama_model_load: loading model from './ggml-model-q4_0.bin' - please wait ...
llama_model_load: invalid model file './ggml-model-q4_0.bin' (unsupported format version 2, expected 1)
llama_init_from_file: failed to load model
AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
Exception ignored in: <function Llama.__del__ at 0x2b86d7130>
Traceback (most recent call last):
  File "/Users/rajdatta/miniforge3/envs/langchain-sandbox/lib/python3.10/site-packages/llama_cpp/llama.py", line 650, in __del__
    multibyte_fix = 0
AttributeError: 'Llama' object has no attribute 'ctx'
```

# Steps to Reproduce

1. Download the latest versions of Llama.cpp & `llama-cpp-python`
2. Run `convert.py` (in Llama.cpp) to get the f16 version of the model weights
3. Run `quantize.py` (in Llama.cpp) to get the quantized version of the model weights
4. Try running the the Python wrapper's README demo using the 4-bit quantized model weights.

# Failure Logs

```
llama_model_load: loading model from './ggml-model-q4_0.bin' - please wait ...
llama_model_load: invalid model file './ggml-model-q4_0.bin' (unsupported format version 2, expected 1)
llama_init_from_file: failed to load model
AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
Exception ignored in: <function Llama.__del__ at 0x2b86d7130>
Traceback (most recent call last):
  File "/Users/rajdatta/miniforge3/envs/langchain-sandbox/lib/python3.10/site-packages/llama_cpp/llama.py", line 650, in __del__
    multibyte_fix = 0
AttributeError: 'Llama' object has no attribute 'ctx'
```

**Comment by abetlen** [comment]
@rajdtta it looks like your version is compatible with v0.1.50 and later, can you post the original error message you were getting?

**Comment by rajdtta** [comment]
Here's the code block:

```py
from llama_cpp import Llama
llm = Llama(model_path="./ggml-model-q4_0.bin")
output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
print(output)
```

and here's the resulting trace:

```
llama_model_load: loading model from './ggml-model-q4_0.bin' - please wait ...
llama_model_load: invalid model file './ggml-model-q4_0.bin' (unsupported format version 2, expected 1)
llama_init_from_file: failed to load model
AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 |
```

![Trace](https://i.raj.wtf/imgs/3A86WJLkGC358BsgmHSqFtkGVCm.png)

**Comment by abetlen** [comment]
Can you run `pip install --upgrade --force-reinstall --no-cache-dir llama-cpp-python` it looks like it's still on the old version.

**Comment by rajdtta** [comment]
That fixed it! I thought I had run that command earlier, but it looks like I ran it again w/ v0.1.48 specified (which overwrote the latest version).

Thanks for the assistance :)
