### ISSUE TITLE
Failed Building Wheel for llama-cpp-python   runing on Python 3.10.9  windows 10 visual studio 2022

### ISSUE THREAD

**Issue by SLEEP-SOUNDER** [abetlen/llama-cpp-python#233]
``C:\Users\Lenovo>pip install llama-cpp-python
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting llama-cpp-python
  Using cached http://mirrors.aliyun.com/pypi/packages/82/2c/9614ef76422168fde5326095559f271a22b1926185add8ae739901e113b9/llama_cpp_python-0.1.50.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in e:\python\lib\site-packages (from llama-cpp-python) (4.5.0)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [308 lines of output]

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 17 2022

        could not find any instance of Visual Studio.

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 16 2019 x64 v142' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 16 2019

        could not find any instance of Visual Studio.

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 16 2019 x64 v142' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 15 2017 x64 v141)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 15 2017 x64 v141)' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 15 2017 x64 v141' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 15 2017

        could not find any instance of Visual Studio.

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 15 2017 x64 v141' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Running

         'nmake' '-?'

        failed with:

         绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆\x82

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 16 2019 x64 v142)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Running

         'nmake' '-?'

        failed with:

         绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆\x82

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 16 2019 x64 v142)' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 15 2017 x64 v141)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Running

         'nmake' '-?'

        failed with:

         绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆\x82

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 15 2017 x64 v141)' generator - failure
      --------------------------------------------------------------------------------

                      ********************************************************************************
                      scikit-build could not get a working generator for your system. Aborting build.

                      Building windows wheels for Python 3.10 requires Microsoft Visual Studio 2022.
      Get it with "Visual Studio 2017":

        https://visualstudio.microsoft.com/vs/

      Or with "Visual Studio 2019":

          https://visualstudio.microsoft.com/vs/

      Or with "Visual Studio 2022":

          https://visualstudio.microsoft.com/vs/

                      ********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by SLEEP-SOUNDER** [comment]
-

**Comment by trivalik** [comment]
Have you installed "C++-CMake-Tools for Windows" in Visual Studio installer?

**Comment by SLEEP-SOUNDER** [comment]
I just installed "C++-CMake-Tools for Windows" , it can run. tanks

**Comment by SLEEP-SOUNDER** [comment]
can I ask you another question？
After installing llama-cpp-python successfully,I want to install hnswlib, then a similar problem has arisen: error: subprocess-exited-with-error
× Building wheel for hnswlib (pyproject.toml) did not run successfully.
Do you know what’s wrong with it and how to solve it?

**Comment by Nyandaro** [comment]
This coping comment is for me

https://postgresweb.com/python-error-which-is-required-to-install-pyproject-toml-based-projects

https://visualstudio.microsoft.com/en/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

I solved it by following the link above

However, is it strange that it has been working without installing a build tool until now?

**Comment by trivalik** [comment]
It is not strange. I have no cmake.exe on my PC (except in other git repos, which are not on path), but pip install runs cmake.

**Comment by SLEEP-SOUNDER** [comment]
I run it again in PC , run successfully. Thank you.

**Comment by mindwellsolutions** [comment]
Hi, I'm running into the same type of error on Ubuntu Linux. I've installed Visual Studio Build Essentials on linux, updated GCC and Cmake and still get the ERROR: "Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects."

Is there a similar solution on Ubuntu Linux that will resolve this. Really need it fixed. Thanks in advance.

**Comment by SLEEP-SOUNDER** [comment]
Sorry, I'm  a newbie ,didn't know how to slove it on Ubuntu Linux.

**Comment by Nyandaro** [comment]
as a side note
VS was VS2019 not VS2022
Doesn't work on VS2022 but compiled fine on VS2019

The important thing is
MSVC v142 vs2019 c++ x64/x86 build tool
windows 10 SDK
windows C++ CMake tool

I think it's these 3

Be careful matching your VS version lol

**Comment by gjmulder** [comment]
Good info, thanks.

It would be great if we can collect all the different Windows compilation notes and tips in one place and add them to the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md) as a pull request.

Windows is always going to be difficult to support as `llama.cpp` and `python` are really built around Gnu build chains. I've been tagging all Windows issues with the `windows` tag so that we don't lose them.

**Comment by Nyandaro** [comment]
Thank you to everyone involved in the development

It's probably he who caused the problem, llama_cpp_python-0.1.51
So delete it once with "pip uninstall llama-cpp-python"
It is better to newly "pip install llama-cpp-python"
Otherwise, it may not be changed to llama_cpp_python-0.1.52 in the Python folder Especially be careful of downstream applications

**Comment by gjmulder** [comment]
![image](https://github.com/abetlen/llama-cpp-python/assets/10833500/e81d5329-1529-4ed7-9d2e-9768c7513f71)

**Comment by Nyandaro** [comment]
Then i investigated.
I tried with llama cpp python 0.1.55

Downloaded the VS2022 installer.
Uncheck all workloads and select the following in individual components

Windows10 SDK(10.0.20348.0)
MSVC v142 vs2019 c++ x64/x86 build tool(v14.29-16.11)
MSVC v143 vs2022 c++ x64/x86 build tool(new version) ←Absolutely in
windows C++ CMake tool
C++ core functionality

It worked if I just choose this one.

Even if VS2019 installer is removed from the site, it's ok.
If you're on Windows 11, the SDK could be the 11 version.
