### ISSUE TITLE
Push Docker images to Dockerhub using Github actions for running a llama-cpp-python REST server

### ISSUE THREAD

**Issue by gjmulder** [abetlen/llama-cpp-python#236]
A lot of people would like to run their own server, but don't have the necessary DevOps skills to configure and build a `llama-cpp-python + python + llama.cpp` environment.

I'm working on developing some Dockerfiles that are run via a Github action to publish to [Docker Hub](https://hub.docker.com/) similar to [llama.cpp's workflows/docker.yml](https://github.com/ggerganov/llama.cpp/blob/master/.github/workflows/docker.yml) for both OpenBLAS (i.e. no NVidia GPU) and CuBLAS (NVidia GPU via Docker) support.

Which [CC licensed](https://creativecommons.org/licenses/) models are now available that are compatible with `llama.cpp`'s new quantized format? Ideally we want to start with small models to keep the Docker image sizes manageable.

**Comment by gjmulder** [comment]
Looks like [upstream support of Replit + MPT](https://github.com/ggerganov/ggml/pull/145) is maturing with less restrictive licensing:
- [replit-code-v1-3b](https://huggingface.co/replit/replit-code-v1-3b) is: CC BY-SA-4.0
- [MPT-7B-StoryWriter-65k+](https://huggingface.co/mosaicml/mpt-7b-storywriter) is: Apache 2.0
- [MPT-7B-Instruct](https://huggingface.co/mosaicml/mpt-7b-instruct) is: CC-By-SA-3.0
- [MPT-7B-Chat](https://huggingface.co/mosaicml/mpt-7b-chat) is: CC-By-NC-SA-4.0

**Comment by jmtatsch** [comment]
While in principle a great idea this will be a support nightmare. 

The problem is that the binaries of llama.cpp are so optimized to using every possible acceleration feature that they will not run on the many different hardware architectures (especially the older ones which non power users are likely to have).
It will segfault then with a non-descriptive error message and people will be crying in the issues 😉
When building without those acceleration features it will become unusable slow.

**Comment by gjmulder** [comment]
> It will segfault then with a non-descriptive error message and people will be crying in the issues

@jmtatsch better forewarned than snowed in issues, thx. How about if the images require a `docker build` against whatever Docker exposes in terms of local hardware, but come pre-loaded with models?

**Comment by jmtatsch** [comment]
Yes, that would solve the issue and the model can be downloaded within the build from huggingface.

**Comment by gjmulder** [comment]
#270 does most of the heavy lifting. Seems like people are already pushing images to Docker Hub and running into "illegal instructions" due to AVX, etc.

**Comment by gjmulder** [comment]
`FORCE_CMAKE=1  CMAKE_ARGS="-DLLAMA_AVX2=OFF -DLLAMA_AVX512=OFF -DAVX512_VBMI=OFF -AVX512_VNNI=OFF -DFMA=ON -DF16C=ON -DLLAMA_OPENBLAS=ON` might be a crippled enough to work for most people.

**Comment by gjmulder** [comment]
And we now have [open llama](https://github.com/openlm-research/open_llama) w/Apache License Version 2.0

**Comment by gjmulder** [comment]
#310 automates the process of downloading an Apache 2.0 licensed Open Llama 3B model and installing it into a minimal Debian image with an OpenBLAS enabled server.

**Comment by gjmulder** [comment]
So, after a lot of trial and error it seems that forcing CMAKE Intel acceleration flags into a Docker file is a [PITA](https://en.wiktionary.org/wiki/pain_in_the_ass).
