### ISSUE TITLE
Attention weights visualization

### ISSUE THREAD

**Issue by watashiwa-toki** [abetlen/llama-cpp-python#237]
Could you add a visualization of attention weights? Thanks.

**Comment by abetlen** [comment]
![image](https://github.com/abetlen/llama-cpp-python/assets/6826477/5e86e940-b8d1-4615-b415-e46ea76ed2d7)

Do you mean visualising the token probabilities like this?

**Comment by watashiwa-toki** [comment]
> ![image](https://user-images.githubusercontent.com/6826477/239455401-5e86e940-b8d1-4615-b415-e46ea76ed2d7.png)
> 
> Do you mean visualising the token probabilities like this?

Yes. Is it possible? Ideally - possibility to use BertViz https://github.com/jessevig/bertviz for LLaMA and derived models.

**Comment by abetlen** [comment]
That example should work with the v0.1.51 that I just pushed.

Steps:
1. Install llama-cpp-python >= v0.1.51
2. Start the web server with `--model_alias text-davinci-003`
3. Start the openplayground through docker `docker run --rm -e OPENAI_API_KEY=sk-xxx -e OPENAI_API_BASE=http://100.64.159.73:8000/v1 -p 5432:5432 natorg/openplayground` and replace the IP address there with your local ip address of the llama-cpp-python web server
4. Go to `http://localhost:5432` in your web browser and use the "openai" model that we just created.

**Comment by watashiwa-toki** [comment]
> That example should work with the v0.1.51 that I just pushed.
> 
> Steps:
> 
> 1. Install llama-cpp-python >= v0.1.51
> 2. Start the web server with `--model_alias text-davinci-003`
> 3. Start the openplayground through docker `docker run --rm -e OPENAI_API_KEY=sk-xxx -e OPENAI_API_BASE=http://100.64.159.73:8000/v1 -p 5432:5432 natorg/openplayground` and replace the IP address there with your local ip address of the llama-cpp-python web server
> 4. Go to `http://localhost:5432` in your web browser and use the "openai" model that we just created.

This works only with OpenAI models?

**Comment by abetlen** [comment]
@watashiwa-toki the webserver is a drop-in replacement for the openai api, essentially it let's you use llama.cpp models anywhere you would use the openai api by just routing to your local server. I'm not sure about the BertViz project you linked, that may requiire some additional work to visualize.

**Comment by watashiwa-toki** [comment]
Run server with:
`python3 -m llama_cpp.server --model /home/canterel/lm/llama.bin --model_alias text-davinci-003`
and docker:
`docker run --rm -e OPENAI_API_KEY=sk-xxx -e OPENAI_API_BASE=http://localhost:8000/v1 -p 5432:5432 natorg/openplayground`
then open http://localhost:5432 in browser, select text-davinci-003, submit text. Get an error:
```
Model Error
OpenAI API request failed to connect: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f676662f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by jmtatsch** [comment]
Look at your ports. If you access your server inside the container at port 8000 you need to map at least 8000:5432

**Comment by iBibek** [comment]
@watashiwa-toki Hello, were you able to visualize the attentions? i
