### ISSUE TITLE
warning: failed to mlock NNNNNN-byte buffer (after previously locking 0 bytes): Cannot allocate memory

### ISSUE THREAD

**Issue by AnonymousAmalgrams** [abetlen/llama-cpp-python#254]
I'm getting the following output when running the web server from the git clone:

```
llama.cpp: loading model from ./vendor/llama.cpp/models/7B/ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v2 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size = 4017.34 MB
llama_model_load_internal: mem required  = 5809.34 MB (+ 17592185987986.00 MB per state)
warning: failed to mlock 4212486144-byte buffer (after previously locking 0 bytes): Cannot allocate memory
Try increasing RLIMIT_MLOCK ('ulimit -l' as root).
```

I manually built the libllama.so file and dumped it into the directory where it checks for it. I tried building it both following #30 and also with make libllama.so, both maybe as expected give the same result. However oddly enough, the pip install seems to work fine (not sure what it's doing differently) and gives the same "normal" ctx size (around 70KB) as running the model directly within vendor/llama.cpp and the -n 128 suggested for testing. Any suggestions for how to get a working libllama.so would be greatly appreciated.

**Comment by gjmulder** [comment]
Is this an enhancement request?

Working fine with a 13B model and a 11GB GPU. Increasing `n_ctx` increases the memory requirements noticeably:
```
llama_model_load_internal: format     = ggjt v2 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 8196
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  90.75 KB
llama_model_load_internal: mem required  = 11359.05 MB (+ 1608.00 MB per state)
....................................................................................................
llama_model_load_internal: [cublas] offloading 40 layers to GPU
llama_model_load_internal: [cublas] offloading output layer to GPU
llama_model_load_internal: [cublas] total VRAM used: 9192 MB
llama_init_from_file: kv self size  = 6403.12 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 
```0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |

**Comment by gjmulder** [comment]
Ahh, saw the error. Here's the fix, which is not directly related to `n_ctx`. With `mlock` enabled you are hitting the default `mlock` memory limits for your Linux distro. Here's a fix:

`ulimit -l unlimited && python3 main.py`

There is a system-wide `ulimit.conf` file which varies in location depending on the distro.

**Comment by gjmulder** [comment]
#171

**Comment by AnonymousAmalgrams** [comment]
> Ahh, saw the error. If you format your screen output and refer to the actual error in your issue description as per the template it helps people understand your issue easier.
> 
> Here's the fix, which is not directly related to `n_ctx`. With `mlock` enabled you are hitting the default `mlock` memory limits for your Linux distro:
> 
> `ulimit -l unlimited && python3 llama_cpp.server`
> 
> There is a system-wide `ulimit.conf` file which varies in location depending on the distro.

In the issue mentioned, they pasted an image of the output and still have a ctx of around 70KB and a correspondingly much smaller mem required than “+ 17592185987986.00 MB per state”. It lines up with what I observed running the llama.cpp version on its own vs the parameters that were somehow saved into the .so. If I’m interpreting that correctly I don’t think I would ever be able to get enough memory to run this even if I disabled mlock with those requirements, and worry for my computer if I tried 😅.

**Comment by gjmulder** [comment]
> In the issue mentioned, they pasted an image of the output and still have a ctx of around 70KB and a correspondingly much smaller mem required than “+ 17592185987986.00 MB per state”. It lines up with what I observed running the llama.cpp version on its own vs the parameters that were somehow saved into the .so. If I’m interpreting that correctly I don’t think I would ever be able to get enough memory to run this even if I disabled mlock with those requirements, and worry for my computer if I trie

17592185987986.00 MB (17.6 exabytes) is clearly a bug. `mlock` just forces the memory allocated to `lllama.cpp` to not be swapped out. This is approx. how much memory you need:

| Model | Original size | Quantized size (4-bit) |
|------:|--------------:|-----------------------:|
|    7B |         13 GB |                 4GB |
|   13B |         24 GB |                 8 GB |
|   30B |         60 GB |                20GB |
|   65B |        120 GB |                39 GB |

From [llama.ccp CPU memory / disk reqs](https://github.com/ggerganov/llama.cpp#memorydisk-requirements)

You can adjust `n_gpu_layers` to fill your GPU with as many layers as you have VRAM available.

**Comment by AnonymousAmalgrams** [comment]
Thanks, so as I understand it the n_gpu_layers will limit the amount of swap used to the associated VRAM amount? Just trying to make sure I'm not about to blow anything out.

**Comment by AnonymousAmalgrams** [comment]
> > In the issue mentioned, they pasted an image of the output and still have a ctx of around 70KB and a correspondingly much smaller mem required than “+ 17592185987986.00 MB per state”. It lines up with what I observed running the llama.cpp version on its own vs the parameters that were somehow saved into the .so. If I’m interpreting that correctly I don’t think I would ever be able to get enough memory to run this even if I disabled mlock with those requirements, and worry for my computer if I trie
> 
> 17592185987986.00 MB (17.6 exabytes) is clearly a bug. `mlock` just forces the memory allocated to `lllama.cpp` to not be swapped out. This is approx. how much memory you need:
> 
> Model	Original size	Quantized size (4-bit)
> 7B	13 GB	4 GB
> 13B	24 GB	8 GB
> 30B	60 GB	20 GB
> 65B	120 GB	39 GB
> From [llama.ccp CPU memory / disk reqs](https://github.com/ggerganov/llama.cpp#memorydisk-requirements)
> 
> You can adjust `n_gpu_layers` to fill your GPU with as many layers as you have VRAM available.

Actually now that I think of it though, isn't it kind of odd that swap is not needed in some cases then? I ran all testing on the same system, so my impression is that the same swap limits would be imposed.

**Comment by gjmulder** [comment]
Generally you don't want the OS to swap the model out, but it may try to given the large memory footprint. `mlock` can be used to explicitly request the OS not to swap it out. On a Linux Mint system I saw the stupid `OOM Killer` preemptively killing `llama.cpp`, even though the system had enough physical RAM.

The VRAM usage is AFAIK independent of the mlock behaviour. In my experience the `n_ctx` size uses a set amount of VRAM. Whatever is left over can be allocated to `n_gpu_layers`. You'll want to leave some MB free for minor VRAM growth, although #223 indicates that there's a bug in `llama.cpp` where VRAM isn't freed even if you force `python` to garbage collect the model instance.

**Comment by gdedrouas** [comment]
llama_context struct changed in llama.cpp, updating your llama-cpp-python to current main should fix it.

**Comment by AnonymousAmalgrams** [comment]
Okay, I managed to get it working now. Thanks again!

**Comment by pavelklymenko** [comment]
> Okay, I managed to get it working now. Thanks again!

@AnonymousAmalgrams  What did you do?

**Comment by AnonymousAmalgrams** [comment]
I just updated the repo… but there are probably a lot of other random things that can cause this problem.

**Comment by br00t4c** [comment]
On Ubuntu 24:

`sudo nano /etc/security/limits.conf`

Add a line:

`your-username   -   memlock   unlimited`

Log out and log back in, executed `ulimit -l` and `ulimit -r` to confirm the changes have been applied. 

I can't vouch for what this will or will not do to the stability of your system but it will allow you to memlock any and all available RAM
