### ISSUE TITLE
Add performance optimization example

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#26]
I've had some success using `scikit-optimize` to tune the parameters for the `Llama` class, can improve token eval performance by around ~50% from just the default parameters. Planning to turn this into a script, it could also be of some use for upstream `llama.cpp` users.

![image](https://user-images.githubusercontent.com/6826477/230012740-e9a723a6-b6eb-46fd-83bc-ae221cb9b1ec.png)

**Comment by MillionthOdin16** [comment]
Dang super cool!

**Comment by abetlen** [comment]
Thanks! I've added it to the examples in a notebooks folder if you want to try it out (and re-organized the examples a litte bit). You'll need numpy, matplotlib, and scikit-optimize to run it.

https://github.com/abetlen/llama-cpp-python/blob/main/examples/notebooks/PerformanceTuning.ipynb

**Comment by agreenbhm** [comment]
@abetlen - sorry for the dumb question, but after running the notebook how do I go about interpreting the results and applying them?  The graphs are not clear to me (probably because I'm missing something obvious). Thanks!

**Comment by abetlen** [comment]
@agreenbhm the result object returned by scikit-optimize has an `x` member that stores the "best" run the order of parameters is identical to the `space` definition:
```
space = [
    Categorical([True, False], name="f16_kv"),
    Categorical([True, False], name="use_mlock"),
    Integer(1, multiprocessing.cpu_count(), name="n_threads"),
    Integer(1, 2048, name="n_batch")
]
```

**Comment by agreenbhm** [comment]
Thank you very much for the reply @abetlen!

**Comment by vmajor** [comment]
@abetlen How do I set the optimal parameters at server runtime? Is this the correct syntax to set the x for my system:
x =  [False, False, 19, 2048]



python3 -m llama_cpp.server --model models/gpt4-alpaca-lora_mlp-65B/gpt4-alpaca-lora_mlp-65B.ggmlv3.q5_1.bin --f16_kv False --use_mlock False --n_threads 19 --n_batch 2048
