### ISSUE TITLE
'LlamaCppModel' object has no attribute 'model'

### ISSUE THREAD

**Issue by valdesguefa** [abetlen/llama-cpp-python#261]
please i need help 
llama.cpp: loading model from models/ggml-old-vic13b-q4_2.bin
error loading model: unrecognized tensor type 4

llama_init_from_file: failed to load model
Exception ignored in: <function LlamaCppModel.__del__ at 0x7f433a5b13f0>
Traceback (most recent call last):
  File "/mnt/f/text-generation-webui/modules/llamacpp_model.py", line 23, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'

**Comment by gjmulder** [comment]
If you need help please review the issue template and document your environment, code, and problem.

**Comment by valdesguefa** [comment]
i use wsl2 and that is my code.

from llama_cpp import Llama
PATH = "/mnt/f/AI_and_data/oobabooga_windows/text-generation-webui/models/ggml-vicuna-13b-4bit.bin"
llm = Llama(
    model_path=PATH)
output = llm("Q: Donne les planetes du systeme solaire? R: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
print(output)

**Comment by gjmulder** [comment]
[bug_report.md](https://github.com/abetlen/llama-cpp-python/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
