### ISSUE TITLE
Developer installation failing

### ISSUE THREAD

**Issue by Huge** [abetlen/llama-cpp-python#273]
# Prerequisites

# Expected Behavior

`python3 setup.py develop` completes( in my .venv)

# Current Behavior

```
Traceback (most recent call last):
  File "/Users/admin/prog/llama-cpp-python/setup.py", line 1, in <module>
    from skbuild import setup
ModuleNotFoundError: No module named 'skbuild'
```

# Environment and Context

Update: I suppose this is someting about the **conda** python is used. I also get stuck with:
`pip install llama-cpp-python[server]`
`zsh: no matches found: llama-cpp-python[server]`

and `pip install skbuild && python3 setup.py develop` also fails:
```
ERROR: Could not find a version that satisfies the requirement skbuild (from versions: none)
ERROR: No matching distribution found for skbuild
```

```
which python
/opt/homebrew/Caskroom/miniforge/base/bin/python```

**Comment by mvrozanti** [comment]
I'm getting the same error. `pip install scikit-build` didn't help.

**Comment by mvrozanti** [comment]
Ohhh but it was a python version mismatch. I got it working now. Try calling pip through the python version that you intend to run llama-cpp-python on. e.g.: `python3.11 -m -pip scikit-build`

**Comment by gjmulder** [comment]
Can this issue be closed then?

**Comment by AdityaSher** [comment]
I am still facing this issue, 
`>>>pip install llama-cpp-python[server]`
`zsh: no matches found: llama-cpp-python[server]`

can anyone help?

**Comment by gjmulder** [comment]
Try:

`pip install llama-cpp-python`

**Comment by AdityaSher** [comment]
Worked, I realized I do not need to install [server] seperately, the server code is bundled in the library, thanks @gjmulder !

**Comment by sacada-fish** [comment]
I have the same problem. 
zsh: no matches found: llama-cpp-python[server]

**Comment by oliver-was-here** [comment]
@sacada-fish if you're using zsh, the command you want to run is `pip install 'llama-cpp-python[server]'`

see [here](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity) for more info

**Comment by AbrahimZaman360** [comment]
"litestar[standard]" or 'litestar[standard]'

**Comment by Huge** [comment]
Thanks, my bad for using something cool looking that i do not know what syntactic differences from good old bash it has.-)

**Comment by psahni** [comment]
> [@sacada-fish](https://github.com/sacada-fish) if you're using zsh, the command you want to run is `pip install 'llama-cpp-python[server]'`
> 
> see [here](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity) for more info

You are a MEN
