### ISSUE TITLE
The latest version of llama.cpp is not running on my system, can I have llama-cpp-python use a specific commit/version of it?

### ISSUE THREAD

**Issue by mvrozanti** [abetlen/llama-cpp-python#275]
**Is your feature request related to a problem? Please describe.**
It's more of a question, of whether we can choose which llama.cpp version to build. llama.cpp does work when I build an older version. I don't know if it's relevant as it's on their repo, but I think I have [this same issue](https://github.com/ggerganov/llama.cpp/issues/1569)

**Describe the solution you'd like**
I have no idea where to put this option, but I think there could be _an_ option to choose llama.cpp version.

**Comment by gjmulder** [comment]
That's not quite how things work, AFAIK:

If you install a particular version of `llama-cpp-python` you install a corresponding version of [llama.cpp](https://github.com/ggerganov/llama.cpp) that is _verified_ to work with `llama-cpp-python`. These versions are linked and should not be changed.

What you are requesting is that a new `llama-cpp-python` version includes a fix for [llama.cpp issue 1569](https://github.com/ggerganov/llama.cpp/issues/1569). This would require:

1. A pull request fixing [llama.cpp issue #1569](https://github.com/ggerganov/llama.cpp/issues/1569) in `llama.cpp`, which doesn't look to have occurred
2. A pull request for a new `llama-cpp-python` version that includes the upstream fix to `llama.cpp` (when it is fixed)

**Comment by mvrozanti** [comment]
Hi @gjmulder, thanks for the quick reply and the explanation. I understand how the versions are linked now. I'm going to try and use an older version of llama-cpp-python and report back in a moment. Having said that I don't really see this as a bug on llama-cpp-python side anymore, I'm not sure if this issue has any merit staying opened.

**Comment by mvrozanti** [comment]
I ended up just installing v0.1.50 through pip and it works like a charm!
