### ISSUE TITLE
Add CHANGELOG or Release notes

### ISSUE THREAD

**Issue by gaby** [abetlen/llama-cpp-python#281]
Currently there's no way to know what new features are in this project. When creating a new release and adding a tag a button to the right on github will auto-generate release notes.

Thanks

**Comment by abetlen** [comment]
Thanks @gaby will do that for future releases, I've just commited the first version of a changelog to the repo (nothing there yet). It's probably too much work to go back through old releases but I wouldn't be opposed if someone did do that for key changes / past releases in a PR.

**Comment by gaby** [comment]
Thanks! It's fine to do it from now on, no need to update the old ones at this point

**Comment by gaby** [comment]
@abetlen Found the perfect tool to make your life easier.

https://github.com/github-changelog-generator/github-changelog-generator
