### ISSUE TITLE
Add docs example for setting up OpenLlama model

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#283]
Weights for OpenLlama are available under a permissive license so no risk of repo takedown from sharing them, I've had a chance to test the quantized 700b token checkpoint from https://huggingface.co/vihangd/open_llama_7b_700bt_ggml and it works well with llama-cpp-python. Should consider adding a download link in the README.

**Comment by gjmulder** [comment]
I'll work on including it in the Docker "bot-in-a-box" as the default option.
