### ISSUE TITLE
OSError: [WinError -529697949] Windows Error 0xe06d7363

### ISSUE THREAD

**Issue by subhu1996** [abetlen/llama-cpp-python#288]
```
Traceback (most recent call last):
  File "d:\AI\Vivy\test.py", line 57, in <module>
    llm = Llama(model_path=".\\models\\ggml-model-q4_0.bin")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sksub\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llama.py", line 186, in __init__
    self.ctx = llama_cpp.llama_init_from_file(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sksub\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llama_cpp.py", line 262, in llama_init_from_file
    return _lib.llama_init_from_file(path_model, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError -529697949] Windows Error 0xe06d7363
Exception ignored in: <function Llama.__del__ at 0x000001D9523A0C20>
Traceback (most recent call last):
  File "C:\Users\sksub\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llama.py", line 1309, in __del__
    if self.ctx is not None:
       ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'
```

**Comment by gjmulder** [comment]
It would help if you followed the instructions in the issue template. I'm guessing the path to your model is wrong.

**Comment by graylan0** [comment]
i ran this on two machines ,exactly the same. model path correct same error.

the first machine (win10) worked fine. 2nd machine. didn't work , gave this error. model path is correct. so either A>envriomental change. or B upstream was broken with i installed pip.

**Comment by zhiyixu** [comment]
@graylan0 have you solve this problem yet?

**Comment by gjmulder** [comment]
So from a number of reports this could be a model versioning error. If you're installing the latest `llama-cpp-python` via `pip` you should try to use a `ggml v3` model.

You can try and use this script to find one on [HuggingFace](https://huggingface.co/models), although it hasn't been tested on Windows, sorry:

[hug_model.py](https://github.com/abetlen/llama-cpp-python/blob/main/docker/open_llama/hug_model.py)

**Comment by gjmulder** [comment]
Let's hope #316 can solve this issue.
