### ISSUE TITLE
Mac M1 import of LLama leads to error "incompatible architecture (have 'x86_64', need 'arm64'))"

### ISSUE THREAD

**Issue by tleers** [abetlen/llama-cpp-python#291]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Trying to import the library and then use it.
```python
from llama_cpp import Llama
```

# Current Behavior

Unable to import the library without running into an error:

> 
> Traceback (most recent call last):
> File "/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/llama_cpp.py", line 60, in _load_shared_library
> return ctypes.CDLL(str(_lib_path), **cdll_args)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/init.py", line 376, in init
> self._handle = _dlopen(self._name, mode)
> ^^^^^^^^^^^^^^^^^^^^^^^^^
> OSError: dlopen(/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/libllama.so, 0x0006): tried: '/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/libllama.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/libllama.so' (no such file), '/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/libllama.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> File "/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/init.py", line 1, in <module>
> from .llama_cpp import *
> File "/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/llama_cpp.py", line 73, in <module>
> _lib = _load_shared_library(_lib_base_name)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/llama_cpp.py", line 62, in _load_shared_library
> raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
> RuntimeError: Failed to load shared library '/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/libllama.so': dlopen(/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/libllama.so, 0x0006): tried: '/Users/tleers/Projects/personal/LLM-API-StarterKit/dependencies/llama-cpp-python/llama_cpp/libllama.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System

# Environment and Context

Mac M1 with Python 3.11.3 and GNU Make 3.81

# Failure Information (for bugs)

Already tried all of the potential fixes at #5 without any changes in error output.
ggerganov's LLama.cpp compilation and usage works just fine without any errors.

# Steps to Reproduce

1. `python3 -m venv venv & . venv/bin/activate`
2. `pip install llama-cpp-python`
3. `python`
4. `from llama_cpp import LLama`

**Comment by gjmulder** [comment]
Can you `llama-cpp-python` and install from source? While this likely won't fix the issue you now have `llama.cpp` in `./vendor/llama.cpp` and can see if a `cmake` of that `llama.cpp` reproduces the same problem.

**Comment by tleers** [comment]
Followed these steps:
1. cloned llama.cpp repo into vendor
2. ran python setup.py develop in llama-cpp-python

Same error.

Using cmake in the llama.cpp folder succeeds in building. I can also successfully run models using the built llama.cpp binaries: `./main -m ./../../../wizardLM-7B.ggmlv3.q4_0.bin -p "Building a website can be done in 10 simple steps:" -n 128`

In conclusion, the cmake does not lead to the same error.

**Comment by gjmulder** [comment]
If MacOS has the command `file`, you may want to run it against `libllama.so` and `main` to see if they're `x86_64` or `arm64`.

As I don't have a Mac, this is pure guesswork, but it is possible your _python_ is `arm64`, so it refuses to load a `x86_64` `libllama.so`

**Comment by gjmulder** [comment]
Is this working now with the latest `llama.cpp`?

**Comment by gjmulder** [comment]
Please reopen if this issue is still occuring

**Comment by muzhig** [comment]
I can confirm it's still happening

**Comment by Diniden** [comment]
@muzhig I was having your exact error and came across this thread and only sad to find no answer. So, here I am to help document a fix and how to figure out the problem here, as I was able to correct this malady.

The underlying issue is there is SOME TOOL/PROGRAM that is running in x86. This could be your python installation all the way down to cmake or clang. When one of these tools runs in this mode it can mask the architecture when triggering the build steps.

For python: just have your activity monitor open while running any of the steps you are performing and have a search for python in place. Ensure the "Kind" column always says "Apple" and never "intel"

For your other tools you can do a similar approach to see if anything intel gets fired up. Or if you are lucky, sort all your processes by "Kind" and see if any Intel shows up. From which you can see if the process triggers in a non arm64 arch.

Now, for the build tools you have clang and cmake. I fixed all this up by using homebrew (and MAKING SURE I am using the arm64 homebrew...there is STILL an x86 homebrew that floats around so please look up those instructions on making sure you are running the correct homebrew)

Next, we ensure homebrew arm edition installs are being used when we run our build tools. I did an explicit addition to my .bash_profile:

```
export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH
```

Now we KNOW our arm installs will be the ones used in subsequent commands. Next:

```
brew install llvm
brew install cmake
```

Now we are assured the correct build tools get used. This is my values for which checks:

```
which clang
# /usr/bin/clang

which cmake
/opt/homebrew/bin/cmake
```

When that looks all good, you are probably hitting all the correct tools and your build should work fine.

Figuring out the environments is a wild ride with rosetta. Be aware anything that jumps to rosetta can really mess up build processes and is a bit of a pain to unravel.

Hope this helps!

**Comment by guanyuwl** [comment]
> @muzhig I was having your exact error and came across this thread and only sad to find no answer. So, here I am to help document a fix and show how to figure out the problem here, as I was able to correct this malady.
> 
> The underlying issue: there is SOME TOOL/PROGRAM that is running in x86. This could be your python installation all the way down to cmake or clang. When one of these tools runs in this mode it can mask the architecture when triggering the build steps.
> 
> For python: just have your activity monitor open while running any of the steps you are performing and have a search for python in place. Ensure the "Kind" column always says "Apple" and never "intel"
> 
> For your other tools you can do a similar approach to see if anything intel gets fired up. Or if you are lucky, sort all your processes by "Kind" and see if any Intel shows up. From which you can see if the process triggers in a non arm64 arch.
> 
> Now, for the build tools you have clang and cmake. I fixed all this up by using homebrew (and MAKING SURE I am using the arm64 homebrew...there is STILL an x86 homebrew that floats around so please look up those instructions on making sure you are running the correct homebrew)
> 
> Next, we ensure homebrew arm edition installs are being used when we run our build tools. I did an explicit addition to my .bash_profile:
> 
> ```
> export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH
> ```
> 
> Now we KNOW our arm installs will be the ones used in subsequent commands. Next:
> 
> ```
> brew install llvm
> brew install cmake
> ```
> 
> Now we are assured the correct build tools get used. This is my values for which checks:
> 
> ```
> which clang
> # /usr/bin/clang
> 
> which cmake
> /opt/homebrew/bin/cmake
> ```
> 
> When that looks all good, you are probably hitting all the correct tools and your build should work fine.
> 
> Figuring out the environments is a wild ride with rosetta. Be aware anything that jumps to rosetta can really mess up build processes and is a bit of a pain to unravel.
> 
> Hope this helps!

This is useful for me，tks！
