### ISSUE TITLE
error: inlining failed in call to ‘always_inline’

### ISSUE THREAD

**Issue by owenmarinas** [abetlen/llama-cpp-python#299]
# Expected Behavior
`pip install -v llama-cpp-python --no-cache-dir  `

# Current Behavior
```  make: *** [Makefile:201: ggml.o] Error 1
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/tmp/pip-build-env-hkshnlz_/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 674, in setup
      cmkr.make(make_args, install_target=cmake_install_target, env=env)
    File "/tmp/pip-build-env-hkshnlz_/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 697, in make
      self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
    File "/tmp/pip-build-env-hkshnlz_/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 742, in make_impl
      raise SKBuildError(msg)

  An error occurred while building with CMake.
    Command:
      /tmp/pip-build-env-hkshnlz_/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake --build . --target install --config Release --
    Install target:
      install
    Source directory:
      /tmp/pip-install-7cyvk1zz/llama-cpp-python_ae4aa3cd77d3469da07849c426f3d492
    Working directory:
      /tmp/pip-install-7cyvk1zz/llama-cpp-python_ae4aa3cd77d3469da07849c426f3d492/_skbuild/linux-x86_64-3.10/cmake-build
  Please check the install target is valid and see CMake's output for more information.
  error: subprocess-exited-with-error
    × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
    note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpfbvfkst5
  cwd: /tmp/pip-install-7cyvk1zz/llama-cpp-python_ae4aa3cd77d3469da07849c426f3d492
  Building wheel for llama-cpp-python (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects`
```
# Environment and Context

```lscpu 
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    CPU family:          6
    Model:               142
    Thread(s) per core:  1
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            12
    BogoMIPS:            4608.00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpui
                         d tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 inv
                         pcid rdseed clflushopt md_clear flush_l1d arch_capabilities
Virtualization features: 
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):     
  L1d:                   128 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    1 MiB (4 instances)
  L3:                    32 MiB (4 instances)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:         
  Itlb multihit:         KVM: Mitigation: VMX unsupported
  L1tf:                  Mitigation; PTE Inversion
  Mds:                   Mitigation; Clear CPU buffers; SMT Host state unknown
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Mitigation; Clear CPU buffers; SMT Host state unknown
  Retbleed:              Vulnerable
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Unknown: Dependent on hypervisor status
  Tsx async abort:       Not affected`
```
```Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
Linux Ubuntu  5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

vagrant@privategpt:~$ id
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),110(lxd)
```

```
Python 3.10.6
GNU Make 4.3
Built for x86_64-pc-linux-gnu
g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
```

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.
```
  sudo apt update && sudo apt upgrade -y
  sudo apt install -y python3-pip build-essential g++ clang cmake libxml2-dev libxmlsec1-dev
  pip install -v llama-cpp-python --no-cache-dir  > allout.log 2>&1
```
# Failure Logs
[allout.log.gz](https://github.com/abetlen/llama-cpp-python/files/11599948/allout.log.gz)

<details>

```
vagrant@privategpt:~$ pip list
Package                Version
---------------------- -------------
attrs                  21.2.0
Automat                20.2.0
Babel                  2.8.0
bcrypt                 3.2.0
blinker                1.4
certifi                2020.6.20
chardet                4.0.0
click                  8.0.3
cloud-init             23.1.2
colorama               0.4.4
configobj              5.0.6
constantly             15.1.0
cryptography           3.4.8
dbus-python            1.2.18
distro                 1.7.0
httplib2               0.20.2
hyperlink              21.0.0
idna                   3.3
importlib-metadata     4.6.4
incremental            21.3.0
jeepney                0.7.1
Jinja2                 3.0.3
jsonpatch              1.32
jsonpointer            2.0
jsonschema             3.2.0
keyring                23.5.0
launchpadlib           1.10.16
lazr.restfulclient     0.14.4
lazr.uri               1.0.6
MarkupSafe             2.0.1
more-itertools         8.10.0
netifaces              0.11.0
oauthlib               3.2.0
pexpect                4.8.0
pip                    22.0.2
ptyprocess             0.7.0
pyasn1                 0.4.8
pyasn1-modules         0.2.1
Pygments               2.11.2
PyGObject              3.42.1
PyHamcrest             2.0.2
PyJWT                  2.3.0
pyOpenSSL              21.0.0
pyparsing              2.4.7
pyrsistent             0.18.1
pyserial               3.5
python-apt             2.4.0+ubuntu1
python-magic           0.4.24
pytz                   2022.1
PyYAML                 5.4.1
requests               2.25.1
SecretStorage          3.3.1
service-identity       18.1.0
setuptools             59.6.0
six                    1.16.0
sos                    4.4
ssh-import-id          5.11
systemd-python         234
Twisted                22.1.0
ubuntu-advantage-tools 8001
ufw                    0.36.1
urllib3                1.26.5
wadllib                1.3.6
wheel                  0.37.1
zipp                   1.0.0
zope.interface         5.4.0
```
</details>

**Comment by gjmulder** [comment]
Is there a cmake log file in `/tmp/pip-install-7cyvk1zz/llama-cpp-python_ae4aa3cd77d3469da07849c426f3d492/_skbuild/linux-x86_64-3.10/cmake-build`?

**Comment by owenmarinas** [comment]
all the directories under `/tmp/` are deleted quickly after.
I did `tar` them in another ssh session but there is no log.
[tree.log.gz](https://github.com/abetlen/llama-cpp-python/files/11601345/tree.log.gz)

**Comment by gjmulder** [comment]
Was there an error before `ninja: build stopped: subcommand failed.`?

**Comment by owenmarinas** [comment]
`Configuring Project
    Working directory:
      /tmp/pip-install-t24bt2kn/llama-cpp-python_38e362989f3b4e50bfea85febde41391/_skbuild/linux-x86_64-3.10/cmake-build
    Command:
      /tmp/pip-build-env-o0vf_ayl/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake /tmp/pip-install-t24bt2kn/llama-cpp-python_38e362989f3b4e50bfea85febde41391 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-o0vf_ayl/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-t24bt2kn/llama-cpp-python_38e362989f3b4e50bfea85febde41391/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.6 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-o0vf_ayl/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.10.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-o0vf_ayl/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release

  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 11.3.0
  -- The CXX compiler identification is GNU 11.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done (0.3s)
  -- Generating done (0.0s)
  -- Build files have been written to: /tmp/pip-install-t24bt2kn/llama-cpp-python_38e362989f3b4e50bfea85febde41391/_skbuild/linux-x86_64-3.10/cmake-build
  [1/2] Generating /tmp/pip-install-t24bt2kn/llama-cpp-python_38e362989f3b4e50bfea85febde41391/vendor/llama.cpp/libllama.so
  FAILED: /tmp/pip-install-t24bt2kn/llama-cpp-python_38e362989f3b4e50bfea85febde41391/vendor/llama.cpp/libllama.so
  cd /tmp/pip-install-t24bt2kn/llama-cpp-python_38e362989f3b4e50bfea85febde41391/vendor/llama.cpp && make libllama.so
  I llama.cpp build info:
  I UNAME_S:  Linux
  I UNAME_P:  x86_64
  I UNAME_M:  x86_64
  I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native
  I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native
  I LDFLAGS:
  I CC:       cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  I CXX:      g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0

  g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -c llama.cpp -o llama.o
  cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native   -c ggml.c -o ggml.o
  In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:99,
                   from ggml.c:189:
  ggml.c: In function ‘ggml_vec_dot_q4_0_q8_0’:
  /usr/lib/gcc/x86_64-linux-gnu/11/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
     63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
        | ^~~~~~~~~~~~~~~
  ggml.c:2262:15: note: called from here
   2262 |         acc = _mm256_fmadd_ps( d, q, acc );
        |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:99,
                   from ggml.c:189:
  /usr/lib/gcc/x86_64-linux-gnu/11/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
     63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
        | ^~~~~~~~~~~~~~~
  ggml.c:2262:15: note: called from here
   2262 |         acc = _mm256_fmadd_ps( d, q, acc );
        |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:99,
                   from ggml.c:189:
  /usr/lib/gcc/x86_64-linux-gnu/11/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
     63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
        | ^~~~~~~~~~~~~~~
  ggml.c:2262:15: note: called from here
   2262 |         acc = _mm256_fmadd_ps( d, q, acc );
        |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:99,
                   from ggml.c:189:
  /usr/lib/gcc/x86_64-linux-gnu/11/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_fmadd_ps’: target specific option mismatch
     63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
        | ^~~~~~~~~~~~~~~
  ggml.c:2262:15: note: called from here
   2262 |         acc = _mm256_fmadd_ps( d, q, acc );
        |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  make: *** [Makefile:201: ggml.o] Error 1
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/tmp/pip-build-env-o0vf_ayl/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 674, in setup
      cmkr.make(make_args, install_target=cmake_install_target, env=env)
    File "/tmp/pip-build-env-o0vf_ayl/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 697, in make
      self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
    File "/tmp/pip-build-env-o0vf_ayl/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 742, in make_impl
      raise SKBuildError(msg)

  An error occurred while building with CMake.
    Command:
      /tmp/pip-build-env-o0vf_ayl/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake --build . --target install --config Release --
    Install target:
      install
    Source directory:
      /tmp/pip-install-t24bt2kn/llama-cpp-python_38e362989f3b4e50bfea85febde41391
    Working directory:
      /tmp/pip-install-t24bt2kn/llama-cpp-python_38e362989f3b4e50bfea85febde41391/_skbuild/linux-x86_64-3.10/cmake-build
  Please check the install target is valid and see CMake's output for more information.

  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpzihi5by1
  cwd: /tmp/pip-install-t24bt2kn/llama-cpp-python_38e362989f3b4e50bfea85febde41391
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects`

**Comment by gjmulder** [comment]
It isn't a bug with `llama-cpp-python`. It is a problem with your virtualisation confusing `llama.cpp` about what hardware acceleration options to use:

[error: inlining failed in call to ‘always_inline’ ](https://github.com/ggerganov/llama.cpp/issues?q=error%3A+inlining+failed+in+call+to+%E2%80%98always_inline%E2%80%99)
