### ISSUE TITLE
Shared library with base name 'llama' not found, windows 

### ISSUE THREAD

**Issue by Mohamedballouch** [abetlen/llama-cpp-python#30]
can someone advise me on this issue, windows 
    from .llama_cpp import *  File "C:\Users\usr1\Anaconda3\envs\chatgpt1\lib\site-packages\llama_cpp\llama_cpp.py", line 46, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "C:\Users\moham\Anaconda3\envs\chatgpt1\lib\site-packages\llama_cpp\llama_cpp.py", line 40, in _load_shared_library
    raise FileNotFoundError(f"Shared library with base name '{lib_base_name}' not found")
FileNotFoundError: Shared library with base name 'llama' not found

**Comment by abetlen** [comment]
Hey @Mohamedballouch can you let me know the contents of the `C:\Users\usr1\Anaconda3\envs\chatgpt1\lib\site-packages\llama_cpp` folder, are there any `.dll` files located there?

**Comment by Mohamedballouch** [comment]
Hey man @abetlen  , no dll in the folder
![image](https://user-images.githubusercontent.com/28219393/230234121-d2c3bd45-bad7-4c4d-88e0-ba6e969eb089.png)

**Comment by abetlen** [comment]
So this seems to be an issue with anaconda, I'll have to investigate, if it's possible I'd recommend using a different package manager (pip or poetry should both work).

Alternatively you can build the .dll and copy it in:

```
# build this repo
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp
mkdir build
cd build
cmake ..
cmake --build . --config Release -DBUILD_SHARED_LIBS
```

**Comment by Mohamedballouch** [comment]
Thanks man 
i did the build of .dll but the last command didn't work with me
![image](https://user-images.githubusercontent.com/28219393/230239973-1344792f-afb6-4b13-aafa-9353e909fa1e.png)

**Comment by viktor02** [comment]
> So this seems to be an issue with anaconda, I'll have to investigate, if it's possible I'd recommend using a different package manager (pip or poetry should both work).
> 
> Alternatively you can build the .dll and copy it into the folder above
> 
> ```
> # build this repo
> git clone https://github.com/ggerganov/llama.cpp
> cd llama.cpp
> mkdir build
> cd build
> cmake ..
> cmake --build . --config Release -DBUILD_SHARED_LIBS
> ```

Same on pip installation

**Comment by viktor02** [comment]
I manage to build a llama.dll, but it broken
![изображение](https://user-images.githubusercontent.com/19672960/230313430-1c45ca6b-3822-4bd3-be98-829e7c688c79.png)

**Comment by abetlen** [comment]
> Thanks man i did the build of .dll but the last command didn't work with me ![image](https://user-images.githubusercontent.com/28219393/230239973-1344792f-afb6-4b13-aafa-9353e909fa1e.png)

Sorry, I think the `-DBUILD_SHARED_LIBS` is on the previous cmake command, try

```
# build this repo
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp
mkdir build
cd build
cmake ..  -DBUILD_SHARED_LIBS
cmake --build . --config Release
```

@viktor02 can you try that as well, that might be why the function isn't being linked in properly.

**Comment by abetlen** [comment]
Yeah if you check the github actions tab I'm currently struggling through this one too lol. Checking the cmake logs it looks like it gets built but not placed in the same place as other platforms?

But I'd assume this line should handle that?
https://github.com/abetlen/llama-cpp-python/blob/main/CMakeLists.txt#L9

**Comment by MillionthOdin16** [comment]
@abetlen 
Figured it out. You are right except for windows being weird.

```
install(TARGETS llama
        LIBRARY DESTINATION llama_cpp
        RUNTIME DESTINATION llama_cpp
)
```

By adding the runtime destination to the cmake config it correctly places the dll on windows. On Windows, shared libraries are typically installed in the bin directory, whereas on Unix-like systems, they are installed in the lib directory. So that's why it ended up in bin.

**Comment by abetlen** [comment]
I nearly cried seeing this, thank you!

![image](https://user-images.githubusercontent.com/6826477/230530978-71ca074e-4420-493e-93dd-da221b094768.png)

**Comment by MillionthOdin16** [comment]
Dude, for real. I can't imagine trying to troubleshoot a weird python/windows discrepancy from workflows 💀

Okay, so now it can find the lib, but I don't know the best way to streamline the build process. A lot of people are going to have this auto-configured environment, and it has lots of packages, so we might be able to follow one of those packages approaches for setting up builds. https://github.com/oobabooga/one-click-installers/blob/oobabooga-windows/install.bat

I'm not really familiar with getting build environments setup from python.

**Comment by Brandeyy** [comment]
![grafik](https://github.com/abetlen/llama-cpp-python/assets/84904650/b6459205-2f52-49da-8d61-51497fc748da)

I am getting a similar error. The .dll file is present in der correct directory though. Havent really found any info on why this could be happening.
