### ISSUE TITLE
Prompts and reuse of tokens questions

### ISSUE THREAD

**Issue by LeLaboDuGame** [abetlen/llama-cpp-python#304]
Hello ! I have some questions !

This is my actual code !

```python
from llama_cpp import Llama
class IA:
    def __init__(self, model_path):
        self.llm = Llama(model_path=model_path, n_gpu_layers=9999999
                         , n_ctx=4048, use_mlock=False)
        self.llm.reset()
        self.msgs = [{"role": "system",
                      "content": "### SYSTEM: " + self.get_main_prompt()}]
        print("model load !")

    # We don't fucking care about that is just my system prompt
    def get_main_prompt(self, path="./MainPrompt.nai"):
        main_prompt = ""
        for i in open(path, "r+").readlines():
            main_prompt += i
        return main_prompt

    def prompt(self, msg):
        print(self.llm.cache)
        print("Prompting...")
        self.msgs.append({"role": "user", "content": "### ADRIEN: " + msg})
        prompt = self.llm.create_chat_completion(
            messages=self.msgs,
            stop=["ADRIEN:", "ASSISTANT:", "Human:", "###"], max_tokens=100)["choices"][0]["message"]
        prompt["content"] = "### NASTOR: " + prompt["content"]
        print("Prompting finished !")
        return prompt


ia = IA("D:\\ia\\ia\\ggml-model-q4_0.bin")
for i in range(10):
    print(ia.prompt(input(">>> ")))

```

1-I see that the model store old convertional prompt because when I retsart completly the program he gives me old tokens. I want so to reset the model and I dont know how to do it...
2-I see that the model dont recognize old tokens and he have to reeval each time beetwen two chat_completion so it takes a big time to generate and I want to reduce that ! I see that on kobbold.cpp eval was made just one time and after the model knows whats are sayed.
3-How to generate token per token and get them in a for to maybe print theme procedurally.

I work with CLBLAST

Thanks in advance !
PS:My english is bad I'm young so I hope all are clear !

**Comment by gjmulder** [comment]
Any update?

**Comment by LeLaboDuGame** [comment]
Nope

**Comment by MatthewScholefield** [comment]
I checked the source and it looks like there are solutions to all of these (maybe they were added recently?):

1. Not sure what you're referring to, could you clarify? It seems like the prompt you give it contains all the context; it doesn't seem to remember anything else.
2. It looks like it automatically caches the last prompt and matches the longest prefix so if you do the same prompt again but with additional or slightly modified data it should reuse most of the state. If you switch between different prompts, you'll want to use `llama.set_cache(LlamaRAMCache())` or `llama.set_cache(LlamaDiskCache())` depending on if you have enough RAM and your hard drive speed which will allow automatically reusing state when you continue within a prior conversation.
3. You can use `stream=True` to generate token by token and print them as they generate. You also can use the separate `llama.generate(...)` API if you don't need the OpenAI-esque interface.
