### ISSUE TITLE
Support for 3B parameter models

### ISSUE THREAD

**Issue by jncraton** [abetlen/llama-cpp-python#305]
[OpenLLaMA](https://github.com/openlm-research/open_llama) includes a 3B model smaller than any of the original LLaMA models. Support for these smaller models was [recently merged in llama.cpp](https://github.com/ggerganov/llama.cpp/commit/ffb06a345e3a9e30d39aaa5b46a23201a74be6de).

It would be helpful if the llama.cpp submodule could be updated to provide support for these smaller models.

**Comment by abetlen** [comment]
@jncraton just published `v0.1.57` which adds support for the 3B parameter models, cheers.
