### ISSUE TITLE
 hi, I need help:

### ISSUE THREAD

**Issue by elpewpew** [abetlen/llama-cpp-python#31]
Hello, I need help, I am a very beginner programmer and I understand almost nothing, but could someone explain to me step by step how to use and execute the AI? I don't understand how to do it

**Comment by marceloeatworld** [comment]
Hi, I think you need to compile [llama.cpp]( https://github.com/ggerganov/llama.cpp) first.

**Comment by elpewpew** [comment]
How do I compile llama.cpp, could you explain it to me?

**Comment by marceloeatworld** [comment]
It's well explained in this post. [how to compile](https://til.simonwillison.net/llms/llama-7b-m2)  

Food luck :)

**Comment by elpewpew** [comment]
gracias xoxo
