### ISSUE TITLE
[WinError -529697949] Windows Error 0xe06d7363

### ISSUE THREAD

**Issue by ParisNeo** [abetlen/llama-cpp-python#311]
I tried to use this model: Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin

On my windows PC I get this error:
Une exception s'est produite : OSError
[WinError -529697949] Windows Error 0xe06d7363
  File "C:\Users\aloui\Documents\ai\lollms\lollms\bindings_zoo\llama_cpp_official\__init__.py", line 44, in __init__
    self.model = Llama(
OSError: [WinError -529697949] Windows Error 0xe06d7363

This used to work with previous version: 0.1.53
Is there another breaking change?

**Comment by gjmulder** [comment]
I believe we're at `ggml v3` still. It is still not clear under what circumstances the error occurs, but it does seem to be related to model versioning.

**Comment by gjmulder** [comment]
Let's hope #316 can solve this issue.

**Comment by ParisNeo** [comment]
Sorry for that. They have changed the versions and every time it breaks the compatibility with old models. New models work fine though.
Just recover a new version of the model or simply install an older version of the llama-cpp-python binding using 
```bash
pip install llama-cpp-python==0.1.52
```

or another version. I tested the new version with new models and they seem to work fine.

**Comment by gjmulder** [comment]
Excellent info. Thx! `ggml v3` promised significant performance increases for quantized models. `fp16 ggml v1` models should always work, at the cost of twice the RAM for only a small increase in quality.

Can we close this issue?

**Comment by ParisNeo** [comment]
I think yes
