### ISSUE TITLE
Getting Server Running Public?

### ISSUE THREAD

**Issue by msj121** [abetlen/llama-cpp-python#318]
I can run:

`python3 -m llama_cpp.server --model ./llama.cpp/models/Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_1.bin --n_threads 3`

and it binds to localhost, I want to be able to access http publicly from another server. It is not seeing my instance (locally it sees the docs). Is there a way to change the host? Maybe bind to 0.0.0.0 or something?

**Comment by jmtatsch** [comment]
Exactly as you think. Look at docker/compose files for ideas how  this can be achieved.

**Comment by msj121** [comment]
From #315 

```
$ export HOST=<external IP of your OS>
$ python3 -m llama_cpp.server
```
