### ISSUE TITLE
Logprobs incorrectly computed from logits

### ISSUE THREAD

**Issue by progtologist** [abetlen/llama-cpp-python#349]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I am feeding llama-cpp-python through the `create_completion` api with predefined prompts.
The predefined prompts are like this:
```
Q: Play music
A: music.play()

Q: Stop music
A: music.stop()

... a few more examples...

Q: Pause music
A: %STRING%
```
The `%STRING%` I replace with different API calls, one of them being `music.pause()` but the others can be `music.play()`, `music.stop()` etc.

I am calling the API with max_tokens=0, logprobs=1, temperature=0 and echo=True. I am basically not interested in generating a response, I just want my `%STRING%` to be evaluated by the LLM.

The reason why I do this, is that I expect the correct API call to have a much higher combined logprob than the wrong API calls.

I have validated this example with OpenAI with different models, and it does work without issues.

The problem that I am facing is that the logprobs that gets calculated from llama-cpp-python does not appear to be correct. 

The values that I get are almost constantly extremely low. I have tried to see if I can fix it, but unfortunately the few things that I have tried did not work, and I believe some expert advice could go a long way.

# Current Behavior

I print all the tokens, together with their logprobs and their probs which I calculate through numpy.exp(logprobs)

The following is an example of the results I get:
```
Token Logprob Probability
mu -13.098522331165873 2.0482550320620133e-06
sic -23.94800838365418 3.976601815073668e-11
. -25.437061074011822 8.970667086442726e-12
play -24.84781513922617 1.6170781080207215e-11
() -27.32543331183062 1.3574226671545055e-12
```

Similarly, the same example with the OpenAI api yields:
```
Token Logprob Probability
mu -0.49815017 0.6076536766979097
sic -0.0052926685 0.9947213129925816
. 0 1.0
play -0.8366768 0.4331475703151241
() -3.4089344e-06 0.9999965910714105
```
Which makes so much more sense, as expected, the tokens that are really expected to be there get probability that is very close to 1.

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

```bash
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               GenuineIntel
  Model name:            11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    CPU family:          6
    Model:               141
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           1
    Stepping:            1
    CPU max MHz:         4600.0000
    CPU min MHz:         800.0000
    BogoMIPS:            4608.00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_g
                         ood nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_
                         timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase t
                         sc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock
                         _detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid mo
                         vdiri movdir64b fsrm avx512_vp2intersect md_clear ibt flush_l1d arch_capabilities
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   384 KiB (8 instances)
  L1i:                   256 KiB (8 instances)
  L2:                    10 MiB (8 instances)
  L3:                    24 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-15
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

* Operating System, e.g. for Linux:

```bash
$ uname -a
Linux HOSTNAME 5.19.0-1024-lowlatency #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Apr 24 09:44:21 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

* SDK version, e.g. for Linux:

```bash
$ python3 --version
Python 3.10.11
$ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by abetlen** [comment]
@progtologist will look into this
