### ISSUE TITLE
0.1.59 and 0.1.60 does not install correctly or open new quantizations

### ISSUE THREAD

**Issue by Celppu** [abetlen/llama-cpp-python#354]
Cannot use the newest version to work and previous does not open the new quantization formats

used:
sudo CMAKE_ARGS="-DLLAMA_CUBLAS=on" CUDACXX=/usr/local/cuda-12.1/bin/nvcc FORCE_CMAKE=1 pip install llama-cpp-python==0.1.59 --force-reinstall  --no-cache-dir

with that I only get
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1070
llama.cpp: loading model from /home/valtionrautatiet/Downloads/guanaco-65B.ggmlv3.q3_K_L.bin

and with 0.1.60 I cannot even install. During installation i get:

Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      loading initial cache file /tmp/tmpib4l_tji/build/CMakeInit.txt
      -- The C compiler identification is GNU 11.3.0
      -- The CXX compiler identification is GNU 11.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Git: /usr/bin/git (found version "2.34.1")
      fatal: not a git repository: /tmp/pip-install-m9w32sky/llama-cpp-python_5a7502dc643144868fbb99654d89e138/vendor/llama.cpp/../../.git/modules/vendor/llama.cpp
      fatal: not a git repository: /tmp/pip-install-m9w32sky/llama-cpp-python_5a7502dc643144868fbb99654d89e138/vendor/llama.cpp/../../.git/modules/vendor/llama.cpp
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
      -- Found Threads: TRUE
      -- Found CUDAToolkit: /usr/local/cuda/include (found version "12.1.105")
      -- cuBLAS found
      -- The CUDA compiler identification is NVIDIA 12.1.105
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/local/cuda-12.1/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- CMAKE_SYSTEM_PROCESSOR: x86_64
      -- x86 detected
      -- GGML CUDA sources found, configuring CUDA architecture
      -- Configuring done (2.2s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/tmpib4l_tji/build
      ninja: error: '/tmp/pip-install-m9w32sky/llama-cpp-python_5a7502dc643144868fbb99654d89e138/.git/modules/vendor/llama.cpp/index', needed by '/tmp/pip-install-m9w32sky/llama-cpp-python_5a7502dc643144868fbb99654d89e138/vendor/llama.cpp/build-info.h', missing and no known rule to make it
      *** scikit-build-core 0.4.4 using CMake 3.26.4
      *** Configurating CMake...
      *** Building project with Ninja...
      
      *** CMake build failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python

**Comment by brandonj60** [comment]
I don't see a 0.1.60 release. Unless I'm missing something, 0.1.59 is the newest.
https://github.com/abetlen/llama-cpp-python/releases

**Comment by gjmulder** [comment]
#352

**Comment by DocShotgun** [comment]
Yeah 0.1.59 is the latest release, but I've been trying today to build the current master branch of the repo (which is versioned as 0.1.60) in order to use k-quants and the recent fixes introduced to llama.cpp that are not available in the last release version. I suspect that OP is trying to do the same.

I also haven't had any success getting it to work. I cloned llama-cpp-python into a folder and then llama.cpp into the vendor subfolder, then attempted to pip install the package from source with:

```
set CMAKE_ARGS="-DLLAMA_CUBLAS=on"
set FORCE_CMAKE=1
pip install . --no-cache-dir
```

However I'm not getting any errors - in fact it's saying the package was installed successfully. But it doesn't actually build llama.dll and upon attempting to load a model errors out with an unable to load module.

**Comment by Celppu** [comment]
Apparently 0.1.60 had problems and was replaced with 0.1.61. Now the newest works!
