### ISSUE TITLE
library doesn't print verbose information

### ISSUE THREAD

**Issue by dhirajsuvarna** [abetlen/llama-cpp-python#371]
### Discussed in https://github.com/abetlen/llama-cpp-python/discussions/364

<div type='discussions-op-text'>

<sup>Originally posted by **dhirajsuvarna** June 12, 2023</sup>
Hi, 
I am using llama-cpp-python to load a LLM model and want to see its running times during prediction. 

For this i am instantiating the model in the following manner - 
![image](https://github.com/abetlen/llama-cpp-python/assets/4989127/5ca742bc-4932-4eb7-b676-cc28c770ccef)

but i am not able to see any output regarding the timings. 
I am doing this on google colab. 
Am I missing something?</div>

**Comment by dhirajsuvarna** [comment]
@gjmulder  - is this an enhancement !!! would like to understand whats the problem here?

**Comment by gjmulder** [comment]
Actually now that I looked at it again I'm guessing that Colab isn't displaying output `stderr`. `llama.cpp` (not `llama-cpp-python`) prints the timing info to `stderr`.

@abetlen is there a Pythonic way to redirect `stderr` from `libllama.cpp`?

**Comment by abetlen** [comment]
@gjmulder sorry for the late reply, best bet would be https://docs.python.org/3/library/contextlib.html?highlight=context#contextlib.redirect_stderr

```python
import sys
from contextlib import redirect_stderr
with redirect_stderr(sys.stdout):
    ...
```

**Comment by dhirajsuvarna** [comment]
Nope, its not working :( 

![image](https://github.com/abetlen/llama-cpp-python/assets/4989127/399c26a6-394d-4ad8-b3be-f3d33e57ccb7)

**Comment by codito** [comment]
`contextlib` works if the code writing to stderr/stdout is pure python. If the source is C code, we can try https://github.com/minrk/wurlitzer.

This worked for me.

```python
from wurlitzer import pipes

with pipes():
    self._llm = llama_cpp.Llama(...)
```
