### ISSUE TITLE
Update llama.cpp for new CUDA support

### ISSUE THREAD

**Issue by amrrs** [abetlen/llama-cpp-python#378]
Thanks very much for the project, any plans to enable the recently merged CUDA support?

https://github.com/ggerganov/llama.cpp/pull/1827

**Comment by NeoAnthropocene** [comment]
> Thanks very much for the project, any plans to enable the recently merged CUDA support?
> 
> [ggerganov/llama.cpp#1827](https://github.com/ggerganov/llama.cpp/pull/1827)

I am also looking for that.
The speed boost is promising, I would like to try it asap :)

**Comment by abetlen** [comment]
@gaby @NeoAnthropocene yes should've been included in 0.1.63. I also just published 0.1.64 with some additional fixes from llama.cpp, let me know if that works!

**Comment by gaby** [comment]
> @gaby @NeoAnthropocene yes should've been included in 0.1.63. I also just published 0.1.64 with some additional fixes from llama.cpp, let me know if that works!

@amrrs Thanks, i didnt get the email notification because its a git tag, not a Github release 😂

**Comment by matib99** [comment]
Should it work now? I installed v0.1.64 with cuBLAS, and set `n_gpu_layers` parameter and it still runs only on CPU. I'm on Ubuntu with rtx3080, `torch.cuda.is_available()` returns true.

**Comment by berkut1** [comment]
On the RTX 2080 I got +~10% performance (13b models) after the upgrade but can only load 50-60% of the GPU layers due to VRAM. (I have a large context min. 400 tokens)

**Comment by NeoAnthropocene** [comment]
> @gaby @NeoAnthropocene yes should've been included in 0.1.63. I also just published 0.1.64 with some additional fixes from llama.cpp, let me know if that works!

Thx for the feedback.
I uninstalled my previous llama-cpp-python==0.1.63 model and now I can't install it back with BLAS=1

I've read everything on the internet but I somehow it builds without CUDA support. That is strange because I couldn't remember about any change that I've done before with the CUDA toolkit installation on my system.

**Comment by bryanhpchiang** [comment]
the latest llama.cpp works with CUDA acceleration, but not this repo in my own testing
