### ISSUE TITLE
rand=-1 to use a random seed, not rand=0 as documented

### ISSUE THREAD

**Issue by rmngllnn** [abetlen/llama-cpp-python#386]
Hello,

I use this library to use `llama-cpp` in Python.

It's working very well but the generation is always the same (no seed in the script). I use this function 

```python
from llama_cpp import Llama

llama = Llama("./path/models/7B/ggml-model-7b.bin")

gen = llama.create_completion("Cite the best movie citation you know.", 
                         max_tokens=50, 
                         temperature=0.95, 
                         top_p=0.95)
```
I ran it several times and it's always the same text generated. Is there like HuggingFace a `do_sample` parameter to trigger ? I didn't find anything in the documentation or the issues of this github (but maybe I missed it)

Thank you, whoever you are who will help me :)

**Comment by gjmulder** [comment]
Try changing the `seed` when you init the model:

[llama_cpp.llama.Llama.__init__](https://abetlen.github.io/llama-cpp-python/#llama_cpp.llama.Llama.__init__)

**Comment by rmngllnn** [comment]
Same thing happen. Got the same generation with three runs.

**Comment by gjmulder** [comment]
That's strange. Can you try -1?

It looks like seed is passed to `libllama.cpp`:

```
llama.cpp$ ./main --help 2>&1 | grep seed
  -s SEED, --seed SEED  RNG seed (default: -1, use random seed for < 0)
```

**Comment by rmngllnn** [comment]
It's working by passing -1 to seed

According to [documentation ](https://abetlen.github.io/llama-cpp-python/#llama_cpp.llama.Llama.__init__), default is to 1337 and 0 value for random seed.

-1 does allow to have different generation for each run.

Thank you.

**Comment by gjmulder** [comment]
Bug in the docs then :smile:

**Comment by rmngllnn** [comment]
Apparently ... which is unfortunate ...

Thank you for your (fast) response and help :)

**Comment by batrasrishti** [comment]
> It's working by passing -1 to seed
> 
> According to [documentation ](https://abetlen.github.io/llama-cpp-python/#llama_cpp.llama.Llama.__init__), default is to 1337 and 0 value for random seed.
> 
> -1 does allow to have different generation for each run.
> 
> Thank you.

How to get same generated answer every single time?

**Comment by gerrynjenny** [comment]
The above pointers were not permalinks so the urls are now 404. So I'm sharing this for others looking for the seed code:
https://github.com/abetlen/llama-cpp-python/blob/a14b49d64e760183504e1a5b37f4c9beb36a20ff/llama_cpp/llama.py#L82
https://github.com/abetlen/llama-cpp-python/blob/a14b49d64e760183504e1a5b37f4c9beb36a20ff/llama_cpp/llama.py#L163

<img width="402" alt="Screenshot 2024-07-25 at 09 23 14" src="https://github.com/user-attachments/assets/e89c139c-c4e8-4169-8235-46396c89389a">

**Comment by dentropy** [comment]
> ```python
> top_p=0.95)
> ```

Seems like this was the magic variable we need to set, setting seed and temerature by themselves does not work
