### ISSUE TITLE
termux build issues

### ISSUE THREAD

**Issue by SubhranshuSharma** [abetlen/llama-cpp-python#389]
pip install llama-cpp-python doesn't work on termux and gives [this](https://pastebin.com/mZdeQXTd) error, even if ninja is installed it gives same error, might be a hardcoded absolute path problem

i have tried to use [portable venv](https://web.archive.org/web/20201130233251/https://aarongorka.com/blog/portable-virtualenv/) setup on my linux machine but running it on termux gave a dependency not found error, so maybe some paths in the source code were still absolute(even after the correction attempts in the [blog post](https://web.archive.org/web/20201130233251/https://aarongorka.com/blog/portable-virtualenv/))

tried using pyinstaller, but it doesn't support this library yet, same missing dependency issue

another option is to use [docker on termux](https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27) but that requires root privileges and custom kernel

i hv tried to look into the source code of this repo but donno where to start, any hint on where to start?

the original llama.cpp library works fine on termux but doesn't have a server inbuilt, and doesn't work well unless using bash

should i make a pull request editing the readme, linking to the docker workaround on rooted phones

**Comment by aseok** [comment]
I resolved ninja installation by termux-chroot. Also added following to 
project CMakeLists.txt:
set(CMAKE_C_COMPILER "/data/data/com.termux/files/usr/bin/clang")
set(CMAKE_CXX_COMPILER "/data/data/com.termux/files/usr/bin/clang++")
And passing opencl args:
CMAKE_ARGS="-DLLAMA_CLBLAST=on -DLLAMA_OPENBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python
Here's output eror:
../CMake-src/Utilities/cmlibarchive/libarchive/archive.h:101:10: fatal error: 'android_lf.h' file not found
            #include "android_lf.h"

**Comment by abetlen** [comment]
Looks to be related to https://github.com/scikit-build/cmake-python-distributions/issues/223

The longer term solution seems to be migrating the project to scikit-build-core (something I'm in the process of doing). However someone in the thread mentioned they were able to get their example to work by building cmake and ninja from source on the android.

**Comment by aseok** [comment]
Also tried following:
cmake .. -DLLAMA_CLBLAST=on -DLLAMA_OPENBLAS=on
make
make install

Here's output:
CMake Error: Target DependInfo.cmake file not found
[100%] Built target run
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /usr/local/llama_cpp/libllama.so
Is installing successful?
Python:
>>> import llama_cpp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'llama_cpp'

**Comment by SubhranshuSharma** [comment]
while trying to make it work on termux i ended up writing a [small llama.cpp wrapper](https://github.com/SubhranshuSharma/The_Elite_Order_of_Pure_Thought/tree/cb063f5ac0d8c8a26bc75f4f0de18cc8cee062ef/discord/termux) myself, instructions to use which are [here](https://github.com/SubhranshuSharma/The_Elite_Order_of_Pure_Thought/tree/cb063f5ac0d8c8a26bc75f4f0de18cc8cee062ef#linuxtermux), at the time llama.cpp cache files could be read but not generated/edited in termux, but that problem is sorted now, so put `cache_is_supported_trust_me_bro=True` in `discord/termux/settings.py` to use it.

[these highlighted lines](https://github.com/SubhranshuSharma/The_Elite_Order_of_Pure_Thought/blob/cb063f5ac0d8c8a26bc75f4f0de18cc8cee062ef/discord/termux/the_elite_bot_termux.py#L40C1-L51C71) are all you need to make a wrapper of your own

**Comment by aseok** [comment]
Is it compatible with babyagi and other stuff that needs llama python
wrapper?

**Comment by SubhranshuSharma** [comment]
nope, my wrapper is tightly integrated with with my usecase and isn't a separate installable package

**Comment by abetlen** [comment]
@SubhranshuSharma so for your wrapper you just built the libllama.so seperately correct, did you just build llama.cpp with the Makefile? Maybe one solution is to avoid building llama.cpp on install by setting an environment variable / path to a pre-built library.

**Comment by SubhranshuSharma** [comment]
> @SubhranshuSharma so for your wrapper you just built the libllama.so seperately correct, did you just build llama.cpp with the Makefile? Maybe one solution is to avoid building llama.cpp on install by setting an environment variable / path to a pre-built library.

Yeah, I run `git clone https://github.com/ggerganov/llama.cpp ~/llama.cpp;cd ~/llama.cpp;make`

I suggest, just check if the `main` file exists at a pre defined/user inputted path, if not use `os.system('git clone https://github.com/ggerganov/llama.cpp ~/llama.cpp;cd ~/llama.cpp;make')` to clone and make it, way more simple and easy to maintain.

**Comment by Freed-Wu** [comment]
> The longer term solution seems to be migrating the project to scikit-build-core

Any progress about it?

**Comment by SubhranshuSharma** [comment]
> Any progress about it?

[seems related](https://github.com/abetlen/llama-cpp-python/pull/350)

**Comment by abetlen** [comment]
@SubhranshuSharma @Freed-Wu implementing in #499 but I just have some issues with Macos still

**Comment by abetlen** [comment]
@SubhranshuSharma sorry for this very late reply but I finally merged in #499.

You can now set `CMAKE_ARGS="-DLLAMA_BUILD=OFF pip install llama-cpp-python` to avoid building from source, then just set `LLAMA_CPP_LIB` to the path to the shared library to use a pre-built library.

**Comment by Freed-Wu** [comment]
So can we close this issue now?

**Comment by bishwenduk029** [comment]
@Freed-Wu , @abetlen 
I also tried packaging a python binary with llama-cpp-python, but when I try to run the binary standalone it fails with below error

```
INFO:root:Loading Model: TheBloke/synthia-7b-v1.3.Q5_K_M.gguf, on: cpu
INFO:root:This action can take a few minutes!
INFO:root:synthia-7b-v1.3.Q5_K_M.gguf
INFO:root:Using Llamacpp for GGUF/GGML quantized models
ERROR:root:Exception occurred: Shared library with base name 'llama' not found
```

But when I run simply by `python3 main.py` it works fine.

For pyinstaller do I need to generate the shared library seperatly and then use `LLAMA_CPP_LIB`

**Comment by SubhranshuSharma** [comment]
> You can now set `CMAKE_ARGS="-DLLAMA_BUILD=OFF pip install llama-cpp-python` to avoid building from source, then just set `LLAMA_CPP_LIB` to the path to the shared library to use a pre-built library.

[this](https://pastebin.com/K5sh8jjD) is the error i still get in termux when running `CMAKE_ARGS="-DLLAMA_BUILD=OFF" pip install llama-cpp-python`

am i missing something

**Comment by romanovj** [comment]
@SubhranshuSharma if you want to build cmake module https://github.com/termux/termux-packages/issues/10065

or build without it
1. CMAKE_ARGS="-DLLAMA_BUILD=OFF" pip install llama-cpp-python --no-build-isolation -v

2. check error message and install missing modules

 repeat 1-2 steps

**Comment by Freed-Wu** [comment]
@SubhranshuSharma can <https://github.com/termux/termux-packages/actions/runs/5992017774?pr=17457> be useful?

**Comment by SubhranshuSharma** [comment]
is the python library working for anyone?

@Freed-Wu is this related to adding llama.cpp to termux package manager? if yes, llama.cpp was working out of the box on termux anyway, that's why i could make my own usecase-specific python wrapper around it, to quote myself:

> @abetlen Yeah, I run `git clone https://github.com/ggerganov/llama.cpp ~/llama.cpp;cd ~/llama.cpp;make`

@romanovj [this solution of yours](https://github.com/termux/termux-packages/issues/10065#issuecomment-1655979515) did install cmake without errors, now `pip list` is returning `cmake` and a simple `import cmake` is working, but `pip install llama-cpp-python` still gives [error](https://pastebin.com/FkXtBYcm) saying `No module named 'cmake'`

and your second solution leads to [this error](https://pastebin.com/PCCTk26w), where i dont see any installable dependencies to install

**Comment by romanovj** [comment]
@SubhranshuSharma 
`still gives [error](https://pastebin.com/FkXtBYcm) saying No module named 'cmake`

reinstall cmake
`pkg rei cmake`

also you can copy compiled cmake wheel to ~/wheels folder and install modules with
pip install ... --find-links ~/wheels

**Comment by abetlen** [comment]
Hey guys, I was finally able to put some time into this, the following worked for me:

```bash
pkg install python-pip python-cryptography cmake ninja autoconf automake libandroid-execinfo
MATHLIB=m CFLAGS=--target=aarch64-unknown-linux-android33 LDFLAGS=-lpython3.11 pip install numpy --force-reinstall --no-cache-dir
pip install llama-cpp-python --verbose
```

**Comment by SubhranshuSharma** [comment]
@abetlen it works inconsistently, on a clean termux install with python installed i usually also haveto install `libexpat` then `openssl` then run `pkg update && pkg upgrade`

this works more consistently for me, keep selecting default answers to prompts
```shell
pkg install libexpat openssl python-pip python-cryptography cmake ninja autoconf automake libandroid-execinfo patchelf
pkg update && pkg upgrade 
MATHLIB=m CFLAGS=--target=aarch64-unknown-linux-android33 LDFLAGS=-lpython3.11 pip install numpy --force-reinstall --no-cache-dir pip install llama-cpp-python --verbose
```
then run `python -c 'import llama_cpp'` to check if it installed

**Comment by pinyaras** [comment]
Does the llama-cpp-server work in termux?

**Comment by SubhranshuSharma** [comment]
@pinyaras original llama.cpp has its [own server](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md) which is stable
the python server additionally requires rust which is [unstable](https://github.com/termux/termux-packages/issues/15851) on termux but is working for now, after installing previous requirements run
```shell
pkg install rust
pip install llama-cpp-python[server]
```
