### ISSUE TITLE
Investigate model aliasing

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#39]
Allow the user to alias their local models to OpenAI model names as many tools have those hard-coded.

This may cause unexpected issues with tokenization mismatches.

**Comment by MillionthOdin16** [comment]
Is this still an issue, or you meant to delete?

**Comment by abetlen** [comment]
Just tracking an idea I had related to #17 basically allow the user to alias their local models to OpenAI model names as many tools have those hard-coded.

**Comment by MillionthOdin16** [comment]
Ahhhhh, okay, I thought you were somehow having models aliasing as an issue 😆
