### ISSUE TITLE
AssertionError due to model version 

### ISSUE THREAD

**Issue by garder-les-ciseaux-droits** [abetlen/llama-cpp-python#393]
WHY? 
I've never had this error before. 2 weeks ago It worked well. Now I can't run my model.

llama.cpp: loading model from ./ggml-vicuna-7b-4bit-rev1.bin
error loading model: unexpectedly reached end of file
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "/Users/evanvosh/PycharmProjects/pythonProject2/main.py", line 2, in <module>
    llm = Llama(model_path="./ggml-vicuna-7b-4bit-rev1.bin")
  File "/Users/evanvosh/PycharmProjects/pythonProject2/venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 289, in __init__
    assert self.ctx is not None
AssertionError

**Comment by SubhranshuSharma** [comment]
I think your model is not up-to-date, u seem to b using [this](https://huggingface.co/eachadea/legacy-ggml-vicuna-7b-4bit/tree/main) model(judging by the name in error), use something like [this](https://huggingface.co/TheBloke/vicuna-7B-1.1-GGML/tree/main)

**Comment by garder-les-ciseaux-droits** [comment]
Thanks. It works!

**Comment by moapatoa** [comment]
I have a quite similar issue with some models :
```
    assert self.**model** is not None
AssertionError
```
But I get this error with recent model (updated 27 days ago on Huggingface), I think they're up to date, any idea ?
The model I use that raise the error is this one :
[Vigogne-Instruct-13B.ggmlv3.q2_K.bin](https://huggingface.co/TheBloke/Vigogne-Instruct-13B-GGML/tree/main)

**Comment by moapatoa** [comment]
Oh and I just tried [pygmalion-13b-superhot-8k.ggmlv3.q6_K.bin](https://huggingface.co/TheBloke/Pygmalion-13B-SuperHOT-8K-GGML/tree/main), that work perfectly, whereas the same model with q2_K quant method ([pygmalion-13b-superhot-8k.ggmlv3.q2_K.bin](https://huggingface.co/TheBloke/Pygmalion-13B-SuperHOT-8K-GGML/tree/main)) raise this error.
Both were published one week ago ; I don't understand why the q6_K work when  q2_K don't...

**Comment by moapatoa** [comment]
Ok while trying several models, I noticed that TheBlock specify that some models are "type 0" or "type 1"
([here is a clue](https://huggingface.co/TheBloke/Vigogne-Instruct-13B-GGML#explanation-of-the-new-k-quant-methods))
I don't know the difference, but types 0 seem working and type 1 not
