### ISSUE TITLE
Build fails on Mac M1 13.4

### ISSUE THREAD

**Issue by slavag** [abetlen/llama-cpp-python#396]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Current Behavior

Failed CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install -U llama-cpp-python --no-cache-dir.

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

MacBook Pro M1 Mac MacOS 13.4
```
$ python3 --version : Python 3.11.3
$ make --version : GNU Make 3.81
$ g++ --version : Apple clang version 14.0.3 (clang-1403.0.22.14.1)
```
# Failure Logs
   ```   
  Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [163 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is AppleClang 14.0.3.14030022
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is AppleClang 14.0.3.14030022
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.9s)
      -- Generating done (0.0s)
      -- Build files have been written to: /private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-install-bxevf_t_/llama-cpp-python_b7a363606aee4610be73116904d6c35b/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-install-bxevf_t_/llama-cpp-python_b7a363606aee4610be73116904d6c35b/_skbuild/macosx-13.0-arm64-3.11/cmake-build
        Command:
          /private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-build-env-c1j0ikz4/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake /private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-install-bxevf_t_/llama-cpp-python_b7a363606aee4610be73116904d6c35b -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-build-env-c1j0ikz4/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-install-bxevf_t_/llama-cpp-python_b7a363606aee4610be73116904d6c35b/_skbuild/macosx-13.0-arm64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.3 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-build-env-c1j0ikz4/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/Users/slava/.pyenv/versions/3.11.3/bin/python3.11 -DPYTHON_INCLUDE_DIR:PATH=/Users/slava/.pyenv/versions/3.11.3/include/python3.11 -DPYTHON_LIBRARY:PATH=/Users/slava/.pyenv/versions/3.11.3/lib/libpython3.11.dylib -DPython_EXECUTABLE:PATH=/Users/slava/.pyenv/versions/3.11.3/bin/python3.11 -DPython_ROOT_DIR:PATH=/Users/slava/.pyenv/versions/3.11.3 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/Users/slava/.pyenv/versions/3.11.3/include/python3.11 -DPython3_EXECUTABLE:PATH=/Users/slava/.pyenv/versions/3.11.3/bin/python3.11 -DPython3_ROOT_DIR:PATH=/Users/slava/.pyenv/versions/3.11.3 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/Users/slava/.pyenv/versions/3.11.3/include/python3.11 -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-build-env-c1j0ikz4/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -DLLAMA_METAL=on -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=13.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64 -DCMAKE_BUILD_TYPE:STRING=Release -DLLAMA_METAL=on
      
      Not searching for unused variables given on the command line.
      -- The C compiler identification is AppleClang 14.0.3.14030022
      -- The CXX compiler identification is AppleClang 14.0.3.14030022
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Git: /usr/bin/git (found version "2.39.2 (Apple Git-143)")
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      CMake Warning at vendor/llama.cpp/CMakeLists.txt:112 (message):
        Git repository not found; to enable automatic generation of build info,
        make sure Git is installed and the project is a Git repository.
      
      
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
      -- Found Threads: TRUE
      -- Accelerate framework found
      -- CMAKE_SYSTEM_PROCESSOR: arm64
      -- ARM detected
      -- Configuring done (0.6s)
      -- Generating done (0.0s)
      -- Build files have been written to: /private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-install-bxevf_t_/llama-cpp-python_b7a363606aee4610be73116904d6c35b/_skbuild/macosx-13.0-arm64-3.11/cmake-build
      [1/8] Building C object vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o
      [2/8] Building C object vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-metal.m.o
      [3/8] Building CXX object vendor/llama.cpp/CMakeFiles/llama.dir/llama.cpp.o
      [4/8] Building C object vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o
      [5/8] Linking C static library vendor/llama.cpp/libggml_static.a
      [6/8] Linking C shared library vendor/llama.cpp/libggml_shared.dylib
      FAILED: vendor/llama.cpp/libggml_shared.dylib
      : && /Library/Developer/CommandLineTools/usr/bin/cc -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=13.0 -dynamiclib -Wl,-headerpad_max_install_names  -o vendor/llama.cpp/libggml_shared.dylib -install_name @rpath/libggml_shared.dylib vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-metal.m.o vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o   && :
      Undefined symbols for architecture arm64:
        "_MPSSupportsMTLDevice", referenced from:
            _ggml_metal_init in ggml-metal.m.o
        "_MTLCreateSystemDefaultDevice", referenced from:
            _ggml_metal_init in ggml-metal.m.o
        "_OBJC_CLASS_$_MPSMatrix", referenced from:
            objc-class-ref in ggml-metal.m.o
        "_OBJC_CLASS_$_MPSMatrixDescriptor", referenced from:
            objc-class-ref in ggml-metal.m.o
        "_OBJC_CLASS_$_MPSMatrixMultiplication", referenced from:
            objc-class-ref in ggml-metal.m.o
        "_OBJC_CLASS_$_NSBundle", referenced from:
            objc-class-ref in ggml-metal.m.o
        "_OBJC_CLASS_$_NSMutableArray", referenced from:
            objc-class-ref in ggml-metal.m.o
        "_OBJC_CLASS_$_NSObject", referenced from:
            _OBJC_CLASS_$_GGMLMetalClass in ggml-metal.m.o
        "_OBJC_CLASS_$_NSString", referenced from:
            objc-class-ref in ggml-metal.m.o
        "_OBJC_METACLASS_$_NSObject", referenced from:
            _OBJC_METACLASS_$_GGMLMetalClass in ggml-metal.m.o
        "___CFConstantStringClassReference", referenced from:
            CFString in ggml-metal.m.o
            CFString in ggml-metal.m.o
            CFString in ggml-metal.m.o
            CFString in ggml-metal.m.o
            CFString in ggml-metal.m.o
            CFString in ggml-metal.m.o
            CFString in ggml-metal.m.o
            ...
        "__objc_empty_cache", referenced from:
            _OBJC_METACLASS_$_GGMLMetalClass in ggml-metal.m.o
            _OBJC_CLASS_$_GGMLMetalClass in ggml-metal.m.o
        "_cblas_sgemm", referenced from:
            _ggml_compute_forward_mul_mat in ggml.c.o
        "_objc_alloc", referenced from:
            ___ggml_metal_graph_compute_block_invoke in ggml-metal.m.o
        "_objc_opt_class", referenced from:
            _ggml_metal_init in ggml-metal.m.o
        "_vDSP_maxv", referenced from:
            _ggml_compute_forward_soft_max in ggml.c.o
            _ggml_compute_forward_flash_attn in ggml.c.o
            _ggml_compute_forward_flash_attn_back in ggml.c.o
            _ggml_compute_forward_cross_entropy_loss in ggml.c.o
            _ggml_compute_forward_cross_entropy_loss_back in ggml.c.o
        "_vDSP_sve", referenced from:
            _ggml_compute_forward_sum_rows in ggml.c.o
            _ggml_compute_forward_mean in ggml.c.o
            _ggml_compute_forward_cross_entropy_loss in ggml.c.o
        "_vDSP_vadd", referenced from:
            _ggml_compute_forward_add in ggml.c.o
            _ggml_compute_forward_add1 in ggml.c.o
            _ggml_compute_forward_acc in ggml.c.o
        "_vDSP_vdiv", referenced from:
            _ggml_compute_forward_div in ggml.c.o
        "_vDSP_vmul", referenced from:
            _ggml_compute_forward_mul in ggml.c.o
        "_vDSP_vsub", referenced from:
            _ggml_compute_forward_sub in ggml.c.o
      ld: symbol(s) not found for architecture arm64
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      [7/8] Linking CXX shared library vendor/llama.cpp/libllama.dylib
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-build-env-c1j0ikz4/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-build-env-c1j0ikz4/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-build-env-c1j0ikz4/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-build-env-c1j0ikz4/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-install-bxevf_t_/llama-cpp-python_b7a363606aee4610be73116904d6c35b
        Working directory:
          /private/var/folders/z1/qsct20p17nxdfhjlp29yr6r40000gn/T/pip-install-bxevf_t_/llama-cpp-python_b7a363606aee4610be73116904d6c35b/_skbuild/macosx-13.0-arm64-3.11/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
```
Environment info:
```
llama-cpp-python$ git log | head -1
commit 92b0013427be9a1fcea29a3090aa51d0fd8fb35f

llama-cpp-python$ python3 --version
Python 3.11.3

llama-cpp-python$ pip list | egrep "uvicorn|fastapi|sse-starlette|numpy"
fastapi                  0.95.2
numpy                    1.24.3
uvicorn                  0.22.0

llama-cpp-python/vendor/llama.cpp$ git log | head -3
commit 92b0013427be9a1fcea29a3090aa51d0fd8fb35f
Author: Andrei Betlen <abetlen@gmail.com>
Date:   Sun Jun 18 09:48:43 2023 -0400
```

**Comment by Jchang4** [comment]
Also seeing this error: 

```
Traceback (most recent call last):
  File "/Users/justin/.justin_bash/ai_tools/main.py", line 67, in <module>
    llm = get_langchain_llama(
  File "/Users/justin/.justin_bash/ai_tools/ai_tools/get_llama.py", line 16, in get_langchain_llama
    return LlamaCpp(
  File "/Users/justin/mambaforge/envs/langchain/lib/python3.10/site-packages/langchain/load/serializable.py", line 64, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /Users/justin/Desktop/text-generation-webui/models/WizardLM-7B-uncensored-GGML/WizardLM-7B-uncensored.ggmlv3.q4_K_M.bin. Received error Model path does not exist: /Users/justin/Desktop/text-generation-webui/models/WizardLM-7B-uncensored-GGML/WizardLM-7B-uncensored.ggmlv3.q4_K_M.bin (type=value_error)
Exception ignored in: <function Llama.__del__ at 0x11fd38700>
Traceback (most recent call last):
  File "/Users/justin/mambaforge/envs/langchain/lib/python3.10/site-packages/llama_cpp/llama.py", line 1435, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
```

**Comment by Malrama** [comment]
Same error also happens for CUDA builds:

` -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/eashr/AppData/Local/Temp/pip-install-l_291tjm/llama-cpp-python_d9ef6902c6b8494598a2e368618fefeb/_skbuild/win-amd64-3.10/cmake-build
      [1/8] Building C object vendor\llama.cpp\CMakeFiles\ggml.dir\k_quants.c.obj
      [2/8] Building C object vendor\llama.cpp\CMakeFiles\ggml.dir\ggml.c.obj
      [3/8] Building CXX object vendor\llama.cpp\CMakeFiles\llama.dir\llama.cpp.obj
      [4/8] Building CUDA object vendor\llama.cpp\CMakeFiles\ggml.dir\ggml-cuda.cu.obj
      ggml-cuda.cu

      [5/8] Linking CUDA static library vendor\llama.cpp\ggml_static.lib
      [6/8] Linking CUDA shared library bin\ggml_shared.dll
      FAILED: bin/ggml_shared.dll vendor/llama.cpp/ggml_shared.lib
      cmd.exe /C "cmd.exe /C "C:\Users\eashr\AppData\Local\Temp\pip-build-env-jf5zs8ng\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E __create_def C:\Users\eashr\AppData\Local\Temp\pip-install-l_291tjm\llama-cpp-python_d9ef6902c6b8494598a2e368618fefeb\_skbuild\win-amd64-3.10\cmake-build\vendor\llama.cpp\CMakeFiles\ggml_shared.dir\.\exports.def C:\Users\eashr\AppData\Local\Temp\pip-install-l_291tjm\llama-cpp-python_d9ef6902c6b8494598a2e368618fefeb\_skbuild\win-amd64-3.10\cmake-build\vendor\llama.cpp\CMakeFiles\ggml_shared.dir\.\exports.def.objs && cd C:\Users\eashr\AppData\Local\Temp\pip-install-l_291tjm\llama-cpp-python_d9ef6902c6b8494598a2e368618fefeb\_skbuild\win-amd64-3.10\cmake-build" && C:\Users\eashr\AppData\Local\Temp\pip-build-env-jf5zs8ng\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E vs_link_dll --intdir=vendor\llama.cpp\CMakeFiles\ggml_shared.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x86\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx86\x64\link.exe /nologo vendor\llama.cpp\CMakeFiles\ggml.dir\ggml.c.obj vendor\llama.cpp\CMakeFiles\ggml.dir\ggml-cuda.cu.obj vendor\llama.cpp\CMakeFiles\ggml.dir\k_quants.c.obj  /out:bin\ggml_shared.dll /implib:vendor\llama.cpp\ggml_shared.lib /pdb:bin\ggml_shared.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO  /DEF:vendor\llama.cpp\CMakeFiles\ggml_shared.dir\.\exports.def  cudadevrt.lib  cudart_static.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib -LIBPATH:"C:/Users/eashr/Desktop/TextGPT/installer_files/env/lib/x64"  && cd ."
      LINK: command "C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx86\x64\link.exe /nologo vendor\llama.cpp\CMakeFiles\ggml.dir\ggml.c.obj vendor\llama.cpp\CMakeFiles\ggml.dir\ggml-cuda.cu.obj vendor\llama.cpp\CMakeFiles\ggml.dir\k_quants.c.obj /out:bin\ggml_shared.dll /implib:vendor\llama.cpp\ggml_shared.lib /pdb:bin\ggml_shared.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO /DEF:vendor\llama.cpp\CMakeFiles\ggml_shared.dir\.\exports.def cudadevrt.lib cudart_static.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib -LIBPATH:C:/Users/eashr/Desktop/TextGPT/installer_files/env/lib/x64 /MANIFEST /MANIFESTFILE:bin\ggml_shared.dll.manifest" failed (exit code 1120) with the following output:
         Bibliothek "vendor\llama.cpp\ggml_shared.lib" und Objekt "vendor\llama.cpp\ggml_shared.exp" werden erstellt.
      LINK : warning LNK4098: Standardbibliothek "LIBCMT" steht in Konflikt mit anderen Bibliotheken; /NODEFAULTLIB:Bibliothek verwenden.
      ggml-cuda.cu.obj : error LNK2019: Verweis auf nicht aufgel”stes externes Symbol "cublasCreate_v2" in Funktion "ggml_init_cublas".
      ggml-cuda.cu.obj : error LNK2019: Verweis auf nicht aufgel”stes externes Symbol "cublasSetStream_v2" in Funktion ""void __cdecl ggml_cuda_op_mul_mat_cublas(struct ggml_tensor const *,struct ggml_tensor const *,struct ggml_tensor *,char *,float *,float *,float *,__int64,__int64,__int64,int,struct CUstream_st * &)" (?ggml_cuda_op_mul_mat_cublas@@YAXPEBUggml_tensor@@0PEAU1@PEADPEAM33_J44HAEAPEAUCUstream_st@@@Z)".
      ggml-cuda.cu.obj : error LNK2019: Verweis auf nicht aufgel”stes externes Symbol "cublasSetMathMode" in Funktion "ggml_init_cublas".
      ggml-cuda.cu.obj : error LNK2019: Verweis auf nicht aufgel”stes externes Symbol "cublasSgemm_v2" in Funktion ""void __cdecl ggml_cuda_op_mul_mat_cublas(struct ggml_tensor const *,struct ggml_tensor const *,struct ggml_tensor *,char *,float *,float *,float *,__int64,__int64,__int64,int,struct CUstream_st * &)" (?ggml_cuda_op_mul_mat_cublas@@YAXPEBUggml_tensor@@0PEAU1@PEADPEAM33_J44HAEAPEAUCUstream_st@@@Z)".

      bin\ggml_shared.dll : fatal error LNK1120: 4 nicht aufgel”ste Externe

      [7/8] Linking CXX shared library bin\llama.dll
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\eashr\AppData\Local\Temp\pip-build-env-jf5zs8ng\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "C:\Users\eashr\AppData\Local\Temp\pip-build-env-jf5zs8ng\overlay\Lib\site-packages\skbuild\cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "C:\Users\eashr\AppData\Local\Temp\pip-build-env-jf5zs8ng\overlay\Lib\site-packages\skbuild\cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          'C:\Users\eashr\AppData\Local\Temp\pip-build-env-jf5zs8ng\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' --build . --target install --config Release --
        Install target:
          install
        Source directory:
          C:\Users\eashr\AppData\Local\Temp\pip-install-l_291tjm\llama-cpp-python_d9ef6902c6b8494598a2e368618fefeb
        Working directory:
          C:\Users\eashr\AppData\Local\Temp\pip-install-l_291tjm\llama-cpp-python_d9ef6902c6b8494598a2e368618fefeb\_skbuild\win-amd64-3.10\cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects`

**Comment by jppaolim** [comment]
Same here with similar output :)

**Comment by WojtekKowaluk** [comment]
0.1.63 installs fine, 0.1.64 fails.

**Comment by jllllll** [comment]
There seems to be an issue with linking required libraries on the latest version. On Windows, I can compile for cuBLAS by setting the `CUDAFLAGS` environment variable to `-lcublas` like so:
```cmd
set FORCE_CMAKE=1
set "CMAKE_ARGS=-DLLAMA_CUBLAS=on"
set "CUDAFLAGS=-lcublas"
python -m pip install git+https://github.com/abetlen/llama-cpp-python
```

**Comment by gsantopaolo** [comment]
I got the same exact error of @slavag 
I solved it by installing llama-cpp-python==0.1.63 
`CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install -U llama-cpp-python==0.1.63 --no-cache-dir`

So for anyone interested, this seems to be a regression introduced in 0.1.64

**Comment by remixer-dec** [comment]
just tried 0.1.65, installed with no errors

**Comment by abetlen** [comment]
@remixer-dec glad to hear, likely caused by the structure alignment issue in llama.cpp which was recently fixed. If anyone else can also try it and let me know if it works I'd be grateful.

Cheers.

**Comment by leuchtetgruen** [comment]
@abetlen I can confirm that 

CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install -U llama-cpp-python --no-cache-dir

now runs and installs without any error, while with 0.1.64 that was not the case. Thanks for your work.

**Comment by slavag** [comment]
Yes, 0.1.65 installed fined.
Thanks
