### ISSUE TITLE
LangFlow + llama-cpp-python + Metal build (m2 max) = fail

### ISSUE THREAD

**Issue by trivita** [abetlen/llama-cpp-python#410]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Everything should be working.

# Current Behavior

followed official Metal build method here.

LangFlow console gives:
```
llama_init_from_file: kv self size  =  400.00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '/opt/homebrew/lib/python3.10/site-packages/llama_cpp/ggml-metal.metal'
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "Compiler encountered XPC_ERROR_CONNECTION_INVALID (is the OS shutting down?)" UserInfo={NSLocalizedDescription=Compiler encountered XPC_ERROR_CONNECTION_INVALID (is the OS shutting down?)}
```
then crash.

I know this could be a bug in LangFlow but I think it's also worth mentioning here.

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

Macbook Pro M2 Max

* Operating System, e.g. for Linux:

Ventura 13.4

* SDK version, e.g. for Linux:

```
Python 3.10.12
GNU Make 3.81
```

**Comment by gjmulder** [comment]
The error looks to be from `llama.cpp` and specific to the Apple Metal code.

**Comment by trivita** [comment]
> The error looks to be from `llama.cpp` and specific to the Apple Metal code.

i also have a METAL build of llama.cpp running without any problem.
so i guess this something in llama-cpp-python or between llama-cpp-python and langflow.

**Comment by gjmulder** [comment]
```
llama.cpp$ egrep -R ggml_metal_init .
./ggml-metal.h:struct ggml_metal_context * ggml_metal_init(void);
./ggml-metal.m:struct ggml_metal_context * ggml_metal_init(void) {
```

Have you confirmed that the git hash of your `llama.cpp` and and the one in `llama-cpp-python/vendor/llama.cpp` are similar in date?

```
llama.cpp$ git log | head -3
commit bbca06e26949686d61a5126332680ba3cccf235c
Author: Johannes Gäßler <johannesg@5d6.de>
Date:   Wed Jun 21 23:49:25 2023 +0200
```

**Comment by trivita** [comment]
i think it might be an issue coming from langflow.
```
python3 -m llama_cpp.server --model $MODEL  --n_gpu_layers 1
```
runs without any problem.

**Comment by trivita** [comment]
i think it might be an issue coming from langflow.
```
python3 -m llama_cpp.server --model $MODEL  --n_gpu_layers 1
```
runs without any problem.

ps, langflow seems to have fixed this issue in a recent update.

thank you. i'm closing this issue.

**Comment by aka-awasthi** [comment]
@trivita  i know its closed but want to highlight some findings.  
Scenario with Langflow --> With metal GPU, langflow (latest) will not work
llama-cpp-python = 0.2.6
langchain=0.0.256
langflow=0.4.19

working with cpu installation of llama-cpp and giving response in 1-2 mins.
llama-cpp-python=0.1.81
langflow=0.4.19
langchain=0.0.256

Scenario without Langflow --> But on terminal if you build with only langchain and llama-cpp-python (with metal gpu it is working and giving response in 5 secs)
llama-cpp-python=0.2.6
langchain=0.0.274

issue is bascially langflow doesnt support version higher than 0.0.256 of langchain.  if langflow supports 0.0.274 of langchain ,metal gpu will work really awesome and langflow Ui will give resposne much much faster.
System Used is M1 pro 32gb.
