### ISSUE TITLE
The maximum full path to an object file is 250     characters (see CMAKE_OBJECT_PATH_MAX) in Windows 10

### ISSUE THREAD

**Issue by ye-ye823** [abetlen/llama-cpp-python#426]
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [173 lines of output]

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.36.32535.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.36.32535.0
      CMake Warning (dev) at C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-5nvkko6t/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:168 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-5nvkko6t/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:189 (elseif):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Detecting CXX compiler ABI info
      CMake Warning in C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-9hc2hon2/llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-zol2p4/CMakeLists.txt:
        The object file directory

          C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-9hc2hon2/llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-zol2p4/CMakeFiles/cmTC_93b22.dir/./

        has 225 characters.  The maximum full path to an object file is 250
        characters (see CMAKE_OBJECT_PATH_MAX).  Object file

          CMakeCXXCompilerABI.cpp.obj

        cannot be safely placed under this directory.  The build may not work
        correctly.

      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (1.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-9hc2hon2/llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-9hc2hon2\llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7\_skbuild\win-amd64-3.11\cmake-build
        Command:
          'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-9hc2hon2\llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7' -G Ninja '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\ninja\data\bin\ninja' -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-9hc2hon2\llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7\_skbuild\win-amd64-3.11\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPYTHON_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython3_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython3_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\ninja\data\bin\ninja' -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.36.32535.0
      -- The CXX compiler identification is MSVC 19.36.32535.0
      -- Detecting C compiler ABI info
      CMake Warning in C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-9hc2hon2/llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-7vp2kl/CMakeLists.txt:
        The object file directory

          C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-9hc2hon2/llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-7vp2kl/CMakeFiles/cmTC_bb06a.dir/./

        has 235 characters.  The maximum full path to an object file is 250
        characters (see CMAKE_OBJECT_PATH_MAX).  Object file

          CMakeCCompilerABI.c.obj

        cannot be safely placed under this directory.  The build may not work
        correctly.

      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe
      CMake Warning in C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-9hc2hon2/llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-8em1t8/CMakeLists.txt:
        The object file directory

          C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-9hc2hon2/llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-8em1t8/CMakeFiles/cmTC_fac45.dir/./

        has 235 characters.  The maximum full path to an object file is 250
        characters (see CMAKE_OBJECT_PATH_MAX).  Object file

          testCCompiler.c.obj

        cannot be safely placed under this directory.  The build may not work
        correctly.

      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - broken
      CMake Error at C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-5nvkko6t/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-9hc2hon2/llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-8em1t8

          Run Build Command(s):C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-5nvkko6t/overlay/Lib/site-packages/ninja/data/bin/ninja -v cmTC_fac45 && [1/2] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx86\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\cmTC_fac45.dir\testCCompiler.c.obj /FdCMakeFiles\cmTC_fac45.dir\ /FS -c C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-9hc2hon2\llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8em1t8\testCCompiler.c
          [2/2] cmd.exe /C "cd . && C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_fac45.dir --rc=D:\WINDOW~1\10\bin\100203~1.0\x86\rc.exe --mt=D:\WINDOW~1\10\bin\100203~1.0\x86\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx86\x64\link.exe /nologo CMakeFiles\cmTC_fac45.dir\testCCompiler.c.obj  /out:cmTC_fac45.exe /implib:cmTC_fac45.lib /pdb:cmTC_fac45.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
          FAILED: cmTC_fac45.exe
          cmd.exe /C "cd . && C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_fac45.dir --rc=D:\WINDOW~1\10\bin\100203~1.0\x86\rc.exe --mt=D:\WINDOW~1\10\bin\100203~1.0\x86\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx86\x64\link.exe /nologo CMakeFiles\cmTC_fac45.dir\testCCompiler.c.obj  /out:cmTC_fac45.exe /implib:cmTC_fac45.lib /pdb:cmTC_fac45.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
          RC Pass 1: command "D:\WINDOW~1\10\bin\100203~1.0\x86\rc.exe /fo CMakeFiles\cmTC_fac45.dir/manifest.res CMakeFiles\cmTC_fac45.dir/manifest.rc" failed (exit code 2) with the following output:
          Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384

          Copyright (C) Microsoft Corporation.  All rights reserved.

          CMakeFiles\cmTC_fac45.dir/manifest.rc(3) : error RC2136 : missing '=' in EXSTYLE=<flags>

          ninja: build stopped: subcommand failed.

        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (project)

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
                ^^^^^^^^^^^^^^^
        File "C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-9hc2hon2\llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7' -G Ninja '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\ninja\data\bin\ninja' -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-9hc2hon2\llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7\_skbuild\win-amd64-3.11\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPYTHON_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython3_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython3_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-5nvkko6t\overlay\Lib\site-packages\ninja\data\bin\ninja' -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-9hc2hon2\llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7
        Working directory:
          C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-9hc2hon2\llama-cpp-python_fee3700de0cb407aa137ad46a15dfcb7\_skbuild\win-amd64-3.11\cmake-build
      Please see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by gjmulder** [comment]
OS bug.
