### ISSUE TITLE
On m1 mac, after install, running and navigating to local URL I get error "{"detail":"Not Found"}"

### ISSUE THREAD

**Issue by dogjamboree** [abetlen/llama-cpp-python#43]
Everything worked without errors but the web page says:
{"detail":"Not Found"}

Console shows the following:
INFO:     Started server process [4194]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     ::1:58413 - "GET / HTTP/1.1" 404 Not Found

The only thing I didn't understand about the install process was what was supposed to go in the brackets for [server] in the command pip "install llama-cpp-python[server]". Could that have caused a problem?

llama.cpp works perfectly standalone BTW.

**Comment by abetlen** [comment]
Nope you just missed the `/docs` part of the url to get to the swagger ui try http://localhost:8000/docs

**Comment by dogjamboree** [comment]
Ahhh...that worked. THanks!!
