### ISSUE TITLE
Not unload a model from VRAM anymore.

### ISSUE THREAD

**Issue by berkut1** [abetlen/llama-cpp-python#434]
The last version 0.1.66, not unload model from VRAM.
I thought the problem was with oobabooga/text-generation-webui https://github.com/oobabooga/text-generation-webui/issues/2920, but after digging into the code from projects, I think the problem is with this library.
I think there https://github.com/abetlen/llama-cpp-python/blob/442213b070e579774c0374d6150fc38e0b3c978d/llama_cpp/llama.py#L1439 should be added a new `llama_free_model` function.

Sorry if I'm wrong, I don't work with python.

**Comment by abetlen** [comment]
@berkut1 thank you for caching that, will have publish a new version shortly

**Comment by iactix** [comment]
It still only "deletes" the model though, VRAM still ends up a lot higher than before loading the model.
https://github.com/abetlen/llama-cpp-python/issues/223
