### ISSUE TITLE
Please add config how to change ip:port(already 8000)

### ISSUE THREAD

**Issue by j0schihatake** [abetlen/llama-cpp-python#445]
Good afternoon, sorry to bother you, but this solution is very interesting. True, I come across such a stack trace when I collect the image myself:
PS D:\Develop\NeuronNetwork\llama_cpp\llama_cpp_java> docker run -dit --name llamaserver -p 221:22 -p 8082:8000 -v D:/Develop/NeuronNetwork/llama_cpp/llama_cpp_java/model/wizardLM-7B.ggmlv3.q4_0.bin:/home/llama-cpp-user/mo
del/wizardLM-7B.ggmlv3.q4_0.bin  --gpus all --restart unless-stopped llamaserver:latest
dee0a672cf6d6786ac925a16b9e9aaf326abf99aeee5c69530a6a96fa3b53aaf
PS D:\Develop\NeuronNetwork\llama_cpp\llama_cpp_java> docker container attach llamaserver
llama-cpp-user@dee0a672cf6d:~/llama.cpp$ python3 -m llama_cpp.server --model /home/llama-cpp-user/model/wizardLM-7B.ggmlv3.q4_0.bin
llama.cpp: loading model from /home/llama-cpp-user/model/wizardLM-7B.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: mem required  = 5407.72 MB (+ 1026.00 MB per state)
warning: failed to mlock 73732096-byte buffer (after previously locking 73748480 bytes): Cannot allocate memory
Try increasing RLIMIT_MLOCK ('ulimit -l' as root).
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
INFO:     Started server process [8]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 8000, 0, 0): cannot assign requested address
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

i am trying to change the port by redirect in docker command but the output is not changing. Please tell me what I can be wrong?

**Comment by j0schihatake** [comment]
I downloaded your finished image and I'm studying it, maybe I can fix everything myself, thanks

**Comment by JoNoahBros** [comment]
Hello j0schihatake, did you find the way how to fix this issue? Thanks
