### ISSUE TITLE
stream generation slowing down massively, when the context lenght is shorter that the previous one

### ISSUE THREAD

**Issue by KocWozniakPiotr** [abetlen/llama-cpp-python#448]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

So after about two weeks of pause I returned back to my chat-bot project. Basicaly my prompt is being cropped at the end, every time the context reaches a particular size to avoid exceeding `n_ctx` .
I'm using a simple code for that in addition to `Lamma.tokenize()`

```
   def question_request(usr, new_prompt, connection):
    bot.usr = usr
    response_queue = Queue()

    bot.set_context(new_prompt)

    while True:
        memory_tokens_len = len(llm.tokenize(bot.context.encode(encoding="utf-8")))
        print("current tokens:", memory_tokens_len)
        if memory_tokens_len >= (bot.ctx_size_allowed - bot.answer_size):
            bot.trim_short_memory()
        else:
            break

    t = threading.Thread(target=generate, args=(response_queue,))
    t.start()

    while True:
        response = response_queue.get()
        if response == "< quit >":
            bot.append_memory()
            break
        elif response != "":
            connection.send(response.encode())
```

I run this just before generating the actuall content from prompt. Until now it worked blazing fast without problems.

# Current Behavior

I don't really know how to debug the issue because I see no errors or such. 
The use of tokenize
What I can confirm is that tokenize() is still tokenizing fast... it's just that what happens afterwards inside `generate()`

```
def generate(response_queue):
    stream = llm(bot.context, stop=["?\n", "###", f"{bot.usr}:", f"{bot.name}:"], temperature=0.7, repeat_penalty=1.1,
                 presence_penalty=0, frequency_penalty=0, top_k=40, tfs_z=1, top_p=0.95, max_tokens=bot.answer_size,
                 stream=True)

    for output in stream:
        word = output['choices'][0]['text']
        bot.collect_words(word)
        if word == "\n":
            word = "<br>"
        response_queue.put(word)
    response_queue.put("< quit >")
```

Is anyone experiencing same issues?

`$ llama-cpp-python 0.1.67 `
`$ llama-cpp-python 0.1.68 `

* Operating System, e.g. for Linux:

`$ Fedora 38 6.3.7-200.fc38.x86_64`

* SDK version, e.g. for Linux:

```
$ python3.11
```

**Comment by KocWozniakPiotr** [comment]
eval time went from 2 seconds to 12 seconds for some reason, when using tokenize before generating prompt:

```
llama_print_timings:        load time =  4827.12 ms
llama_print_timings:      sample time =    13.39 ms /    18 runs   (    0.74 ms per token,  1344.19 tokens per second)
llama_print_timings: prompt eval time =   715.99 ms /    11 tokens (   65.09 ms per token,    15.36 tokens per second)
llama_print_timings:        eval time =  2014.16 ms /    17 runs   (  118.48 ms per token,     8.44 tokens per second)
llama_print_timings:       total time =  2838.75 ms
Llama.generate: prefix-match hit
current tokens: 281
migrating temp memory...
current tokens: 209

llama_print_timings:        load time =  4827.12 ms
llama_print_timings:      sample time =    78.05 ms /   105 runs   (    0.74 ms per token,  1345.38 tokens per second)
llama_print_timings: prompt eval time =  8851.12 ms /   144 tokens (   61.47 ms per token,    16.27 tokens per second)
llama_print_timings:        eval time = 12267.04 ms /   104 runs   (  117.95 ms per token,     8.48 tokens per second)
llama_print_timings:       total time = 21557.65 ms
```

**Comment by gjmulder** [comment]
Can you watch your CPU and memory utilisation as your code is running  e.g. using `top` or `atop 3`?

`llama.cpp` is multi-threaded so you should see it using 70-100% of the number of cores you configure when initializing the model (e.g. on a 4 core system you would expect to see 3 to 4 cores busy, i.e. about 300-400% CPU). I'm guessing the the tokenizer is single-threaded so you should see a single thread running at 100% CPU. Try to log each step your code is doing so you can correlate it to your performance monitoring. Note that `top` refreshes by default every 3 seconds, and the `atop` command above changes `atop` from its default 10 second refresh.

Finally, watch your memory utilisation. If you see `kswapd` running and your swap utilisation changing, it implies that the model is taking up so much memory that any other python memory allocation (e.g. for tokenization) requires Fedora to swap.

**Comment by gjmulder** [comment]
> eval time went from 2 seconds to 12 seconds for some reason, when using tokenize before generating prompt:
> 
> ```
> llama_print_timings:        load time =  4827.12 ms
> llama_print_timings:      sample time =    13.39 ms /    18 runs   (    0.74 ms per token,  1344.19 tokens per second)
> llama_print_timings: prompt eval time =   715.99 ms /    11 tokens (   65.09 ms per token,    15.36 tokens per second)
> llama_print_timings:        eval time =  2014.16 ms /    17 runs   (  118.48 ms per token,     8.44 tokens per second)
> llama_print_timings:       total time =  2838.75 ms
> Llama.generate: prefix-match hit
> current tokens: 281
> migrating temp memory...
> current tokens: 209
> 
> llama_print_timings:        load time =  4827.12 ms
> llama_print_timings:      sample time =    78.05 ms /   105 runs   (    0.74 ms per token,  1345.38 tokens per second)
> llama_print_timings: prompt eval time =  8851.12 ms /   144 tokens (   61.47 ms per token,    16.27 tokens per second)
> llama_print_timings:        eval time = 12267.04 ms /   104 runs   (  117.95 ms per token,     8.48 tokens per second)
> llama_print_timings:       total time = 21557.65 ms
> ```

Also note this is not an apples-to-apples performance comparison. Your tokens per second for all of sample, prompt eval, and eval time are close to identical. The number of tokens being processed is different. More tokens = more time.

**Comment by KocWozniakPiotr** [comment]
> > eval time went from 2 seconds to 12 seconds for some reason, when using tokenize before generating prompt:
> > ```
> > llama_print_timings:        load time =  4827.12 ms
> > llama_print_timings:      sample time =    13.39 ms /    18 runs   (    0.74 ms per token,  1344.19 tokens per second)
> > llama_print_timings: prompt eval time =   715.99 ms /    11 tokens (   65.09 ms per token,    15.36 tokens per second)
> > llama_print_timings:        eval time =  2014.16 ms /    17 runs   (  118.48 ms per token,     8.44 tokens per second)
> > llama_print_timings:       total time =  2838.75 ms
> > Llama.generate: prefix-match hit
> > current tokens: 281
> > migrating temp memory...
> > current tokens: 209
> > 
> > llama_print_timings:        load time =  4827.12 ms
> > llama_print_timings:      sample time =    78.05 ms /   105 runs   (    0.74 ms per token,  1345.38 tokens per second)
> > llama_print_timings: prompt eval time =  8851.12 ms /   144 tokens (   61.47 ms per token,    16.27 tokens per second)
> > llama_print_timings:        eval time = 12267.04 ms /   104 runs   (  117.95 ms per token,     8.48 tokens per second)
> > llama_print_timings:       total time = 21557.65 ms
> > ```
> 
> Also note this is not an apples-to-apples performance comparison. Your tokens per second for all of sample, prompt eval, and eval time are close to identical. The number of tokens being processed is different. More tokens = more time.

Thank you for the suggestions!
I simply wanted to show some output to outline my approach. 
When it comes to my specs and monitoring resources:
- I use: 6c/12t ryzen5 4600HS with 16GB ram
- the utilization of ram never goes above 8-9GB ram
- I'm using Wizard-Vicuna-7B_qK_M model 

I did actually experiment with reducing `n_threads` already. It doesn't have impact on the current issue. Regardless if I use less of my max available cpu threads.

When I reach the context limit and `trim_temp_memory` reduces the size of context to tokenize it does choke the `generate()` thread thought. In fact so much that it doesn't send chunks of tokens back to my web-ui gradually but all at once! I'm running my `generate()` function as a separate thread, otherwise sending tokens over socket wouldn't work on the fly.

What I did notice is, when putting `tokenize()` outside of my loop doesn't affect the prompt generation at all. 
I mean each time when I generate something (increaze the context size) regardless of `memory_tokens_len` statement in my "if case" .

I just added trimming context feature. My `trim_short_memory()` function removes the oldest generated QA from the context... nothing fancy for now. I didn't have it implemented 2 weeks ago.


```
    def trim_short_memory(self):
        print("migrating temp memory...")
        with open(f'ai_{self.name}.mem', "a") as file:
            file.seek(0, 2)
            file.write(f"""{self.temp_memory.pop(0)}\n""")
            file.close()
        self.context = f"""{self.default_part()} {''.join(self.temp_memory)}"""
```


So now I'm 100% sure it has something to do with `tokenize()` tokenizing a context smaller than the previous one... but why? Why does it influence the generation time by so much? I find it so strange.

Steadily increasing the context size while using tokenize() has **absolutely** no impact. 
This is strange for me but I'm not familiar with the `Llama` mechanics behind it, so I apologize if I might sound stupid asking such questions.

**Comment by gjmulder** [comment]
I can help you diagnose `llama.cpp` specific performance issues, but I will have to defer to @abetlen for the internals on how `llama-cpp-python` and `llama.cpp` interact.

`n_threads` defaults (from memory) to half the number of hypercores on your system, namely the number of physical cores on your system which for `llama.cpp` is close to optimal. Whether `llama.cpp` actually utilises all of the cores is a different matter. On my 16 core system with GPU acceleration I usually see around 1300% CPU. 1600% CPU without GPU acceleration.

**Comment by KocWozniakPiotr** [comment]
Thank you for your help!

I did further testing and this looks like solely a problem while using a `stream`. 
When I just disable `stream` and use `echo` to return the output, it doesn't matter if the context got smaller .
As I already said - this happens ONLY when tokenizing something before generation.

Also It would be great if the stream returned this:

```
 "usage": {
    "prompt_tokens": 1234,
  }
```

just like it returns it when stream is disabled. That way  we could get additional useful information about the tokens. I wonder why wasn't it implemented it the first place? Performance?
