### ISSUE TITLE
Confusing assortment of llama cpp python binding packages.. 

### ISSUE THREAD

**Issue by linuxmagic-mp** [abetlen/llama-cpp-python#455]
```
python3 -m pip show llamacpp
Name: llamacpp
Version: 0.1.14
Summary: Python bindings for @ggerganov's llama.cpp
Home-page: https://github.com/thomasantony/llamacpp-python
Author: 
Author-email: Thomas Antony <mail@thomasantony.com>
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by:

python3 -m pip show llama_cpp_python
Name: llama-cpp-python
Version: 0.1.68
Summary: A Python wrapper for llama.cpp
Home-page: 
Author: Andrei Betlen
Author-email: abetlen@gmail.com
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: diskcache, numpy, typing-extensions
Required-by:
```
Both projects trying to do the same thing? Maybe since they aren't working as actively on llamacpp-python, could be a time to unify?

**Comment by abetlen** [comment]
Hey @linuxmagic-mp there's actually even more than just those two bindings yes.

I have a short section in the README on what my goals are and how this project is different from some of the other bindings but the long and short of it is:

- At a low-level this project is based on python's built-in ctypes module while most other's I've seen use pybind11. The main benefit of ctypes is that it's quite a bit easier to maintain so this project is fairly up-to-date with llama.cpp. The other benefit is that if you're familiar with the c api for llama.cpp and how to use ctypes you can use the low-level bindings and build you're own systems that don't need to use the "high-level" Llama class so it's a little more hacker friendly in that regard.
- The other big feature of this project is the drop-in openai server compatibility, this has made it fairly easy to drop this project into existing apps like LangChain, Microsoft Guidance, etc.

Hope that answers your question!

Cheers.
