### ISSUE TITLE
Models not working on version 0.1.69, fail with an exception: Requested tokens (85) exceed context window of 2048

### ISSUE THREAD

**Issue by Kenshiro-28** [abetlen/llama-cpp-python#462]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

When I send a prompt to the model should receive a response (using version 0.1.69)

# Current Behavior

It generates an exception:

"Requested tokens (85) exceed context window of 2048"

# Environment and Context

* Physical (or virtual) hardware you are using, e.g. for Linux: 

AMD Ryzen 5 3600 6-Core Processor

* Operating System, e.g. for Linux:

Debian 12

Linux 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.37-1 (2023-07-03) x86_64 GNU/Linux

* SDK version, e.g. for Linux:

Python 3.11.2
GNU Make 4.3
g++ (Debian 12.2.0-14) 12.2.0

# Failure Information (for bugs)

It generates an exception:

"Requested tokens (85) exceed context window of 2048"

# Steps to Reproduce

1. Just call the model with a normal prompt:
...
MAX_TOKENS = 2048
...
model = Llama(model_path = modelFile, n_ctx = MAX_TOKENS)
...
response = model(text, max_tokens = MAX_TOKENS - text_tokens)

The code I'm using works fine in previous versions.

**Comment by gjmulder** [comment]
See #416

**Comment by Kenshiro-28** [comment]
I'm using models of 2048 tokens, requesting a context of the same size. It fails even with Wizard-Vicuna:

https://huggingface.co/TheBloke/Wizard-Vicuna-7B-Uncensored-GGML

**Comment by gjmulder** [comment]
```
$ grep -B 2 -ir "exceed context window of" llama_cpp/llama.py
        if len(prompt_tokens) > self._n_ctx:
            raise ValueError(
                f"Requested tokens ({len(prompt_tokens)}) exceed context window of {self._n_ctx}"
```

**Comment by Kenshiro-28** [comment]
In current version of the file, I see 2 cases:

if max_tokens <= 0:
    # Unlimited, depending on n_ctx.
    if len(prompt_tokens) >= int(llama_cpp.llama_n_ctx(self.ctx)):
        raise ValueError(
            f"Requested tokens exceed context window of {llama_cpp.llama_n_ctx(self.ctx)}"
        )
    else:
        max_tokens = int(llama_cpp.llama_n_ctx(self.ctx)) - len(prompt_tokens)
elif len(prompt_tokens) + max_tokens > int(llama_cpp.llama_n_ctx(self.ctx)):
    raise ValueError(
        f"Requested tokens ({len(prompt_tokens)}) exceed context window of {self._n_ctx}"
    )

**Comment by gjmulder** [comment]
Sorry. My mistake. I was working on a branch and hadn't pulled in the latest updates.

Here's the PR #385

**Comment by Kenshiro-28** [comment]
Ok, thx! :) will it be fixed in 0.1.70?

**Comment by gjmulder** [comment]
Not by me.

**Comment by abetlen** [comment]
@Kenshiro-28 yes I'll revert this back so that it just truncates max_tokens by default to the context length, this was change in a recent PR.

**Comment by Kenshiro-28** [comment]
@abetlen great, thank you! :)
