### ISSUE TITLE
Wrong size of embeddings

### ISSUE THREAD

**Issue by djpadbit** [abetlen/llama-cpp-python#47]
While playing around, I noticed the embeddings are only 512 floats rather than the 4096 you get when using the standalone application. 

So I went digging and I found the culprit which was a copy-paste residue in the function `llama_n_embd`
https://github.com/abetlen/llama-cpp-python/blob/6d1bda443e2f52b080c4c9156d35ff693857609b/llama_cpp/llama_cpp.py#L220-L221
It's calling `llama_n_ctx` rather than `llama_n_embd`.

I don't think this warrants a pull request as it is a very easy issue to fix, so I made a simple issue instead.

Keep up the good work :)

**Comment by abetlen** [comment]
Woops, thanks for pointing this out!
