### ISSUE TITLE
Multi-threading concurrency, error reported 

### ISSUE THREAD

**Issue by sevenold** [abetlen/llama-cpp-python#471]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

llama-cpp-python-0.1.70

```python

from llama_cpp import Llama


llm = Llama(model_path=settings.buddy_7b_path, n_gpu_layers=32)


from concurrent.futures import ThreadPoolExecutor

data = ['User:你好\nAssistant:'] * 2
with ThreadPoolExecutor() as executor:
    for _ in executor.map(llm, data):
        print(_)


```
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9
llama.cpp: loading model from /data/seven/models/openbuddy-7b-v1.3-q5_1/7b-v1.3-q5_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 37498
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 2011.81 MB (+ 1026.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 288 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloaded 32/35 layers to GPU
llama_model_load_internal: total VRAM used: 4921 MB
llama_new_context_with_model: kv self size  =  256.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
GGML_ASSERT: /tmp/pip-install-zhv2qv6m/llama-cpp-python_cc53a980d17f4ac2ba6c6bd76b6690aa/vendor/llama.cpp/ggml.c:14571: tensor->src1 == NULL || tensor->src1->backend == GGML_BACKEND_CPU
Aborted (core dumped)
```log


```

**Comment by gjmulder** [comment]
That's a `llama.cpp` error. I suspect `llama.cpp` is not thread-safe.

**Comment by litetoooooom** [comment]
M

**Comment by abetlen** [comment]
@sevenold yes as @gjmulder points out the llama.cpp model itself is not thread-safe in this way, you can use a ProcessPool but this will increase memory usage.

**Comment by sevenold** [comment]
https://github.com/marella/ctransformers/issues/38#issuecomment-1613627309

**Comment by liuzhipengchd** [comment]
你好，这个问题你解决了没
