### ISSUE TITLE
error loading model: unexpectedly reached end of file

### ISSUE THREAD

**Issue by jaymon0703** [abetlen/llama-cpp-python#476]
Any ideas why i may be getting this error when models directory has the model?

![image](https://github.com/abetlen/llama-cpp-python/assets/4340156/9883bc27-2a57-4526-8dde-194a702ea09a)

**Comment by jaymon0703** [comment]
Please see https://github.com/abetlen/llama-cpp-python/issues/399 for environment and context

**Comment by Azeirah** [comment]
I don't understand. I ran the commands in the last post in the referenced issue and I'm still getting "error loading m omdel: unexpectedly reached end of file".

My model exists at the specified path. I built with cuBLAS, FORCE_CMAKE=1

**Comment by jaymon0703** [comment]
Try using just `!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python --no-cache-dir --user` and make sure you are using a compatible model...like this one works for me - https://huggingface.co/TheBloke/LLaMa-7B-GGML/resolve/main/llama-7b.ggmlv3.q4_0.bin
