### ISSUE TITLE
Disable llama.cpp output

### ISSUE THREAD

**Issue by Freed-Wu** [abetlen/llama-cpp-python#478]
How to disable the following output? I try `verbose=False`, but there is still some outputs.

```
llama.cpp: loading model from XXX.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 9130.33 MB (+ 1608.00 MB per state)
llama_new_context_with_model: kv self size  =  400.00 MB
```

**Comment by gjmulder** [comment]
Related to #364

**Comment by abetlen** [comment]
@Freed-Wu I've tried a few options like `contextlib.redirect_stderr` but that doesn't seem to work, I believe this needs to be done inside llama.cpp

**Comment by mendhak** [comment]
Aw that's a shame, I did find a similar [this discussion thread](https://github.com/ggerganov/llama.cpp/discussions/1758) which says when running llama.cpp directly you can redirect stderr. 

    ./main 2>/dev/null

So I'd have thought your `contextlib.redirect_stderr` makes sense but I'm not any kind of CPP/Python expert. 

Similarly when running a Python script with llama-cpp-python, I suppose I could do this workaround:

    python3 testing.py 2>/dev/null

or output to an error file.

**Comment by mendhak** [comment]
Found a [workaround](https://stackoverflow.com/a/50438156/974369)! This should suppress stuff being output to stderr even from the CPP library, but still throw an exception if something goes wrong.  Declare this class then use it `with` this library.

```python
import os
import sys

class suppress_stdout_stderr(object):
    def __enter__(self):
        self.outnull_file = open(os.devnull, 'w')
        self.errnull_file = open(os.devnull, 'w')

        self.old_stdout_fileno_undup    = sys.stdout.fileno()
        self.old_stderr_fileno_undup    = sys.stderr.fileno()

        self.old_stdout_fileno = os.dup ( sys.stdout.fileno() )
        self.old_stderr_fileno = os.dup ( sys.stderr.fileno() )

        self.old_stdout = sys.stdout
        self.old_stderr = sys.stderr

        os.dup2 ( self.outnull_file.fileno(), self.old_stdout_fileno_undup )
        os.dup2 ( self.errnull_file.fileno(), self.old_stderr_fileno_undup )

        sys.stdout = self.outnull_file        
        sys.stderr = self.errnull_file
        return self

    def __exit__(self, *_):        
        sys.stdout = self.old_stdout
        sys.stderr = self.old_stderr

        os.dup2 ( self.old_stdout_fileno, self.old_stdout_fileno_undup )
        os.dup2 ( self.old_stderr_fileno, self.old_stderr_fileno_undup )

        os.close ( self.old_stdout_fileno )
        os.close ( self.old_stderr_fileno )

        self.outnull_file.close()
        self.errnull_file.close()

from llama_cpp import Llama

suppress_stdout_stderr()

def load_model_and_do_something():
    with suppress_stdout_stderr():
        llm = Llama(model_path="./models/7B/ggml-model-q4_0.bin")
        output = llm("Q: Name the planets in the solar system? A: ", max_tokens=250, stop=["Q:", "\n"], echo=False)
    print(output['choices'][0]['text'])


if __name__ == "__main__":
    load_model_and_do_something()

```

![image](https://github.com/abetlen/llama-cpp-python/assets/746276/a33dc258-bce9-4be5-ade4-466c99374bed)

**Comment by abetlen** [comment]
@mendhak that works! Thank you, I've added it to the `Llama` class and will push an update shortly, there's still some unintended output when calling `llama_backend_init` but I'll work on a fix for that as well.

**Comment by mendhak** [comment]
Good to know! Ah yeah I've noticed that there's still some extra output during the `from llama_cpp import Llama` if it was built for GPU. In that case I also had to put the import into the suppress bit. 

```python
def load_model_and_do_something():
    with suppress_stdout_stderr():
        from llama_cpp import Llama
        llm = Llama(model_path="./models/7B/ggml-model-q4_0.bin")
        output = llm("Q: Name the planets in the solar system? A: ", max_tokens=250, stop=["Q:", "\n"], echo=False)
    print(output['choices'][0]['text'])

```

**Comment by abetlen** [comment]
@mendhak I the solution is to just move llama_init_backend into the Llama class and for the high level api, this should also give users more control if e.g. they want to enable NUMA cores

**Comment by DomainFlag** [comment]
Alternatively, you can use the following solution:

You just have to replace the static global logger in `llama.cpp` lib.

```python
import ctypes

from llama_cpp import llama_log_set

def my_log_callback(level, message, user_data):
    pass

log_callback = ctypes.CFUNCTYPE(None, ctypes.c_int, ctypes.c_char_p, ctypes.c_void_p)(my_log_callback)
llama_log_set(log_callback, ctypes.c_void_p())
```
