### ISSUE TITLE
Running server gives error when using huggingface model

### ISSUE THREAD

**Issue by djaffer** [abetlen/llama-cpp-python#48]
850     return issubclass(cls.__origin__, self.__origin__)
    851 if not isinstance(cls, _GenericAlias):
--> 852     return issubclass(cls, self.__origin__)
    853 return super().__subclasscheck__(cls)

TypeError: issubclass() arg 1 must be a class

The manual package works with the model not huggingface

https://huggingface.co/eachadea/ggml-vicuna-13b-4bit/resolve/main/ggml-vicuna-13b-4bit-rev1.bin

**Comment by djaffer** [comment]
Downloaded from huggingface

**Comment by MillionthOdin16** [comment]
I'm not sure what the solution is, did you try it and get it work? I had a similar issue and I think it did fix mine.

**Comment by gjmulder** [comment]
Can this issue be closed?

**Comment by djaffer** [comment]
no just left it. Didn't have much time to continue messing arround.

**Comment by gjmulder** [comment]
Please reopen when you have time.
