### ISSUE TITLE
Add support for OpenAI-style functions

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#494]
**Constrained Sampling**
- [x] Json
- [x] [JsonSchema](https://json-schema.org/understanding-json-schema/reference/index.html)

**Fine-tuned Models**

**Comment by adrianlyjak** [comment]
Grammar based sampling should help https://github.com/ggerganov/llama.cpp/pull/1773

**Comment by jasoncaojingren** [comment]
Any update about this feature?

**Comment by c0sogi** [comment]
@abetlen This one should help:
https://github.com/abetlen/llama-cpp-python/pull/572
