### ISSUE TITLE
Llama v2 support

### ISSUE THREAD

**Issue by rlancemartin** [abetlen/llama-cpp-python#497]
I'm sure this is the obvious question, so sorry if this is a duplicate. Raw format for Llama-v2 cannot be loaded out-of-the box:
```
from llama_cpp import Llama
llm = Llama(model_path="/Users/rlm/Desktop/Code/llama/llama-2-7b-chat/consolidated.00.pth")
```

Result:
```
AssertionError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 llm = Llama(model_path="/Users/rlm/Desktop/Code/llama/llama-2-7b-chat/consolidated.00.pth")

File ~/anaconda3/lib/python3.10/site-packages/llama_cpp/llama.py:305, in Llama.__init__(self, model_path, n_ctx, n_parts, n_gpu_layers, seed, f16_kv, logits_all, vocab_only, use_mmap, use_mlock, embedding, n_threads, n_batch, last_n_tokens_size, lora_base, lora_path, low_vram, tensor_split, rope_freq_base, rope_freq_scale, verbose)
    300     raise ValueError(f"Model path does not exist: {model_path}")
    302 self.model = llama_cpp.llama_load_model_from_file(
    303     self.model_path.encode("utf-8"), self.params
    304 )
--> 305 assert self.model is not None
    307 self.ctx = llama_cpp.llama_new_context_with_model(self.model, self.params)
    309 assert self.ctx is not None

AssertionError: 
```

Anyone have linked to converted files?

**Comment by rlancemartin** [comment]
> Fyi, [TheBloke](https://huggingface.co/TheBloke) already converted & uploaded the model: https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML -> works for me ^^

Oh, cool. I Will check there.

**Comment by abetlen** [comment]
@rlancemartin let me know if those models work out of the box, I'm currently working on some changes to better support the chat models (I think there's some changes that need to be made to tokenization)

**Comment by rlancemartin** [comment]
> @rlancemartin let me know if those models work out of the box, I'm currently working on some changes to better support the chat models (I think there's some changes that need to be made to tokenization)

Ya, it did. Pretty cool. I added an example [here](https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llamacpp):

```
# Make sure the model path is correct for your system!
llm = LlamaCpp(
    model_path="/Users/rlm/Desktop/Code/llama/llama-2-7b-ggml/llama-2-7b-chat.ggmlv3.q4_0.bin",
    input={"temperature": 0.75, "max_length": 2000, "top_p": 1},
    callback_manager=callback_manager,
    verbose=True,
)
```

**Comment by shaowei-su** [comment]
Anyone loaded `TheBloke/Llama-2-70B-Chat-GGML` successfully?

**Comment by denizkenan** [comment]
> Anyone loaded `TheBloke/Llama-2-70B-Chat-GGML` successfully?

yep. this one to be precise: https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGML

**Comment by shaowei-su** [comment]
> yep.

Would you mind sharing your hardware setups etc..? thanks
