### ISSUE TITLE
Pointing to an existing infernce 

### ISSUE THREAD

**Issue by davidLif** [abetlen/llama-cpp-python#512]
Is there a way to point the library to an existing llama.cpp instance instead of having the pip installation downloading and building llama.cpp on its own?

**Comment by abetlen** [comment]
@davidLif yes you should be able to use the `LLAMA_CPP_LIB` environment variable to override the version that's built with the installation.

**Comment by charles-dyfis-net** [comment]
Can we prevent any copy from being built with the installation at all, without needing to rip skbuild/cmake/&c out of the source tree?

**Comment by davidLif** [comment]
Thank you :)
