### ISSUE TITLE
Supported mechanism to build without vendoring libllama

### ISSUE THREAD

**Issue by charles-dyfis-net** [abetlen/llama-cpp-python#518]
**Is your feature request related to a problem? Please describe.**
If I have an existing, precompiled libllama that's correctly optimized for my platform, I don't want building llama-cpp-python to build separate binaries.

(Moreover, I'm trying to support a platform -- NixOS -- where llama-cpp-python currently doesn't build cleanly, whereas llama.cpp itself ships a fully functional package; #517 constitutes a _partial_ fix, but at present _only_ a partial fix).

**Describe the solution you'd like**
Right now, a workaround for this looks like:

```sh
sed -i -e 's@from skbuild import setup@from setuptools import setup@' setup.py
```

This works, but it's awful for all the obvious reasons. Something that's actually supported upstream (and perhaps lets a path to the location where libllama should be searched for to be passed in _at build time_ would be far preferable.

**Describe alternatives you've considered**
See workaround above.

**Comment by abetlen** [comment]
Buliding llama.cpp can now be disabled by setting `CMAKE_ARGS="-DLLAMA_BUILD=OFF"` when pip installing or building the package.
