### ISSUE TITLE
Error loading 70B model

### ISSUE THREAD

**Issue by Kenshiro-28** [abetlen/llama-cpp-python#539]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I want to load airoboros-l2-70b-gpt4-1.4.1.ggmlv3.q5_K_M.bin model. It should work.

# Current Behavior

Can't load the model:

error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

AMD EPYC Processor

* Operating System, e.g. for Linux:

Debian 6.1.38-1 (2023-07-14) x86_64

* SDK version, e.g. for Linux:

Python 3.11.2
GNU Make 4.3
g++ (Debian 12.2.0-14) 12.2.0

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

# Steps to Reproduce

Load the Airoboros 70B model:

https://huggingface.co/TheBloke/airoboros-l2-70B-gpt4-1.4.1-GGML/blob/main/airoboros-l2-70b-gpt4-1.4.1.ggmlv3.q5_K_M.bin

**Comment by ventz** [comment]
@Kenshiro-28 I saw that you closed this - what was the solution here?

Running into the same thing with the llama2-70-b ggml:

```
llama.cpp: loading model from /models/llama-2-70b.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 8192
llama_model_load_internal: n_mult     = 4096
llama_model_load_internal: n_head     = 64
llama_model_load_internal: n_head_kv  = 64
llama_model_load_internal: n_layer    = 80
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 24576
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: model size = 65B
llama_model_load_internal: ggml ctx size =    0.21 MB
error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024
```

**Comment by Kenshiro-28** [comment]
Hi! I closed because they added instructions to the readme:

https://github.com/abetlen/llama-cpp-python#loading-llama-2-70b

We have to add n_gqa=8 when loading the model

llm = Llama(model_path="./models/70B/ggml-model.bin", n_gqa=8)

**Comment by ventz** [comment]
Thanks. I wonder if the parameter will work as a cli input to the docker container.

**Comment by Kenshiro-28** [comment]
What I do is check the name of the file. If it contains "70", then I load the model with the new parameter.

**Comment by alexshmmy** [comment]
Hello, I tested the `llama2, 70B` model `llama-2-70b-chat.ggmlv3.q4_0.bin` with Apple Mac M1 64GB, and works great. 
Installation:

```bash
conda create -n llamaM1 python=3.9.16
conda activate llamaM1
CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install -U llama-cpp-python --no-cache-dir
python testM1llama.py
```

Sample code:

```bash
from llama_cpp import Llama
model_path = './llama-2-70b-chat.ggmlv3.q4_0.bin'
lm = Llama(model_path, n_gqa=8)
output = lm("what do you know about superconductors?")
print(output)
``` 

Output:
![Screenshot 2023-08-15 at 11 07 37](https://github.com/abetlen/llama-cpp-python/assets/12173938/f6145f60-28ea-4fe4-b308-066a3a180e41)
