### ISSUE TITLE
[Question] about calculate n_gpu_layers

### ISSUE THREAD

**Issue by phamkhactu** [abetlen/llama-cpp-python#581]
following [tutorial](https://python.langchain.com/docs/integrations/llms/llamacpp#gpu). I see the ```n_gpu_layers``` parameter
If I have a  ```ggml``` model. How can I calculate exactly  n_gpu_layers?

Thank you very much

**Comment by imwide** [comment]
usually a 13B model based on Llama have 40 layers
If you have a bigger model, it should be possible to just google the number of layers for this specific, or general models with the same parameter count. Also when running the model through llama cp python, it says the layer count on load of the model:

llama_model_load_internal: n_layer    = 40

**Comment by phamkhactu** [comment]
> usually a 13B model based on Llama have 40 layers If you have a bigger model, it should be possible to just google the number of layers for this specific, or general models with the same parameter count. Also when running the model through llama cp python, it says the layer count on load of the model:
> 
> llama_model_load_internal: n_layer = 40

Yeah, Thank you.

**Comment by earonesty** [comment]
https://github.com/abetlen/llama-cpp-python/pull/716
