### ISSUE TITLE
Models not loaded into RAM on CPU-Only setup. Is the library using the disk as RAM?

### ISSUE THREAD

**Issue by jacmkno** [abetlen/llama-cpp-python#603]
# Prerequisites

CPU Only setup on google colab. Link to notebook here:
https://colab.research.google.com/drive/1PXsYMNYLIkTLqrZRpKktGJ4YJu4cULMJ?usp=sharing

Keep an eye on resources during inference.

Running most recent version from pip in Colab.

- [ No] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [Yes ] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [Yes ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [No ] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Inference should not be painfully slow on CPU-Only setup with enough RAM to store the model and it seems to be because the model is not fully loaded into RAM. Standard hugging face transformers do load the whole models into GPU RAM in order to maximize performance. A 7GB model should use at least 7GB on RAM during inference, as it happens with hugging face transformers with GPU RAM.

# Current Behavior

Inference is painfully slow on CPU-Only setup with enough RAM to store the model and it seems to be because the model is not fully loaded into RAM.

# Environment and Context

It's just basic inference on google colab

* Physical (or virtual) hardware you are using, e.g. for Linux:

Google Colab 16GB RAM, CPU Only, Linux

# Failure Information (for bugs)

Short inference from a short string takes about 2 minutes with 12GB RAM.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Click on the Colab Link provided
2. Select Runtime > Run all
3. Look at the size of the downloaded model (About 7GB)
4. Look at the resources during inference. RAM never goes above 1.2GB

**Note: Many issues seem to be regarding functional or performance issues / differences with `llama.cpp`. In these cases we need to confirm that you're comparing against the version of `llama.cpp` that was built with your python package, and which parameters you're passing to the context.**

I created the same issue on llama.cpp because I understand this probably is not an issue with this library but with llama.cpp:
https://github.com/ggerganov/llama.cpp/issues/2589

Can also be an issue with GGML (not sure if llama.cpp uses GGML):
https://github.com/ggerganov/ggml/issues/444

# Failure Logs

No Failure.

Example environment info:
Check on the colab link

**Comment by gjmulder** [comment]
`llama.cpp` uses `mmap` so your RAM usage may be less than the model size in some cases.

This is not a `llama-cpp-python` issue.

**Comment by jacmkno** [comment]
@gjmulder Check the answer from the guys at llama.cpp, apparently they already have some options to allow [loading the whole model into RAM](https://github.com/ggerganov/llama.cpp/issues/2589#issuecomment-1675956486).

Regardless of how memory is managed if a 7GB is using only 0.2 GB of RAM, and if every inference requires to perform operations with each and every weight on the model, that means, the software is reading the weights from disk as it needs them, and then freeing up that RAM, there is no escape to that. So that means the whole model is never loaded into RAM at the same time, which may be good for very low end devices. but if you´re trying to perform efficient inferences this is a killer.

**Comment by ddh0** [comment]
This is an old issue, but have you tried setting `use_mlock=True` when initializing the model? I think that's exactly what mlock is supposed to do - keep the whole model in RAM.

**Comment by LtpLGM** [comment]
Sometimes setting `use_mlock=True` may not have much impact, but if there is enough memory, `use_mmap=False` maybe can make the model fully loaded into RAM（[source](https://github.com/ggerganov/llama.cpp/issues/2589)）
