### ISSUE TITLE
llama_init_from_file disappeared? 

### ISSUE THREAD

**Issue by CodingCat** [abetlen/llama-cpp-python#655]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

old code can just run 

# Current Behavior

code runs fine with 0.1.77 does not compile with the latest version

# Environment and Context

mac os x

**Comment by colobas** [comment]
Per [this](https://github.com/abetlen/llama-cpp-python/commit/952228407ebd68ef621ad747e3561c821d1c02d3) it looks like it's called `llama_load_from_file` now?

**Comment by abetlen** [comment]
@CodingCat correct this changed with a llama.h api change, I'll try to keep more detailed links in the CHANGELOG to specific commits so it's easier to review api changes to the bindings.
