### ISSUE TITLE
Please add the lora function to llama_cpp.server

### ISSUE THREAD

**Issue by yhw720** [abetlen/llama-cpp-python#656]
Hi. I'm here to request an additional function.

Run the following from the DOS prompt to read the gguf file well.
python -m llama_cpp.server --model models/7B/ggml-model-f16.gguf

But if you try to bring it up to Lora, it says there is no related option.

```
python -m llama_cpp.server --model models/7B/ggml-model-f16.gguf --lora
C:\Users\hwyoon\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\_internal\_fields.py:127: UserWarning: Field "model_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ('settings_',)`.
  warnings.warn(
usage: __main__.py [-h] [--model MODEL] [--model_alias MODEL_ALIAS] [--n_ctx N_CTX] [--n_gpu_layers N_GPU_LAYERS]
                   [--tensor_split TENSOR_SPLIT] [--rope_freq_base ROPE_FREQ_BASE] [--rope_freq_scale ROPE_FREQ_SCALE]
                   [--seed SEED] [--n_batch N_BATCH] [--n_threads N_THREADS] [--f16_kv F16_KV] [--use_mlock USE_MLOCK]
                   [--use_mmap USE_MMAP] [--embedding EMBEDDING] [--low_vram LOW_VRAM]
                   [--last_n_tokens_size LAST_N_TOKENS_SIZE] [--logits_all LOGITS_ALL] [--cache CACHE]
                   [--cache_type CACHE_TYPE] [--cache_size CACHE_SIZE] [--vocab_only VOCAB_ONLY] [--verbose VERBOSE]
                   [--host HOST] [--port PORT] [--interrupt_requests INTERRUPT_REQUESTS] [--n_gqa N_GQA]
                   [--rms_norm_eps RMS_NORM_EPS] [--mul_mat_q MUL_MAT_Q]
__main__.py: error: unrecognized arguments: --lora
```

Please add the lora function to llama_cpp.server.

**Comment by Ph0rk0z** [comment]
There is lora already. It's just annoying that it has to be loaded when the model is and not after.

Unfortunately it's all a wash because lora are not supported with quants when offloaded to GPU.

**Comment by yhw720** [comment]
@Ph0rk0z 
> There is lora already. It's just annoying that it has to be loaded when the model is and not after.

Oh, that's right. I checked that there is an option to apply Lora in the python code below. And I also checked that the movement is working well.

```python
llm = Llama(model_path="./models/7B/ggml-model-f16.gguf", n_ctx=1024, lora_path="./loras/kurugai-llama2-ko-medical-chat-7b/ggml-adapter-model.bin")
```
What I'm saying is 'llama_cpp.server'.

**Comment by szymonrucinski** [comment]
You can as well merge huggingface model into torch format and then convert merged adapter and model into gguf.

**Comment by Ph0rk0z** [comment]
That's a good solution for 7b but not for 70b.

**Comment by earonesty** [comment]
i have had no problems with conversions.  my program "auto-downloads-and-converts-to-gguf" based on an HF repo path and filter.   if anyone wants that i can extract it and make it a lib.

**Comment by abetlen** [comment]
@yhw720 just added in v0.2.4, let me know if that works for you!

**Comment by yhw720** [comment]
@abetlen 
Okay, it's working ^^ Thanks for adding the feature. 
I will use it well!

**Comment by dgo2dance** [comment]
> @abetlen Okay, it's working ^^ Thanks for adding the feature. 好的，它正在工作 ^^ 感谢您添加该功能。 I will use it well! 我会好好利用它的！

Hello! How to use this? How to load the file after lora?
