### ISSUE TITLE
Text generation only one line with Vicuna

### ISSUE THREAD

**Issue by JeroenAdam** [abetlen/llama-cpp-python#67]
Text generation is only one line with Vicuna 13b-4bit while it is a larger model compared to gtp4all which returns multiple lines. The request did seem to run fine, lots of CPU processing and finish_reason "stop" seems fine to me.
I changed the original config to max_tokens = 500.
So how is it that gtp4all returns a 4-line response and Vicuna only one line? The response seems to suggest there were several bullet points supposed to be coming.

Here the response body:
{
  "id": "cmpl-3462b1bc-ac69-4a02-b7d9-aa55a5146b0c",
  "object": "text_completion",
  "created": 1681174273,
  "model": "./models/ggml-vicuna-13b-4bit.bin",
  "choices": [
    {
      "text": "Some potential key competencies that educational resources for children could focus on include:",
      "index": 0,
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 50,
    "completion_tokens": 16,
    "total_tokens": 66
  }
}

**Comment by abetlen** [comment]
Hey @JeroenAdam is it the same request for both models, do you have a `\n` in the stop sequences?

**Comment by JeroenAdam** [comment]
I now see the issue exists with both models, it must be related to summation of points. You could easily reproduce with this request:
{
  "prompt": "\n\n### Instructions:\nGive me some potential key competencies that educational resources for children could focus on, with a focus on language skills, math skills, and reading comprehension?\n\n### Response:\n",
  "stop": [
    "\n",
    "###"
  ]
}

I now am unable to get a good response but I saved a printscreen, sadly not a complet one.
![image](https://user-images.githubusercontent.com/16437621/231031242-15089f90-2fcc-4053-b2cd-14859423cb23.png)

**Comment by abetlen** [comment]
@JeroenAdam try removing the "\n" from the stop array in the request.

**Comment by JeroenAdam** [comment]
Thanks! It worked removing "\n",

**Comment by abetlen** [comment]
No problem, for reference the stop arguments are the same as https://platform.openai.com/docs/api-reference/completions/create#completions/create-stop
