### ISSUE TITLE
Add __version__ to llama_cpp

### ISSUE THREAD

**Issue by janvdp** [abetlen/llama-cpp-python#672]
I'm trying to add support for llama_cpp but I would like to be able to check the version in Python, in a common way:

```Python
import llama_cpp
print(llama_cpp.__version__)
```

I can send a pull request that:
- adds a version file in the llama_cpp folder;
- lets you run the code above successfully;
- updates the setup.py automatically when building;
- adds a test to check if the __version__ exists.

I have some options for updating the pyproject.toml in a similar fashion. But would love to get your feedback on the whole feature request before trying them.

**Comment by abetlen** [comment]
@janvdp would be super happy to accept any PR for that!
