### ISSUE TITLE
not offloading to GPU on jetson orin

### ISSUE THREAD

**Issue by freeEDUfi** [abetlen/llama-cpp-python#674]
I am trying to run my code with GPU support, I am running it on Jetson orin  but it's not offloading the GPU My CUDA is 11.4 see attached files for screenshot and code:

models i use:
llama-2-13b.Q2_K.gguf
llama2-13b-chat.Q5_K_S.gguf
 
[llm_code.txt](https://github.com/abetlen/llama-cpp-python/files/12543450/llm_code.txt)
[model output.txt](https://github.com/abetlen/llama-cpp-python/files/12543452/model.output.txt)

**Comment by abetlen** [comment]
@freeEDUfi you have to use the `n_gpu_layers` parameter to set how many layers to offload, this allows you some control over how much vram is used.
