### ISSUE TITLE
consistency

### ISSUE THREAD

**Issue by geoHeil** [abetlen/llama-cpp-python#677]
# Expected Behavior

Non garbage, consistent results

# Current Behavior

Sometimes garbage and always changing inconsistent results are being enerated

# Environment and Context

I am running on Apple Silicon M2 pro max - for llama-cpp-python the metal acceleration is enabled, for ctransofrmers not (as it is only supporting incompatible nvica cuda acceleration). Python 3.11 is used

# Steps to Reproduce

The following example works totally fine for ctransformers:

```
from ctransformers import AutoModelForCausalLM


llm = AutoModelForCausalLM.from_pretrained("TheBloke/Speechless-Llama2-13B-GGUF", 
                                           #model_file="speechless-llama2-13b.q4_K_M.gguf", 
                                           model_type="llama", 
                                           gpu_layers=0
                                          )

print(llm("AI is going to"))

```

When now using the same model with llama-cpp-python:

```
import os
from llama_cpp import Llama

llm = Llama(model_path=os.path.expanduser("~/.cache/huggingface/hub/models--TheBloke--Speechless-Llama2-13B-GGUF/blobs/0dfefffebdda477622abf0a4e6f67d0643fce32ecc2711d5bfc8198d59ed9245"), n_gpu_layers=32)


output = llm("AI is going to")
print(output['choices'][0]['text'])


output = llm("AI is going to")
print(output['choices'][0]['text'])

output = llm("AI is going to")
print(output['choices'][0]['text'])

output = llm("AI is going to")
print(output['choices'][0]['text'])
```

each time a totally different result - and sometimes very garbage result is returned.

For ctransformers, the result is a) very sensible and b) consistent.

**Comment by AlessandroSpallina** [comment]
check the temperature value these two methods are settings, be sure the are equal in order to do comparison

**Comment by geoHeil** [comment]
let me do this and close this issue here as it then most likely will not be a bug
