### ISSUE TITLE
Implement chat continuation

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#68]
As suggested by @MillionthOdin16 because implementing #44 is taking longer than expected we should add a simple form of chat continuation if the previous message history matches. ie

Request 1
```
{ "messages": [msg1, msg2] }
```

Response 1
```
{ "messages": [msg1, msg2, msg3] }
```

Request 2
```
{ "messages": [msg1, msg2, msg3, msg4] }
```

In this case we only need to process msg4 and return a new msg5.

**Comment by MillionthOdin16** [comment]
Thanks. I think figuring out a way to get this working will jumpstart further integrations with other projects by making high-speed completions for chat more easily accessible.

I don't know the best way for keeping track of a chat session (i.e. matching messages to an existing context). I think I saw previously that you might have some user information, or maybe we could use the completion ID somehow?

And just to be clear, I'm not expecting this to scale to a significant number of conversations simultaneously. My idea is just that it gives us the ability to continue generation on an existing context without having to reinitialize it. So maybe a couple... Or even just one would be a great performance boost.

And once we do have state saving, or the ability to quickly load up significant message history, then this workaround would no longer be needed.

**Comment by MillionthOdin16** [comment]
And I guess this could even be a separate endpoint that accepts the same data as the actual chat completions endpoint, but is implemented differently with a single persistent model and context that just adds the most recent message from the user to the message history and returns the generation. If that makes sense.

I didn't know if your initial message for this issue was the format you wanted to use or not.

**Comment by abetlen** [comment]
No that was just trying to describe how to check which messages to process. Basically if one list is a prefix of the other than just process the difference of the two lists, otherwise we need to start processing from scratch.

As for the API I'll keep the endpoint the same, unfortunately this workaround isn't gauranteed to work the same as re-processing from scratch but it's probably worth it to get this functionality in sooner rather than later.

**Comment by djaffer** [comment]
Does api accept chat history?

**Comment by abetlen** [comment]
@djaffer Yes if you check the docs it's identical to the OpenAI api where you send in the entire chat history https://platform.openai.com/docs/api-reference/chat

**Comment by abetlen** [comment]
![image](https://user-images.githubusercontent.com/6826477/231310540-db00d3b5-4ee4-40ae-b862-a2d08a4181bf.png)

Okay, I've got a basic implementation, just need to clean up some issues but generally it's working as expected (chats are significantly more responsive).

The way I'm implementing this is through a `LlamaCache` abstract class and then this specific version is a `ContextCache` who's basic strategy is to just check wether it's already processed the first part of a message and if so start from just the new tokens. This should also allow us to extend this with a `KVStateCache` in the future when I can work out the limitations with that API.

@MillionthOdin16 in the #17 issue could you give me a hand identifying the prompt formats for various models? For text completion this is user provided but for the chat it's a little bit more challenging (as illustrated above) because the finetuned models each expect a slightly different format.

**Comment by abetlen** [comment]
@MillionthOdin16 this is now pushed to master (not PyPI yet) if you get the chance can you test it out from source? All you need to do for the server is run with with `CACHE=1` environment variable set.
