### ISSUE TITLE
Add -mg parameter to specify main gpu.

### ISSUE THREAD

**Issue by Ph0rk0z** [abetlen/llama-cpp-python#685]
I have 2x3090 and a P40, I'd like to see if it's faster to use the P40 as the main GPU or not so that more layers go onto the 3090s. The main GPU takes a lot of overhead from the small multiplications and must be underfilled and with the bindings it is forced to always be 0.

**Comment by Ph0rk0z** [comment]
Also would be nice to have numa flag because I have 2 procs. Right now I tried with 2 CPU and everything is on a single CPU

**Comment by abetlen** [comment]
@Ph0rk0z just pushed v0.2.4 which adds the main_gpu, numa, and a few other flags we were missing in this project, let me know if that works for you!

**Comment by Ph0rk0z** [comment]
Awesome, will update and check it out.
