### ISSUE TITLE
Can't use tensor split with server.

### ISSUE THREAD

**Issue by Ph0rk0z** [abetlen/llama-cpp-python#686]
I have tried to call tensor split from server as follows:

--tensor_split "x,y,z"

The argument fails no matter how it is formatted. I tried spaces, using 'x,y,z'. Nothing works and it always says invalid optional value.

I tried to fix the arguments in the code but could not. Always get invalid optional value. Through this process I also found out that use_mmap does not change to false either. I have had to hard encode these values inside app.py and then they work. Something is mad wrong with argument parsing.

**Comment by abetlen** [comment]
@Ph0rk0z sorry about this, can you try using the `TENSOR_SPLIT` environment variable instead, there was a bug introduced in the pydantic 2.0 migration that caused some of the server cli flags to break.

**Comment by Ph0rk0z** [comment]
No worries, I have just been editing the file. I can try passing it with env too.

**Comment by nadeeja89** [comment]
Would you be able to advise on how you can set env variables in windows? should I use SET?
