### ISSUE TITLE
Allow `X-Request-ID` or equivalent in request headers and return in the response.

### ISSUE THREAD

**Issue by devrimcavusoglu** [abetlen/llama-cpp-python#689]
**Is your feature request related to a problem? Please describe.**
Currently there is no way of tracking requests for `llama-cpp-server` afaik (I may miss a related feature). It would be really good if we can put custom IDs/tokens for client side that will be returned by the server. That would be very useful for backtracking, handling async requests, etc.

**Describe the solution you'd like**
Usually [Request-ID](https://http.dev/x-request-id) or `Correlation-ID`. A [related read](https://stackoverflow.com/q/56068619/7871601) about using which one. This is easy to implement, just returning an id in the response headers; however, it would significantly impact the users imho.

**Comment by abetlen** [comment]
@devrimcavusoglu sounds straightforward, currently the completion endpoints currently returns a completion id which is a randomly generated uuid.

To be clear, are you talking about a client provided request id which the server just echos back in the response so you can track the request through a larger distributed system or generating a new request id by the server? I suppose we could do the first and fallback to generating a new request id or using the completion id.

**Comment by devrimcavusoglu** [comment]
> a client provided request id which the server just echos back in the response so you can track the request through a larger distributed system

@abetlen this one.
