### ISSUE TITLE
[Feature Request] Support InternLM Deploy

### ISSUE THREAD

**Issue by vansinhu** [abetlen/llama-cpp-python#693]
Dear llama-cpp-python developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. [InternLM](https://github.com/InternLM/InternLM) is a large language model similar to llama2, and we look forward to InternLM being supported in llama-cpp-python. If there are any challenges or inquiries regarding support for InternLM, please feel free to join our Discord discussion at https://discord.gg/gF9ezcmtM3. 

Best regards,
vansinhu

**Comment by abetlen** [comment]
@vansinhu looks interesting but not much I can do here, try opening an issue in the `llama.cpp` repo for new model architecture support. 

Cheers and good luck!
