### ISSUE TITLE
release 0.2.0 fails to build when installing via pip

### ISSUE THREAD

**Issue by AmineDjeghri** [abetlen/llama-cpp-python#701]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
I update llama-cpp-python on every release and it usually installs without any problem

# Current Behavior

```
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      *** scikit-build-core 0.5.0 using CMake 3.27.4 (wheel)
      *** Configuring CMake...
      2023-09-12 23:23:47,426 - scikit_build_core - WARNING - libdir/ldlibrary: /home/outscale/miniconda3/envs/react-qback/lib/libpython3.9.a is not a real file!
      2023-09-12 23:23:47,427 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/home/outscale/miniconda3/envs/react-qback/lib, ldlibrary=libpython3.9.a, multiarch=x86_64-linux-gnu, masd=None
      loading initial cache file /tmp/tmpokfl0ylr/build/CMakeInit.txt
      -- The C compiler identification is GNU 11.4.0
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /home/outscale/miniconda3/envs/react-qback/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /home/outscale/miniconda3/envs/react-qback/bin/c++ - skipped
      -- Detecting CXX compile features
      ninja: error: '/tmp/pip-install-cj9hww_r/llama-cpp-python_b6fd4b268fde4a7f9c385ad01df0f9ba/.git/modules/vendor/llama.cpp/index', needed by '/tmp/pip-install-cj9hww_r/llama-cpp-python_b6fd4b268fde4a7f9c385ad01df0f9ba/vendor/llama.cpp/build-info.h', missing and no known rule to make it


      *** CMake build failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```
# Environment and Context

I'm using two machines : one with a CPU only and one with a GPU A100. It fails to installs / upgrade on both

**Comment by abetlen** [comment]
@AmineDjeghri looking into it!

**Comment by lithces** [comment]
I could confirm, same issue.

**Comment by abetlen** [comment]
@AmineDjeghri looks like the issue was that a `.git` __file__ was being included in the `vendor/llama.cpp` directory in the pip source distribution, this caused llama.cpp to think it should include `build-info.h`, however as this wasn't an actual git repo (not sure how this even happened) it failed to parse the anything in the git repo.

Anyways, I simply excluded those files in the source distribution and tested out the fix, **v0.2.1** should work now, simply `pip install --upgrade llama-cpp-python`.

Let me know if that works!

**Comment by Chainfire** [comment]
Fixed it for me.

**Comment by Foxtr0t1337** [comment]
> 

Can't install 0.2.0 or 0.2.1 on MacOS if metal is enabled.

`-- Found Git: /usr/bin/git (found version "2.39.2 (Apple Git-143)")
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      CMake Warning at vendor/llama.cpp/CMakeLists.txt:125 (message):
        Git repository not found; to enable automatic generation of build info,
        make sure Git is installed and the project is a Git repository.
      
      
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
      -- Found Threads: TRUE
      -- Accelerate framework found
      -- Metal framework found
      CMake Error: File /private/var/folders/0k/wdw0d6mx67qclt0bwq6mbzcc0000gn/T/pip-install-91ktzvis/llama-cpp-python_5343734b0cc44fbf9804dbc168e3f847/vendor/llama.cpp/ggml-metal.metal does not exist.
      CMake Error at vendor/llama.cpp/CMakeLists.txt:186 (configure_file):
        configure_file Problem configuring file`

Maybe there are more '.git'(s) to remove lol.
However I can still use 0.1.85 rn so no worries!

**Comment by abetlen** [comment]
@Foxtr0t1337 haha nope just an issue with a `.gitignore` causing the `ggml-metal.metal` file to not be included in the source distribution, can you check out `v0.2.2`?

**Comment by Foxtr0t1337** [comment]
> @Foxtr0t1337 haha nope just an issue with a `.gitignore` causing the `ggml-metal.metal` file to not be included in the source distribution, can you check out `v0.2.2`?

Fixed. Blazing fast generation. Thanks!

**Comment by abetlen** [comment]
@Foxtr0t1337 awesome!

I'll wait till tomorrow or confirmation from @AmineDjeghri and then close this.

**Comment by AmineDjeghri** [comment]
@abetlen 
I will try it in few hours and let you know

**Comment by AmineDjeghri** [comment]
@abetlen works fine now . Thanks !

**Comment by AmineDjeghri** [comment]
@abetlen works fine now . Thanks !
