### ISSUE TITLE
Why is the latest version 2x slower?

### ISSUE THREAD

**Issue by Bloob-beep** [abetlen/llama-cpp-python#71]
0.1.32 is 2x slower than 0.1.27

I tried using `use_mlock=TRUE`, warned me about RLIMIT and had to `ulimit -l unlimited` temporarily, but it still didn't improve.
Is anyone else getting the same speed dip?

**Comment by nigh8w0lf** [comment]
yes very slow, seems the problem is on llama cpp's end, seen a few issues about speed recently.

**Comment by CyberTimon** [comment]
Can we install the older version again until this is fixed? How?

**Comment by abetlen** [comment]
@CyberTimon totally, you can check out the PyPI history here -> https://pypi.org/project/llama-cpp-python/#history and try out older versions.

**Comment by AndreiSva** [comment]
I'm feeling this as well. Running llama-cpp manually is noticeably faster than running it through the API.

**Comment by CyberTimon** [comment]
Just checked it. LLaMA CPP is 40ms per token for me and the python bindings are 200ms per token so it's much slower. Sadly downgrading to version 0.1.27 is still slow.
