### ISSUE TITLE
Why use sampling token budget

### ISSUE THREAD

**Issue by krrishdholakia** [abetlen/llama-cpp-python#710]
hi @abetlen @janvdp 
Not sure i understand this - why use a token budget? 
https://github.com/abetlen/llama-cpp-python/blob/6cfc54284b99ef1bff8193e2d5e483dbd89ada02/examples/low_level_api/low_level_api_chat_cpp.py#L405

**Comment by abetlen** [comment]
@krrishdholakia this is to ensure that the number of tokens does not exceed the maximum context length of the model.
