### ISSUE TITLE
i was trying to install pip install llama-cpp-python

### ISSUE THREAD

**Issue by Aadil-tai** [abetlen/llama-cpp-python#712]
and i got an error 
![Screenshot 2023-09-14 133120](https://github.com/abetlen/llama-cpp-python/assets/60460219/f3b277a9-5fcb-4c23-b4fd-d524a420b5d3)

**Comment by abetlen** [comment]
Can you try installing from the latest git  branch using `pip install --verbose git+https://github.com/abetlen/llama-cpp-python.git` and posting that log?

**Comment by Aadil-tai** [comment]
oh i tried and it worked now thank you
