### ISSUE TITLE
Issue loading llama.dll with Windows Isolation Containers

### ISSUE THREAD

**Issue by johnnyainsworth** [abetlen/llama-cpp-python#715]
When using windows isolation containers (like in SQL Server Machine Learning Services) the following line of code from llama_cpp.py throws an error (Win Error 5) when calling 
def _load_shared_library(lib_base_name: str):

 _base_path = pathlib.Path(__file__).parent.resolve() 

runs using administrative  privileges but fails when called inside a windows isolation container. 

changing the line to 

_base_path = pathlib.Path(os.path.abspath(os.path.dirname(__file__)))

resolves the issue on windows. I believe it would work in a cross-platform way, but I don't have the means to test it right now. Please consider patching llama_cpp.py. Thanks!

**Comment by johnnyainsworth** [comment]
That would be awesome. Thanks!

**Comment by abetlen** [comment]
@johnnyainsworth pushed a fix in v0.2.5, can you test that out?

**Comment by johnnyainsworth** [comment]
Works for me. Thanks!
