### ISSUE TITLE
`--use_mlock` arg is confusing

### ISSUE THREAD

**Issue by jamesbraza** [abetlen/llama-cpp-python#719]
With `llama-cpp-python==0.2.5`'s server help:

```bash
python -m llama_cpp.server --help
  ...
  --use_mmap USE_MMAP   Disable Use mmap. (default: True)
  --use_mlock USE_MLOCK
                        Disable Use mlock. (default: True)
```

The arg name is "use mlock", and the description is "disable use mlock".

These are opposite meanings, it's unclear what will actually take place without reading the implementation.  Can we update the docstrings?  Thanks in advance, sorry for a nit

**Comment by abetlen** [comment]
@jamesbraza woops yup that's wrong, will fix

**Comment by CodeJjang** [comment]
@abetlen Shouldn't USE_MMAP=False and USE_MLOCK=True decrease model load time to almost zero (as it is already in mem)?

**Comment by CodeJjang** [comment]
With CPU inference, USE_MMAP=False and USE_MLOCK=True I have a load time of 7s in each prompt completion
