### ISSUE TITLE
Getting `Illegal instruction (core dumped)` when running an openblas made install

### ISSUE THREAD

**Issue by Bloob-beep** [abetlen/llama-cpp-python#72]
Making the latest llama.cpp repo with `make LLAMA_OPENBLAS=1` works as it should.

But running `LLAMA_OPENBLAS=1 pip install --force-reinstall --no-cache-dir --no-index --find-links . llama-cpp-python` (running on an offline server, its the tar.gz you get from `pip download`)
produces an `Illegal instruction (core dumped)` when you try to generate words from it.

**Comment by abetlen** [comment]
Can you check out and test this llama.cpp commit with OPENBLAS (this is what v0.1.32 is based on) https://github.com/ggerganov/llama.cpp/tree/684da25926e5c505f725b4f10b5485b218fa1fc7
to confirm, also compare to the latest llama.cpp

**Comment by Bloob-beep** [comment]
Sorry my bad, I did not think things through.
For the commit you sent it works, and I forgot to test on the actual llama-cpp-python repo itself, it works for llama-cpp-python as well.

My error appeared when I was using langchain, it does not like `chain.run`ning the llm. `Illegal instruction (core dumped)`

```
llm = LlamaCpp(model_path="/opt/gpt/model/ggml-vicuna-7b-4bit-rev1.bin", n_ctx=2048, max_tokens=100, n_batch=512, stop=["\n"])

chain = load_qa_chain(llm, chain_type="stuff")
answer = chain.run(input_documents=found_docs, question=query)
```

**Comment by abetlen** [comment]
@Bloob-beep but without the chain ie `llm(prompt)` doesn't give this error? Very strange

**Comment by Bloob-beep** [comment]
Correct me if i'm misunderstanding, but yes I think so.

It can load the llm, load the chain. But as soon as I try to run the chain it doesn't work.
Works on non-BLAS versions though.

**Comment by gjmulder** [comment]
@Bloob-beep are you still having the issue with BLAS?

**Comment by gjmulder** [comment]
Closing. Reopen if the issue reoccurs.
