### ISSUE TITLE
Segfaults now with latest llama.cpp commits

### ISSUE THREAD

**Issue by Ph0rk0z** [abetlen/llama-cpp-python#727]
I pulled new commits for vendor/llama.cpp and I get `terminate after throwing an instance of std::length error`

The model loads fine and everything seems normal, just dies when generating. This is using the built in server.
Same error is in textgen.

**Comment by manishshettym** [comment]
Can reproduce! It is due to an update to the tokenize APIs in llama.cpp. Opened this PR for it: #730

**Comment by Ph0rk0z** [comment]
Makes sense, that's a big component.

**Comment by abetlen** [comment]
@Ph0rk0z were you using the llama.cpp version pinned in the `vendor/llama.cpp` directory?

**Comment by Ph0rk0z** [comment]
nope, I like to do the latest and greatest
