### ISSUE TITLE
Cublas found but cuda toolkit not found error

### ISSUE THREAD

**Issue by DenizK7** [abetlen/llama-cpp-python#744]
I want to use my code with GPU
Cuda version 11.8

first i did $env:CMAKE_ARGS = "-DLLAMA_OPENBLAS=on"
after that I delete the llama-cpp-python
lastly I wrote this prompt
 pip install llama-cpp-python --no-cache-dir --verbose

But I tried all things on the internet but I am facing same issue over and over again
-- Found Threads: TRUE
-- Found CUDAToolkit: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include (found version "11.8.89")
-- cuBLAS found
CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:503 (message):
No CUDA toolset found.
Call Stack (most recent call first):
C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
vendor/llama.cpp/CMakeLists.txt:286 (enable_language)

-- Configuring incomplete, errors occurred!

*** CMake configuration failed
error: subprocess-exited-with-error

× Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
full command: 'C:\Users\90506\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\90506\AppData\Local\Programs\Python\Python310\lib\site-packages\pip_vendor\pep517\in_process_in_process.py' build_wheel 'C:\Users\90506\AppData\Local\Temp\tmpudf4og91'
cwd: C:\Users\90506\AppData\Local\Temp\pip-install-0y7s6qa3\llama-cpp-python_278d7a0f8c18420bbb8491c952ad10cd
Building wheel for llama-cpp-python (pyproject.toml) ... error
ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by kristianzanev** [comment]
https://stackoverflow.com/questions/56636714/cuda-compile-problems-on-windows-cmake-error-no-cuda-toolset-found/56665992#56665992

uninstalling the 'Build Tools' of Visual Studio and only having the Community IDE installed, CMake used the IDE instead of the Build Tools and then it started working fine.

**Comment by DenizK7** [comment]
It actually worked. Thanks a lot.
