### ISSUE TITLE
The parameter `n_gqa` mentioned in `readme` has been removed

### ISSUE THREAD

**Issue by streetycat** [abetlen/llama-cpp-python#758]
The parameter `n_gqa` mentioned in readme as follow:

```
Llama2 70b must set the n_gqa parameter (grouped-query attention factor) to 8 when loading:

llm = Llama(model_path="./models/70B/llama-model.gguf", n_gqa=8)
```

It has been removed in follow commit:

https://github.com/abetlen/llama-cpp-python/commit/4ed632c4b352f80a8cd19ad5923e2981a2bb3c53

**Comment by abetlen** [comment]
@streetycat correct, this was a change to the `llama.h` api in `llama.cpp`, this is now pulled in from the .gguf file metadata automatically. from my understanding.
