### ISSUE TITLE
mistral 7b model

### ISSUE THREAD

**Issue by adeelhasan19** [abetlen/llama-cpp-python#764]
llm = LlamaCPP(
    model_url='https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/blob/main/mistral-7b-instruct-v0.1.Q5_K_M.gguf',)
    
    i am using the above line to download model but got
    "ValueError: Download incomplete"

**Comment by pabl-o-ce** [comment]
Mistral is other model architecture... I don't know if llama.cpp would create a integration

**Comment by lxa-g** [comment]
I can use llama-cpp-python with Mistral GGUF Okay (TheBloke mistral-7b-instruct-v0.1.Q5_K_M.gguf). 
Just did today, 2023-10-04.

Use latest code.

```
git clone --recurse-submodules https://github.com/abetlen/llama-cpp-python.git
cd llama-cpp-python/
make build
```
