### ISSUE TITLE
Request: `Llama` supporting URL in `model_path`

### ISSUE THREAD

**Issue by jamesbraza** [abetlen/llama-cpp-python#769]
**Is your feature request related to a problem? Please describe.**

I would like to connect to a Llama v2 running on a server.  Currently, `Llama` class only supports local files.

**Describe the solution you'd like**

The ability for `model_path` to be a URL, something like `Llama(model_path="http://1.2.3.4/llama-2-13b-ensemble-v5.Q4_K_M.gguf")`

**Describe alternatives you've considered**

n/a

**Comment by abetlen** [comment]
For connecting to a remote model use the openai python client to connect to a llama-cpp-python server.
