### ISSUE TITLE
Switching from GGML to GGUF formats, performance difference.

### ISSUE THREAD

**Issue by imwide** [abetlen/llama-cpp-python#782]
I updated llama-cpp-python this morning, in order to try the new gguf format, only to find out that the performance (tokens per second) is three times slower with a model the same size, than ggml used to be. is there a way to convert gguf into ggml and run ggml still? if not, how do i increase the inference speed?

**Comment by mvdbos** [comment]
@imwide Did you find out what caused it? Did you solve it?
