### ISSUE TITLE
No longer running on GPU after update

### ISSUE THREAD

**Issue by imwide** [abetlen/llama-cpp-python#787]
I recently updated llama-cpp-python to make use of the new gguf format. Since then, i cant seem to get GPU to work. It keeps saying "BLAS=0" when starting the model, eventhough it was working before. Anything i need to change? I am very confused.

**Comment by talhalatifkhan** [comment]
i am getting same isssue

**Comment by imwide** [comment]
> i am getting same isssue

Hey @talhalatifkhan I run the following command and now it works. try the same if you are using a Nvidia GPU with cuda:
`CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir`
