### ISSUE TITLE
Max Context Length of a model

### ISSUE THREAD

**Issue by rounak610** [abetlen/llama-cpp-python#792]
Is there any way I can find the maximum context length of a local LLM?

**Comment by ddh0** [comment]
For GGUF models you can use this module:

 https://github.com/oobabooga/text-generation-webui/blob/main/modules/metadata_gguf.py

Like so:
```import metadata_gguf```
```my_context_length = metadata_gguf['llama.context_length']```

then `context_length` will be an `int` with the number of tokens your model was trained on.

**Comment by abetlen** [comment]
You can now also use `model.metadata["llama.context_length"]`

**Comment by jndiogo** [comment]
Just to leave the information that this only works if the GGUF file has metadata key "llama.context_length" defined. 

Unfortunately it seems each model defines its own metadata keys, for example in [Rocket 3B](https://huggingface.co/TheBloke/rocket-3B-GGUF), the context length is in the "'stablelm.context_length" key instead...

**Comment by ddh0** [comment]
> Just to leave the information that this only works if the GGUF file has metadata key "llama.context_length" defined.
> 
> Unfortunately it seems each model defines its own metadata keys, for example in [Rocket 3B](https://huggingface.co/TheBloke/rocket-3B-GGUF), the context length is in the "'stablelm.context_length" key instead...

I solved issue this in my own project by doing the following:

```python
        self.metadata = GGUFReader.load_metadata(self, model_path)

        n_ctx_train = None
        for key in self.metadata.keys():
            if key.endswith('.context_length'):
                n_ctx_train = self.metadata[key]
                break

        if n_ctx_train is None:
            raise KeyError(
                "GGUF file does not specify a context length"
            )
        
        rope_freq_base_train = None
        for key in self.metadata.keys():
            if key.endswith('.rope.freq_base'):
                rope_freq_base_train = self.metadata[key]
                break
```

**Comment by jndiogo** [comment]
Thanks - this seems to work very well! I did a quick survey of 16 popular GGUF models and found *.context_length in all of them.

BTW, noticed you're also reading .rope.freq_base and got curious - any practical reason to use or change this value?

**Comment by ddh0** [comment]
> BTW, noticed you're also reading .rope.freq_base and got curious - any practical reason to use or change this value?

That code snippet is [part of a larger function](https://github.com/ddh0/easy-llama/blob/24504e0f6d1703010d83e7da54493472aeb9fc16/model.py#L50) that allows models to be loaded at greater-than-native context lengths. :)
