### ISSUE TITLE
How to specify which GPUs to be used?

### ISSUE THREAD

**Issue by wennycooper** [abetlen/llama-cpp-python#794]
If I have multiple GPUs (say, 0, 1, 2, 3 ...7), how to specify gpu (0 and 1) to be used in llama_cpp ?

**Comment by m-from-space** [comment]
Here is the API reference: https://llama-cpp-python.readthedocs.io/en/latest/api-reference/

Use parameters `main_gpu` (e.g. `0`) and `tensor_split`, which expects a list of floats, e.g. `[0.5, 0.5]`.

As far as I know you should leave more free VRAM inside the main gpu. But you better test it yourself and look how performance changes.

**Comment by wennycooper** [comment]
Hi, Tks for your response.
I tried tensor_split=[0, 0.5, 0.5, 0, 0, 0, 0, 0],  but it showed:

CUDA error 400 at /tmp/pip-install-dzjp3z67/llama-cpp-python_c604e76d007247ec89d6ef4b668a462a/vendor/llama.cpp/ggml-cuda.cu:6389: invalid resource handle
current device: 0

`
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     24411      C   python                                     3820MiB |
|    1   N/A  N/A     24411      C   python                                     4014MiB |
|    2   N/A  N/A     24411      C   python                                     4014MiB |
|    3   N/A  N/A     24411      C   python                                      268MiB |
|    4   N/A  N/A     24411      C   python                                      168MiB |
|    5   N/A  N/A     24411      C   python                                      168MiB |
|    6   N/A  N/A     24411      C   python                                      168MiB |
|    7   N/A  N/A     24411      C   python                                      168MiB |
+---------------------------------------------------------------------------------------+
`
