### ISSUE TITLE
add support for batched inference

### ISSUE THREAD

**Issue by promptboom** [abetlen/llama-cpp-python#818]
as llama.cpp supports batched inference in 8.26, can llama-cpp-python supports  for batched inference? I just tried the latest version 0.2.11 and found that it is not possible to make multiple requests simultaneously.

![image](https://github.com/abetlen/llama-cpp-python/assets/140774620/3de98d86-3cb4-4f77-b5fa-07f308c2329d)

**Comment by yourbuddyconner** [comment]
Linking the PR for visibility: https://github.com/ggerganov/llama.cpp/pull/3228

**Comment by yourbuddyconner** [comment]
Also, looks like easy integration here is potentially contingent on this issue: https://github.com/ggerganov/llama.cpp/issues/3478

**Comment by akx** [comment]
See #771 – it's one of the pinned issues in this repo.

**Comment by SylvainVerdy** [comment]
have you find any solutions? @yugaljain1999

**Comment by yugaljain1999** [comment]
@SylvainVerdy Not yet, so I started using ctranslate2 for batch inference.
