### ISSUE TITLE
Missing Baichuan2 chat format

### ISSUE THREAD

**Issue by promptboom** [abetlen/llama-cpp-python#819]
In version v0.2.11, there is an error when using the Baichuan2 model and calling the chat/completions interface.

<img width="1049" alt="image" src="https://github.com/abetlen/llama-cpp-python/assets/140774620/01a7a722-e7b6-46ae-81c7-63933c9efffa">

**Comment by caiyesd** [comment]
@abetlen I created https://github.com/abetlen/llama-cpp-python/pull/936 to enhance it.

**Comment by abetlen** [comment]
@caiyesd thank you
