### ISSUE TITLE
How to Install llama cpp python bindings in windows using w64devkit or MinGW?

### ISSUE THREAD

**Issue by eswarthammana** [abetlen/llama-cpp-python#825]
I have setup for llama.cpp using w64devkit in my windows machine. 
Please share me steps how to reuse llama.cpp i have setup or help me to install llama-cpp-python using MinGW or w64devkit.

When i tried through both the options i am facing an exception as shown below 

![issue](https://github.com/abetlen/llama-cpp-python/assets/23114153/88a56d46-a239-49af-9d29-011dcbfedfef)

**Comment by sujeendran** [comment]
@eswarthammana - Could you try pulling from [this fork](https://github.com/sujeendran/llama-cpp-python) and follow the extra steps mentioned [here](https://github.com/sujeendran/llama-cpp-python/tree/main#windows-remarks)?

**Comment by eswarthammana** [comment]
thanks for the steps, able to build successfully.

**Comment by eswarthammana** [comment]
Why it fails if i add the bin folder to path variable.. like `set path="path_to_w64devkit_bin";%path%`

**Comment by abetlen** [comment]
@eswarthammana closing this now as @sujeendran fix has been merged in #848
