### ISSUE TITLE
Please add set seed support to the high level api

### ISSUE THREAD

**Issue by tk-master** [abetlen/llama-cpp-python#832]
Hello, I would like to be able to change (set) the seed with the high level api functions (like __call__, generate, create_completion etc. from llama.py).

Currently I can only change the seed by reloading the model, which is slow.. (unless I'm missing something?).

**Comment by tk-master** [comment]
@abetlen is seed not supported at all currently? it behaves like it's random even when seed > 0 (always get different response from same prompt)

**Comment by abetlen** [comment]
@tk-master just added `seed` parameter to create_completion and create_chat_completion which calls `llama_set_rng_seed` let me know if that works for you!

**Comment by tk-master** [comment]
@abetlen great! thanks. Now here's a suggestion, can we add a set_seed function that calls llama_set_rng_seed ? that way it can be used with every generation function (dunno if that's better or doable, just a suggestion). I will test it better later but it seems ok

**Comment by abetlen** [comment]
@tk-master don't see why not, I just added a `set_seed` method to the `Llama` class.
