### ISSUE TITLE
Token-by-token streaming without API

### ISSUE THREAD

**Issue by fakerybakery** [abetlen/llama-cpp-python#844]
Is there a way to stream token-by-token without using the API? i.e.

```python
output = llm(prompt, max_tokens=256, stop=["\n"], echo=False, stream=True)
for token in output:
	print(output)
```

Thanks in advance!

**Comment by m-from-space** [comment]
What do you mean by "without using the API"?

**Comment by fakerybakery** [comment]
Sorry, I meant without using the HTTP API

**Comment by tk-master** [comment]
yes, try this..

for event in output:
    event_text = json.loads(json.dumps(event))["choices"][0]["text"]
    print(event_text , end='', flush=True)
