### ISSUE TITLE
Function changed in llama.cpp

### ISSUE THREAD

**Issue by Ph0rk0z** [abetlen/llama-cpp-python#852]
We lost a KV_cache function in this: https://github.com/ggerganov/llama.cpp/commit/6e08281e588bbba1a5d180290a94a43f167f3a1a

llama_kv_cache_tokens_rm has to be renamed to llama_kv_cache_clear and both extra parameters have to be removed.

**Comment by abetlen** [comment]
@Ph0rk0z should be fixed now!

**Comment by Ph0rk0z** [comment]
Just as you did the work, something broke again. And when I forced it to compile, it OOMs when allocating system ram.
