### ISSUE TITLE
Why no releases?

### ISSUE THREAD

**Issue by tk-master** [abetlen/llama-cpp-python#859]
There hasn't been a release since sep30 (over a month now).

My problem is that building llama.cpp with cuda support is an absolute pain in the butt so I rely on prebuild wheels (jllllll/llama-cpp-python-cuBLAS-wheels) which are build based on the latest release.

Also projects like ooba etc rely on this as it's unreasonable to expect users to compile libraries like llama.cpp manually.

So it would be nice if we had weekly (or so) release builds.

Thanks

**Comment by abetlen** [comment]
Hey @tk-master just had a busier than usual month at work. Releases mean a bunch of urgent issues that I wouldn't have been  able to resolve so I just opt to keep `main` up-to-date for folks who want to pip install through git.

Anyways, work is cleared up, a new release is pushed and should be back to a normal release schedule.

Cheers.
