### ISSUE TITLE
NameError: name 'open' is not defined when llama-cpp-python cleaning up.

### ISSUE THREAD

**Issue by fourdim** [abetlen/llama-cpp-python#860]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

No Exceptions.

# Current Behavior

At the end of inference:
```
Exception ignored in: <function Llama.__del__ at 0x7f38d140f010>
Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/llm-gateway-NqZIJtg0-py3.10/lib/python3.10/site-packages/llama_cpp/llama.py", line 1655, in __del__
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/llm-gateway-NqZIJtg0-py3.10/lib/python3.10/site-packages/llama_cpp/utils.py", line 8, in __enter__
NameError: name 'open' is not defined
```

# Environment

Commit hash:

https://github.com/abetlen/llama-cpp-python/commit/f0d1a1b255e926f8ed488531a487dfab85b3760e

# Related comments

https://github.com/abetlen/llama-cpp-python/pull/803#issuecomment-1775063727

**Comment by abetlen** [comment]
The issue was caused by some weird python behaviour inside of __del__ methods. I'll include this in the next version which should be published sometime today.
