### ISSUE TITLE
kv_self.ctx issue while using vocab_only=True

### ISSUE THREAD

**Issue by eswarthammana** [abetlen/llama-cpp-python#863]
when i used vocab_only=True  for tokenize and add to vectors store, facing the following issue. could you please help me, how to fix,

![issue](https://github.com/abetlen/llama-cpp-python/assets/23114153/0649c6c3-a981-4c9b-b705-16e9ace898d8)

**Comment by abetlen** [comment]
Are you sure you're only calling the tokenizer? That assert should only appear inside the llama_decode function which tries to perform a forward pass on the batch of tokens.

**Comment by eswarthammana** [comment]
i was trying to check the quality of tokens generated. it seems add documents converts to embeddings to push to vector store. i thought if i keep vocab only then it creates token store, lack of understanding. Thanks for the reply :)

**Comment by abetlen** [comment]
No worries, if you need to perform any kind of inference (ie creating embeddings, generating text) you `vocab_only` should be set to `False`, it's mostly meant for testing and standalone tokenizers.
