### ISSUE TITLE
Is this project run llama model without GPU???

### ISSUE THREAD

**Issue by bonuschild** [abetlen/llama-cpp-python#877]
I am looking for the api server backend that can run codellama model, which can then bt integrated into VSCode plugins to offer code assisting service.

What is the supporting component to fulfill this target?
- The frontend IDE is VS Code, but the plugin I am not aware of it
- The model is Phind-Codellama-v2-AWQ
- The OpenAI API backend I am not aware of it. I have both CPU and GPU resources to run the model. maybe vllm or others? I am so confusing now.

**Comment by bioshazard** [comment]
Sounds like you want to look at the OpenAI-compatible "server" function of this project? It runs on CPU if you have GGUF model and you can offload to GPU if you have the VRAM for it with `n_gpu_layers` per `--help` if you compile the repo per the **Hardware Acceleration** section of README. Does that help? Or do I misunderstand?

**Comment by bonuschild** [comment]
> Sounds like you want to look at the OpenAI-compatible "server" function of this project so you can use OpenAI solutions but point to your local model. It runs on CPU if you have GGUF model and you can offload to GPU if you have the VRAM for it with `n_gpu_layers` per `--help` if you compile the repo per the **Hardware Acceleration** section of README. Does that help? Or do I misunderstand?

So simply use `python -m llama_cpp.server` will serve an OpenAI API server?

**Comment by bioshazard** [comment]
Yes, exactly. However, you need a few more flags like to specify the model and GPU layers to offload (again, you will have to install it following the Hardware Acceleration section of the README to get that option). Check `python -m llama_cpp.server --help` for the flags.

**Comment by bioshazard** [comment]
Here, for example is how I serve OrcaMistral on my Windows machine:

```
python -m llama_cpp.server `
  --model .\models\mistral-7b-openorca.Q6_K.gguf `
  --n_ctx 8192 `
  --chat_format chatml `
  --n_gpu_layers 43 `
  --model_alias gpt-3.5-turbo `
  --host 0.0.0.0 --port 8180
```

**Comment by bonuschild** [comment]
@bioshazard That was such a nice reference! Thx!
