### ISSUE TITLE
Finetune Support

### ISSUE THREAD

**Issue by abetlen** [abetlen/llama-cpp-python#882]

**Comment by sengiv** [comment]
Awesome 🚀
Does this mean we can start using "training files" just as in OpenAI's guide?
https://platform.openai.com/docs/guides/fine-tuning/preparing-your-dataset
![image](https://github.com/abetlen/llama-cpp-python/assets/43817262/693d6506-b46b-43b2-9a9f-19ebd467fe53)

**Comment by abetlen** [comment]
Sorry not yet, just closed as duplicate of #814

**Comment by sengiv** [comment]
@abetlen awesome to know it is on todo list. ✅ 🙏
Btw, I'm building something little similar, so if you need help coding this, please let me know....
Glad to help you implement this feature 😁🚀
