### ISSUE TITLE
Default value for the number of threads

### ISSUE THREAD

**Issue by avdosev** [abetlen/llama-cpp-python#89]
The current default value is cpu_count/2:

https://github.com/abetlen/llama-cpp-python/blob/b2a24bddacc7b10d1ba8a0dff1d8b5fae9bfbad3/llama_cpp/llama.py#L102

This value does not seem to be optimal for multicore systems. For example, a CPU with 8 cores will have 4 cores idle. Or to put it simply, we will get twice the slowdown (if there are no more nuances in model execution).

Related issues: https://github.com/abetlen/llama-cpp-python/issues/71

In this discussion I would like to know the motivation for such a default value, as it seems that it is not obvious to most users.

**Comment by gjmulder** [comment]
- Most physical systems are hyperthreaded
- Hyperthreading doesn't seem to improve performance due to the memory I/O bound nature of `llama.cpp`
- Might be invalid for VMs

**Comment by avdosev** [comment]
> Hyperthreading doesn't seem to improve performance due to the memory I/O bound nature of llama.cpp

It's a bit counterintuitive for me. Hypertreading was created to fully utilize the CPU during memory bound programs. 

If we are talking about limited CPU utilization on the VM, in my opinion, the library should not solve such case and should offer the most productive option for the base scenario.

In general, it is necessary to test the performance on different systems and choose the most performance default value.

**Comment by avdosev** [comment]
Okay. If the systems with hypertrading receive reductions, then for them this logic can be left, but why for systems with all physical cores logic is not different?

**Comment by gjmulder** [comment]
Closing as it is impossible to support every config of hardware.

**Comment by kevintsq** [comment]
As of today, many CPU cores have removed hyperthreading. Using `psutil.cpu_count(logical=False)` instead of simply assuming all cores are hyperthreaded should be a better way to do this.

**Comment by serhii-nakon** [comment]
And on servers sometimes hyper-threading has 2-3 virtual cores
