### ISSUE TITLE
llama_cpp conflict with transformers library

### ISSUE THREAD

**Issue by speggioale** [abetlen/llama-cpp-python#891]
Hi everyone, 

I'm currently trying to run the example script provided in the readme, but I noticed a Type error exception is thrown (and ignored) when importing the `transformers==4.35.0` library in the same file. 

# Expected Behavior

The code snippet in the next section should generate an output without throwing any error. 

# Current Behavior

By running the following code snipped, I get an exception after the output is correctly generated. I'm aware the error is ignored but I would like to understand whether that's the expected behaviour or if there is something else I'm missing. Moreover, notice that removing  `import transformers` produces the correct output. 

```python
import transformers
from llama_cpp import Llama

if __name__ == "__main__":

    llm = Llama(model_path="./models/7B/llama-model.gguf")
    output = llm("Q: Name the planets in the solar system? A: ",
                 max_tokens=32, stop=["Q:", "\n"], echo=True)

    print(output)

```
And I get the following error

```
Exception ignored in: <function _LlamaContext.__del__ at 0x7f4cfd08a3b0>
Traceback (most recent call last):
  File "/home/project/my_env/lib/python3.10/site-packages/llama_cpp/llama.py", line 418, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaModel.__del__ at 0x7f4cfd089480>
Traceback (most recent call last):
  File "/home/project/my_env/lib/python3.10/site-packages/llama_cpp/llama.py", line 238, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaBatch.__del__ at 0x7f4cfd08b7f0>
Traceback (most recent call last):
  File "/home/project/my_env/lib/python3.10/site-packages/llama_cpp/llama.py", line 664, in __del__
TypeError: 'NoneType' object is not callable
```

# Environment and Context

- x86_64 GNU/Linux
- Python 3.10.9
- GNU Make 4.2.1
- g++ 9.4.0

**Comment by abetlen** [comment]
@speggioale can you update to the latest version and lmk if the issue still appears?

**Comment by kddubey** [comment]
Appeared for me w/ v0.2.16 and v0.2.17

**Comment by bioshazard** [comment]
@abetlen possibly related to the autotokenizer? That includes transformer dep and in my tests I had to make a dedicated `venv` for the version it wanted. I had put the imports for it in the autotokenizer function itself so those deps wouldn't trigger unless you wanted to use autotokenizer. Works fine for my server endpoint use case, but those with an existing specific transformers version might run into a conflict if those deps do trigger.

**Comment by bioshazard** [comment]
@kddubey do you need that transformer version in this specific use case? Or is it a simple matter of a global pip install? If this specific use case doesn't need that specific transformers version, consider a `venv` just for this use case.

**Comment by kddubey** [comment]
@bioshazard

> do you need that transformer version in this specific use case?

No—I don't need `transformers` at all. It's just in a `venv` I use for development purposes. All of my `transformers` and `llama_cpp` code is correct with the latest versions. It's just that this (ignored) Exception is sometimes displayed

**Comment by abetlen** [comment]
@kddubey I'll have to look deeper into this, sorry about that coming up, this issue happens because of some weird behaviour during python interpreter shutdown. It's odd that the transformer import causes this but maybe there's some cleanup hook in their library that's conflicting.

**Comment by kddubey** [comment]
@abetlen no worries, consider this issue low priority :-)

**Comment by shiftybit** [comment]
I'm getting this error too, but I'm not importing transformers.
I've observed that the error occurs if I import torch, similar to @speggioale.
when I remove the import torch line, the problem goes away

**Comment by kddubey** [comment]
@papipsycho that PR hasn't been part of a release yet. You shouldn't see the ignored exception if you install main:

```
python -m pip install git+https://github.com/abetlen/llama-cpp-python.git
```

**Comment by davidmezzetti** [comment]
A similar or perhaps same root cause error happens with llama_cpp_python==0.2.26 and transformers==4.36.2

```
Exception ignored in: <function _LlamaContext.__del__ at 0x7f84740e4430>
Traceback (most recent call last):
  File "python3.8/site-packages/llama_cpp/llama.py", line 425, in __del__
  File "python3.8/site-packages/llama_cpp/_utils.py", line 24, in __enter__
RuntimeError: could not find io module state (interpreter shutdown?)
Exception ignored in: <function _LlamaModel.__del__ at 0x7f84740e04c0>
Traceback (most recent call last):
  File "python3.8/site-packages/llama_cpp/llama.py", line 241, in __del__
  File "python3.8/site-packages/llama_cpp/_utils.py", line 24, in __enter__
RuntimeError: could not find io module state (interpreter shutdown?)
Exception ignored in: <function _LlamaBatch.__del__ at 0x7f84740e7790>
Traceback (most recent call last):
  File "python3.8/site-packages/llama_cpp/llama.py", line 675, in __del__
  File "python3.8/site-packages/llama_cpp/_utils.py", line 24, in __enter__
RuntimeError: could not find io module state (interpreter shutdown?)
```
