### ISSUE TITLE
Can't import llama-cpp-python model

### ISSUE THREAD

**Issue by greywolf0324** [abetlen/llama-cpp-python#900]
My script is following:

```
from langchain.llms.llamacpp import LlamaCpp
from langchain.chains import ConversationChain
from langchain.chains.conversation.memory import ConversationSummaryMemory
from llama_cpp import Llama

llm = LlamaCpp(
    temperature=0
)
```

But, getting following error

```
Exception has occurred: KeyError
'model_path'
```

But, I can't find where llama-cpp model is.

**Comment by tk-master** [comment]
you need to specify the path to your model it seems.

```
path = 'path-to-model/model-name.gguf'
llm = Llama(model_path=path)
```

**Comment by greywolf0324** [comment]
thanks for your response
But, I can't find where llama-cpp model is.
Do I have to download it manually or is it downloaded automatically when I have installed llama-cpp-python?
if I have to download it manually, where do I have to download it and USE?

**Comment by tk-master** [comment]
yes ofc you need to download a model! Sounds like you have alot to learn but a good place to download quantized models is from https://huggingface.co/TheBloke
I would recommend 7b models, which can easily fit into a consumer gpu with 8gb of vram.. also make sure you download the GGUF format to use with llama-cpp.
Some good models from my experience are [Mistral-7B-Instruct](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF) and [dolphin-2.2.1-mistral-7B-GGUF](https://huggingface.co/TheBloke/dolphin-2.2.1-mistral-7B-GGUF)

**Comment by greywolf0324** [comment]
Thanks, 

```
from langchain.llms.llamacpp import LlamaCpp

llm = LlamaCpp(temperature = 0, model_path = 'path-to-model/model-name.gguf')
```

So, what you mean is that LLM loaders from langchain.llms can only load `.gguf` models?
or is it only for LlamaCpp?
you said that I have to learn much  :), and which do you recommend to learn?

**Comment by tk-master** [comment]
LangChain is a framework for developing applications powered by language models, it can use multiple loaders, not just llama-cpp.
Llama-cpp supports the gguf format. 
To learn more, google is your friend.. you can also find a discord (TheBloke's discord is full of knowledgeable ppl for example).
Good luck

**Comment by greywolf0324** [comment]
Thanks very much for your effort

**Comment by greywolf0324** [comment]
I've attached new problem again.
I've downloaded gguf model and it worked well yesterday.
But, it is not working now. I've shared my code and error what I'm getting
```
llm = LlamaCpp(
    temperature=0,
    model_path = "mistral-7b-instruct-v0.1.Q4_K_M.gguf",
    max_tokens=32,
    stop=["Q:", "\n"],
)
```
```
Exception has occurred: ValidationError
1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: mistral-7b-instruct-v0.1.Q4_K_M.gguf. Received error Model path does not exist: mistral-7b-instruct-v0.1.Q4_K_M.gguf (type=value_error)
  File "E:\work\Daily\11_3\dragon\ConvM\llama.py", line 22, in <module>
    llm = LlamaCpp(
pydantic.v1.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: mistral-7b-instruct-v0.1.Q4_K_M.gguf. Received error Model path does not exist: mistral-7b-instruct-v0.1.Q4_K_M.gguf (type=value_error)
```
