### ISSUE TITLE
error loading model: unknown (magic, version) combination: 46554747, 00000002; is this really a GGML file?

### ISSUE THREAD

**Issue by CRCODE22** [abetlen/llama-cpp-python#902]
K:\llama.cpp>docker run --rm -it -p 8000:8000 -v K:/models/13B:/models -e MODEL=/models/llama-2-13b.Q5_K_M.gguf ghcr.io/abetlen/llama-cpp-python:latest
llama.cpp: loading model from /models/llama-2-13b.Q5_K_M.gguf
error loading model: unknown (magic, version) combination: 46554747, 00000002; is this really a GGML file?
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/llama_cpp/server/__main__.py", line 46, in <module>
    app = create_app(settings=settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/llama_cpp/server/app.py", line 92, in create_app
    llama = llama_cpp.Llama(
            ^^^^^^^^^^^^^^^^
  File "/llama_cpp/llama.py", line 162, in __init__
    assert self.ctx is not None
           ^^^^^^^^^^^^^^^^^^^^
AssertionError

The model is downloaded from here: https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/tree/main

**Comment by abetlen** [comment]
@CRCODE22 those should work, just confirming is the entire file downloaded? I've gotten that before if I forgot to pull the file first with git lfs.

**Comment by CRCODE22** [comment]
> @CRCODE22 those should work, just confirming is the entire file downloaded? I've gotten that before if I forgot to pull the file first with git lfs.

Thank you for your reply sorry for the slow response I will close this ticket as it is too long ago to remember what the problem was but by now it should work I assume but I am using other models now.
