### ISSUE TITLE
Model generates only 16 Tokens always

### ISSUE THREAD

**Issue by shrijayan** [abetlen/llama-cpp-python#903]
**Request body**
{
  "prompt": "\n\n### Instructions:\nwrite a story\n\n### Response:\n",
  "stop": [
    "\n",
    "###"
  ]
}

**Response Body**
{  "id": "cmpl-f729eb01-6691-47c3-99f0-f30d6ab62f25",
  "object": "text_completion",  "created": 1699867559,
 "model": "llama-2-13b-chat.Q4_0.gguf", 
 "choices": [     
{  "text": "Once upon a time, in a far-off land, there was a mag",  
"index": 0,  
"logprobs": null, 
 "finish_reason": "length"     
}   ], 

 "usage": 
{  "prompt_tokens": 20,  
"completion_tokens": 16, 
 "total_tokens": 36  
 } }

In this, we can see only 16 completion_tokens generates all the time. How to solve this problem.

Terminal Input 
python3 -m llama_cpp.server --model $MODEL  --n_gpu_layers 1 --host [0.0.0.0](https://0.0.0.0/) --port 8000 --n_ctx=2048 --n_ctx=2048

**Comment by tk-master** [comment]
--max_tokens ? idk why it would be this low by default though

**Comment by abetlen** [comment]
@tk-master this is to match the openai api defaults, but yes max_tokens will increase this and there's no default limit on the chat completion endpoint

**Comment by shrijayan** [comment]
@tk-master @abetlen 

python3 -m llama_cpp.server --model $MODEL  --n_gpu_layers 1 --host 0.0.0.0 --port 8000 --n_ctx=2048 

This is the command that I used to start the FASTAPI, when I  add --max_tokens=2048 it says __main__.py: error: unrecognized arguments: --max_tokens=2048.

**Comment by shrijayan** [comment]
> sorry, can you try something like..
> 
> ```
> {
>   "prompt": "\n\n### Instructions:\nWhat is the capital of France?\n\n### Response:\n",
>   "stop": [
>     "\n",
>     "###"
>   ],
>   "max_tokens" 200
> }
> ```
Hello @tk-master,

First of all thank you for answering the questions.

This is not working it gives the output like **Internal Server Error**. I also tried  [max_tokens 200, "max_tokens"=200, max_tokens=200, n_ctx=200, "n_ctx"=200, "n_ctx" 200] all produces same output.

**Comment by abetlen** [comment]
That should be `"max_tokens": 200` otherwise the json is invalid. For example:

```json
{
  "prompt": "\n\n### Instructions:\nWhat is the capital of France?\n\n### Response:\n",
  "stop": [
    "\n",
    "###"
  ],
  "max_tokens": 200
}
```

**Comment by shrijayan** [comment]
> ```json
> "max_tokens": 200
> ```

Thank you so much for the help. It is working for the FASTAPI. I'm using this API to call from Langchain, but therer it is only generating 16 tokens.

Code
```
from langchain.llms import TextGen
llm = TextGen(model_url="http://0.0.0.0:8000")

memory = ConversationSummaryBufferMemory(llm=llm, memory_key="history", input_key="question",  max_token_limit=250)

qa = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectorstore.as_retriever(),
    chain_type_kwargs={
        "verbose": True,
        "prompt": prompt,
        "memory": memory,
    },
)

query = "What did the president say about Ketanji Brown Jackson"
qa.run(query)
```

Terminal Output:
```
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1118.88 ms
llama_print_timings:      sample time =       2.36 ms /    16 runs   (    0.15 ms per token,  6791.17 tokens per second)
llama_print_timings: prompt eval time =    7819.48 ms /   610 tokens (   12.82 ms per token,    78.01 tokens per second)
llama_print_timings:        eval time =     859.14 ms /    15 runs   (   57.28 ms per token,    17.46 tokens per second)
llama_print_timings:       total time =   10233.68 ms
INFO:     127.0.0.1:61313 - "POST /v1/engines/copilot-codex/completions HTTP/1.1" 200 OK
```

**Comment by shrijayan** [comment]
> > ```json
> > "max_tokens": 200
> > ```
> 
> Thank you so much for the help. It is working for the FASTAPI. I'm using this API to call from Langchain, but therer it is only generating 16 tokens.
> 
> Code
> 
> ```
> from langchain.llms import TextGen
> llm = TextGen(model_url="http://0.0.0.0:8000")
> 
> memory = ConversationSummaryBufferMemory(llm=llm, memory_key="history", input_key="question",  max_token_limit=250)
> 
> qa = RetrievalQA.from_chain_type(
>     llm=llm,
>     chain_type="stuff",
>     retriever=vectorstore.as_retriever(),
>     chain_type_kwargs={
>         "verbose": True,
>         "prompt": prompt,
>         "memory": memory,
>     },
> )
> 
> query = "What did the president say about Ketanji Brown Jackson"
> qa.run(query)
> ```
> 
> Terminal Output:
> 
> ```
> Llama.generate: prefix-match hit
> 
> llama_print_timings:        load time =    1118.88 ms
> llama_print_timings:      sample time =       2.36 ms /    16 runs   (    0.15 ms per token,  6791.17 tokens per second)
> llama_print_timings: prompt eval time =    7819.48 ms /   610 tokens (   12.82 ms per token,    78.01 tokens per second)
> llama_print_timings:        eval time =     859.14 ms /    15 runs   (   57.28 ms per token,    17.46 tokens per second)
> llama_print_timings:       total time =   10233.68 ms
> INFO:     127.0.0.1:61313 - "POST /v1/engines/copilot-codex/completions HTTP/1.1" 200 OK
> ```

Does the terminal output say that is it generating 610 tokens, but the answer displayed is only 16 tokens.

**Comment by shrijayan** [comment]
Even this code also generates only 16 tokens

Code
```
import requests
import json


url = 'http://0.0.0.0:8000/v1/engines/copilot-codex/completions'

headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json',
}

data = {
    "prompt": f"\n\n### Instructions:\nwrite a poem about nature\n\n### Response:\n",
    "stop": [
    ]
}

response = requests.post(url, headers=headers, data=json.dumps(data))
result = response.json()

print(result)
```

output
```
'choices': [{'text': "\nIn nature's embrace, I find my peace\nBeneath", 'index': 0, 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 22, 'completion_tokens': 16, 'total_tokens': 38}
```

**Comment by shrijayan** [comment]
> That should be `"max_tokens": 200` otherwise the json is invalid. For example:
> 
> ```json
> {
>   "prompt": "\n\n### Instructions:\nWhat is the capital of France?\n\n### Response:\n",
>   "stop": [
>     "\n",
>     "###"
>   ],
>   "max_tokens": 200
> }
> ```

@abetlen Thank you so much this worked

**Comment by Mihaiii** [comment]
This is pretty silly. I also had this issue and I was confident it was a regression (everything works fine before updating the library).

**IMO this change should come with a bump major in version as it breaks current functionality.**

**Comment by abetlen** [comment]
Hey @Mihaiii sorry for the trouble, yeah I should've avoided making that change. The intention was to match the OpenAI API defaults but obviously this was an unintentional breaking change and I'll avoid anything like that in the future. Cheers.

**Comment by segestic** [comment]
What worked for me.. -----------------------

Tried all above, it didn't work, number of tokens still remained same. What worked for me - Setting the stop to after length of paragraphs e.g 3 paragraphs in below
```
{
  "prompt": "\n\n### Instructions:\n Write me a short poem \n\n### Response:\n",
  "stop": [
    "\n \n \n ",
    "###"
  ],
  "max_tokens": 200
}
```
