### ISSUE TITLE
Accessing the low-level API

### ISSUE THREAD

**Issue by andersRuge** [abetlen/llama-cpp-python#91]
Hi,

Thank you for making this port first of all! I am trying to access the low-level API, and I was wondering if there is an example somewhere in the documentation, that I missed?

I would like to be able to mirror the example from the main llama.cpp implementation:
`./main -m ./models/7B/ggml-model-q4_0.bin -c 512 -b 1024 -n 256 --keep 48 \
    --repeat_penalty 1.0 --color -i \
    -r "User:" -f prompts/chat-with-bob.txt`

**Comment by vmajor** [comment]
That program does not work for me. Did you manage to make it run?
