### ISSUE TITLE
Add min p arg to server

### ISSUE THREAD

**Issue by ArtyomZemlyak** [abetlen/llama-cpp-python#911]
Add `min p` arg to server
Related to :
https://github.com/ggerganov/llama.cpp/pull/3841

**Comment by iandennismiller** [comment]
It looks like `min p` was added to llama-cpp-python recently:

https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama_cpp.py#L1560

https://github.com/abetlen/llama-cpp-python/commit/d808fd436c2f0f4df1f491e99c8bcb3b98b4bcbe?diff=split#diff-9184e090a770a03ec97535fbef520d03252b635dafbed7fa99e59a5cca569fbcR1568

**Comment by LorenzoBoccaccia** [comment]
I think it's missing from llama.py sampling

**Comment by ddh0** [comment]
Second this! It looks very promising and I'm excited.

**Comment by ddh0** [comment]
Pinging @abetlen, I finished this. See here: https://github.com/ddh0/llama-cpp-python/commit/e8e05bbb0f4100d33b65f9595c81e341814c8097

Apologies if this isn't the right way to submit a fix, I'm new to github. But I've tested it and it's working as expected. Let me know if I can help in any way.

**Comment by tk-master** [comment]
@ddh0 bad timing, I just made this pr :P https://github.com/abetlen/llama-cpp-python/pull/921

**Comment by m-from-space** [comment]
> tested at temperature 1.6 and 3.0 the assistant remains creative and repetition issues are gone even with a lower repetition penalty. at 3.0 seems to be too creative and basically ignore facts passed in the context, but remains coherent and inteligible.
> 
> still I think it should be disabled by default for backcompat

Hey there, I just saw that this is now implemented. How exactly do I activate `min_p` sampling when calling the model? Is it activated by default?

**Comment by tk-master** [comment]
> > tested at temperature 1.6 and 3.0 the assistant remains creative and repetition issues are gone even with a lower repetition penalty. at 3.0 seems to be too creative and basically ignore facts passed in the context, but remains coherent and inteligible.
> > still I think it should be disabled by default for backcompat
> 
> Hey there, I just saw that this is now implemented. How exactly do I activate `min_p` sampling when calling the model? Is it activated by default?

the same way you'd change the temperature, top_k etc.. it is activated with a small value by default

**Comment by m-from-space** [comment]
> the same way you'd change the temperature, top_k etc.. it is activated with a small value by default

Thank you. So in which order are sampling methods like `min_p`, `top_k` and `top_p` executed? Can I change that order?

**Comment by tk-master** [comment]
> > the same way you'd change the temperature, top_k etc.. it is activated with a small value by default
> 
> Thank you. So in which order are sampling methods like `min_p`, `top_k` and `top_p` executed? Can I change that order?

take a look at these lines here.. https://github.com/abetlen/llama-cpp-python/blob/4026166e682e6c080aeb50e00c4bb2312145f061/llama_cpp/llama.py#L1160-L1168
The order is hardcoded at the moment.. but in my opinion you don't really want or need mixing min_p with top_p and top_k samplers, it's probably better to just disable top_p (top_p=1) etc and just use min_p and temp.
But if you wanna change the order and play with it, just edit that file.. it's simple.
