### ISSUE TITLE
llama_tokenize: too many tokens

### ISSUE THREAD

**Issue by ylchin** [abetlen/llama-cpp-python#92]
I was trying to run an alpaca model on a framework with a relatively large context window, and the following message keeps popping up:
```llama_tokenize: too many tokens```
how could i bypass this, and what is the maximum number of tokens in this case?

**Comment by gjmulder** [comment]
I believe this may be a limit in `llama.cpp`. There was a discussion about having to increase some memory buffers to support larger context sizes.

**Comment by abetlen** [comment]
@gjmulder @ylchin fixed, you can now tokenize longer prompts, while this doesn't help with processing longer contexts it should help with chunking conversations / documents embeddings.
