### ISSUE TITLE
Support finetuning

### ISSUE THREAD

**Issue by fakerybakery** [abetlen/llama-cpp-python#923]
Hi, can you support finetuning? Llama.cpp supports finetuning. Thank you!

**Comment by chrisptang** [comment]
looking for the same feature here!

llama.cpp now supports loading with LoRA adapters:
https://github.com/ggerganov/llama.cpp/tree/master/examples/finetune

**Comment by abetlen** [comment]
Closing this as it's a duplicate of #814 

It's on my roadmap but it currently requires some updates to llama.cpp to make this accessible to bindings outside of that project.
