### ISSUE TITLE
llava image embed failed

### ISSUE THREAD

**Issue by Leon-Sander** [abetlen/llama-cpp-python#935]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
Model outputs a description of the image.

# Current Behavior
I see the terminal output "llava_eval_image_embed : failed to eval" and the chat response states that there was no image input.
(It works when I run it in the manner explained here https://llama-cpp-python.readthedocs.io/en/latest/server/#multimodal-models , but I dont want to run the server, but directly the code as seen below)

Here a snippet from the terminal output:
```
clip_model_load: total allocated memory: 195.95 MB

encode_image_with_clip: image encoded in  1469.64 ms by CLIP (    2.55 ms per image patch)
llava_eval_image_embed : failed to eval


Chat Response: {'id': 'chatcmpl-09e75609-2fc2-4686-adfd-96da33bf3f7f', 'object': 'chat.completion', 'created': 1700642660, 'model': 'llava_ggml-model-q5_k.gguf', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': " I'm sorry, but you haven't provided any image for me to describe. Please provide the image so that I can assist you better."}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 29, 'completion_tokens': 30, 'total_tokens': 59}}

```

# Code

```
import llama_cpp as llama
from llama_cpp.llama_chat_format import Llava15ChatHandler


def main():
    clip_model_path = "mmproj-model-f16.gguf"
    llama_model_path = "llava/llava_ggml-model-q5_k.gguf"
    llama_model = llama.Llama(llama_model_path, logits_all=True)

    chat_handler = Llava15ChatHandler(clip_model_path=clip_model_path, verbose=True)

    image_url = "https://raw.githubusercontent.com/coqui-ai/TTS/dev/images/TTS-performance.png"
    messages = [
        {"role": "system", "content": "You are an assistant who perfectly describes images."},
        {
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {"url": image_url}},
                {"type" : "text", "text": "Describe this image in detail please."}
            ]
        }
    ]

    response = chat_handler(
        llama=llama_model,
        messages=messages,
    )

    print("Chat Response:", response)

main()
```

# Steps to Reproduce

1. Install library with pip
2. download models https://huggingface.co/mys/ggml_llava-v1.5-7b/tree/main
3. run above code

**Comment by johnwick123f** [comment]
Yep, this is the same problem I have as well.

**Comment by johnwick123f** [comment]
@Leon-Sander I solved it by putting the n_context as 1024, try that it might solve it. The default context is 512.

**Comment by Leon-Sander** [comment]
@johnwick123f thank you, it finally works.

```
llama_model = llama.Llama(llama_model_path, logits_all=True,  n_ctx = 1024)
```

**Comment by abetlen** [comment]
@Leon-Sander perfect, I've included this info in the README along with an example for setting up the multi-modal model in python.

**Comment by Leon-Sander** [comment]
@abetlen damn you are fast, I wanted to make a pull request out of it and be a contributor. Hope this saves some people some time.
