### ISSUE TITLE
TypeError: Llama.create_completion() got an unexpected keyword argument 'min_p'

### ISSUE THREAD

**Issue by makingitup** [abetlen/llama-cpp-python#949]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x ] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x ] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Should show output when queried. 

# Current Behavior

Output is empty with reason for finish saying 'stop'.  Have been getting this since about latest update to 0.2.19

# Failure Information (for bugs)

Traceback (most recent call last):
File "/workspace/text-generation-webui/modules/callbacks.py", line 57, in gentask
ret = self.mfunc(callback=_callback, *args, **self.kwargs)
File "/workspace/text-generation-webui/modules/llamacpp_model.py", line 141, in generate
completion_chunks = self.model.create_completion(
TypeError: Llama.create_completion() got an unexpected keyword argument 'min_p'

# Steps to Reproduce

1. Create a runpod instance using 'RunPod TheBloke LLMs' as a template using any gpu
3. Download and load any llm
4. Make any query
5. Output is empty

**Comment by makingitup** [comment]
Works if switch model loader from llama.cpp to ctransformer but output is extremely slow and unusable.

**Comment by tk-master** [comment]
You should probably submit this issue in text-generation-webui
