### ISSUE TITLE
How to find the optimal value for the number of layers to offload to GPU? aka ngl parameter

### ISSUE THREAD

**Issue by utility-aagrawal** [abetlen/llama-cpp-python#960]
Hi,

I am using a llama-2-7b-chat.Q4_K_M.gguf model locally and am trying to identify the optimal number of layers to offload to GPU. How can I find that value? Currently, I have a Tesla T4 GPU but can get something more powerful since reducing the inference time is my topmost priority. Please advise. Let me know if you need any additional details. Thanks!

**Comment by Abhi011999** [comment]
for that model and gpu, just offload everything to gpu, use `-1`
