### ISSUE TITLE
如何动态去设置temperature，top_p和repeat_penalty

### ISSUE THREAD

**Issue by yuxuan2015** [abetlen/llama-cpp-python#97]
如何动态去设置temperature，top_p和repeat_penalty等参数，就是每次生成结果的时候，可以动态去调整这些参数的值
model = Llama(model_path="./llama-ggml-q4_0.bin")
result = model(input, max_tokens=max_tokens, stop=[], echo=True, temperature=temperature, top_p=top_p, top_k=top_k, repeat_penalty=repeat_penalty, stream=stream)
这样用的话，会显示result是 'generator' object，正常生成的应该是一个字典

**Comment by abetlen** [comment]
Hi @yuxuan2015 one approach is to generate a single token at a time using max_tokens and changing the temperature with each (you'll need to concatenate the new tokens to your prompt). The new changes to the Llama class allow it to pick up where it left off so it shouldn't be very inefficient.
