### ISSUE TITLE
llama : add Qwen support (#4281)

### ISSUE THREAD

**Issue by zwqjoy** [abetlen/llama-cpp-python#980]
https://github.com/ggerganov/llama.cpp/commit/37c746d687d877bc11803e96b4dc5f378b83c0a0

**Comment by sorasoras** [comment]
+1 llama cpp support for qwen is  currently functional.

**Comment by 525957887** [comment]
+1

**Comment by llp45135** [comment]
+1

**Comment by afonsoguerra** [comment]
+1

**Comment by ouyyy18** [comment]
+1
error loading model: unknown model architecture: 'qwen'
llama_load_model_from_file: failed to load model
