### ISSUE TITLE
how to run llama.py/llama_ccp.py?

### ISSUE THREAD

**Issue by sussyboiiii** [abetlen/llama-cpp-python#99]
Hello,
I've seen that theres an API to use llama.cpp in an Open AI API like style, but I would rather want to run it like you do main when llama.cpp is made executable. 

So I have tried to run llama_cpp.py which gives this error `FileNotFoundError: Shared library with base name 'llama' not found`
and I have tried to run llama.py which gives this error `ImportError: attempted relative import with no known parent package`

before you ask I have installed the llama-cpp-python library.
Any help is appreciated, Thank you!

**Comment by jmvalente** [comment]
What's the code you're calling and how did you install?

**Comment by sussyboiiii** [comment]
I did clone this repo and installed the llama-cpp-python package. Then I went into ./llama-cpp-python/llama_cpp and there I wanted to run llama.py or llama_cpp.py like you would if you installed llama.cpp where you run llama.cpp.

**Comment by Priestru** [comment]
> I did clone this repo and installed the llama-cpp-python package. Then I went into ./llama-cpp-python/llama_cpp and there I wanted to run llama.py or llama_cpp.py like you would if you installed llama.cpp where you run llama.cpp.

pip install jupyterlab
pip install notebook
cd your/folder/with/llama
jupyter notebook

![image](https://user-images.githubusercontent.com/108554892/234545280-bc33815d-9351-401b-a52b-d2b8f3478f31.png)

```
>>> from llama_cpp import Llama
>>> llm = Llama(model_path="./models/7B/ggml-model.bin")
>>> output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
>>> print(output)
{
  "id": "cmpl-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "object": "text_completion",
  "created": 1679561337,
  "model": "./models/7B/ggml-model.bin",
  "choices": [
    {
      "text": "Q: Name the planets in the solar system? A: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune and Pluto.",
      "index": 0,
      "logprobs": None,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 14,
    "completion_tokens": 28,
    "total_tokens": 42
  }
}
```

>> change path to model and run

**Comment by sussyboiiii** [comment]
Thank you for your response!
What are you trying to tell me? 
I made the API work but im not happy with it as everytime I want a new prompt to be answered it needs to re load the model and it also likes to speak chinese which I am not capable of speaking sadly.

Thats why I wanted to run the main files in this repo on their own to maybe prevent the models from needing to be reloaded every time and speaking chinese as you can't specify a conversation before asking it something and then its just chinese somethimes if you would ask "Hello" as an example.

**Comment by jmvalente** [comment]
Can you please share exactly what you're running? It sounds like you're invoking llama_cpp.py directly which won't work. You need to import the modules as @Priestru showed in that example or check out the readme section on running llama_cpp.setver

**Comment by sussyboiiii** [comment]
Thanks!
